adobe-experience-league/exlm

blocks/toc/toc.css, blocks/toc/toc.js, styles/lazy-styles.css, styles/lazy-styles.scss
Jira ID: UGP-10840
**Summary of Changes:**
- Removed "view more/less" functionality to simplify the TOC.
- Updated initial load behavior to only expand the active section, collapsing all others.
- Implemented expand/collapse functionality for dropdowns, expanding all subpages when clicked.
- Controlled visibility using aria-expanded and aria-hidden attributes to enhance accessibility.
- Added logic to collapse sibling submenus at the same level when expanding a submenu.
- Introduced scrolling behavior to keep the active element in view during navigation.
**Detailed Updates:**
- updateTocContent: Managed dropdown visibility with aria-expanded and aria-hidden, and …
=> Feature/UGP-10840 Improve dropdown behavior in table of contents

blocks/tags/tags.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1885 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives/transitioning-to-adobe-analytics
- After: https://exlm-1885--exlm--adobe-experience-league.hlx.live/en/perspectives/transitioning-to-adobe-analytics
=> EXLM-1885 Add border to all tag blocks

blocks/marquee/marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1897
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/perspectives
- After: https://fix-marquee-img--exlm--adobe-experience-league.hlx.page/en/perspectives
=> fix: marquee img width

blocks/featured-content/featured-content.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1546
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives
- After: https://feat-exlm-1546--exlm--adobe-experience-league.hlx.live/en/perspectives
=> Featured content block CSS update

blocks/article-marquee/article-marquee.js, scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1923
Test URLs::
- After: https://exlm-1923--exlm--adobe-experience-league.hlx.live/
=> chore: remove bookmarks for perspective cards, pages

blocks/product-experience-level/product-experience-level.css, scripts/profile/profile-interests.css, scripts/profile/profile-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1921
Test URLs:
- After: https://fix-exlm-1921--exlm--adobe-experience-league.hlx.live
=> fix: product exp level css EXLM-1921

blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1846
Test URLs:
- After: https://exlm-1846--exlm--adobe-experience-league.hlx.live
=> EXLM 1846 - Role card selection bug fix

scripts/auth/profile.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1922
Test URLs:
- After: https://feat-exlm-1922-fix--exlm--adobe-experience-league.hlx.page
=> EXLM-1922 Revert code changes for fetch community profile

blocks/browse-filters/browse-filter-utils.js, blocks/header/header.js
Jira ID: EXLM-1929 
Reverts
https://github.com/adobe-experience-league/exlm/pull/1055
https://github.com/adobe-experience-league/exlm/pull/1060
https://github.com/adobe-experience-league/exlm/pull/1082
Test URLs:
- After: https://exlm-1929--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-1929 Remove feature flag dependency for Perspectives

blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1846
Test URLs:
- After: https://exlm-1846--exlm--adobe-experience-league.hlx.live
=> EXLM 1846 - Role card bug in profile page fix

scripts/scripts.js
Jira ID: EXLM-1933
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
- After: https://exlm-1933--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> EXLM-1933 ADLS URL Update

blocks/bookmarks/bookmarks.js
Jira ID: EXLM-1783
Test URLs:
- After: https://exlm-1783--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/profile/bookmarks---achievements.html?ref=exlm-1783
=> EXLM-1783 Bookmarks issues fix

blocks/mini-toc/mini-toc.js, blocks/mini-toc/utils.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives/transitioning-to-adobe-analytics
- After: https://bugfix-exlm-1925--exlm--adobe-experience-league.hlx.page/en/perspectives/transitioning-to-adobe-analytics
=> Mini TOC - Scroll & Highlight Issue

blocks/header/header.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1936--exlm--adobe-experience-league.hlx.live/
=> Sign up modal via Query Param

blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js, blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1897
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/featured-content
- After: https://exlm-1897--exlm--adobe-experience-league.hlx.page/en/featured-content
=> fix: blurry images on featured content exlm-1897

scripts/data-service/coveo/coveo-exl-pipeline-helpers.js
Jira ID:
Test URLs:
- After: https://pipeline-adapater-fix--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Wrap coveo call in try/catch and handle no data case

blocks/article-marquee/article-marquee.js, scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1937
Test URLs::
- After: https://exlm-1937--exlm--adobe-experience-league.hlx.live/
=> chore: enable perspective bookmarks on lower env EXLM-1937

styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1941
Test URLs:
- After: https://feat-exlm-1941--exlm--adobe-experience-league.hlx.page
=> EXLM-1941 Center aligning default content text for profile section

scripts/analytics/lib-analytics.js
Jira ID: EXLM-1935
Test URLs:
- After: https://exlm-1935--exlm--adobe-experience-league.hlx.live
=> EXLM-1935 Datalayer for Perspectives mini-toc

styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1941
Test URLs:
- After: https://feat-exlm-1941-fix--exlm--adobe-experience-league.hlx.page
=> EXLM-1941 Margin top fix

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1938
Test URLs:
- After: https://feat-exlm-1938-ue--exlm--adobe-experience-league.hlx.page
=> EXLM-1938 UE changes

scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1880
Test URLs:
- After: https://exlm-1880--exlm--adobe-experience-league.hlx.live/
=> feat: remove close on sign-up modal exlm-1880

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1940
Test URLs:
- After: https://feat-exlm-1940-ue--exlm--adobe-experience-league.hlx.page
=> EXLM-1940 UE changes

blocks/product-interests/product-interests.js, scripts/form-validator.js, scripts/signup-flow/signup-flow.js, scripts/toast/toast.js, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://feature-exlm-1905--exlm--adobe-experience-league.hlx.live/
=> Sign up modal - Product interest validation

blocks/embed/embed.js, blocks/playlist/playlist-utils.js, scripts/analytics/lib-analytics.js
Jira ID: UGP-10130 
Test URLs:
- After: https://ugp-10130--exlm--adobe-experience-league.hlx.page/en/playlists/advanced-tasks-in-adobe-acrobat
=> UGP-10130 - Add videoPlay event for both Embed and playlists

blocks/playlist/playlist.js
Jira ID: UGP-11296
Test URLs:
- After: https://ugp-10130--exlm--adobe-experience-league.hlx.page/en/playlists/advanced-tasks-in-adobe-acrobat
=> UGP-11296 - Fix missing paragraph in Transcript

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1957
Test URLs:
- After: https://exlm-1957--exlm--adobe-experience-league.hlx.live
=> Account URL update EXLM-1957

blocks/playlist/playlist.js
Jira ID: UGP-11280
Test URLs:
- After: https:// ugp-11280--exlm--adobe-experience-league.hlx.page/en/playlists/aem-cloud-manager-skill-builder
=> Better handling of playlist history and browser back/forward

scripts/signup-flow/signup-flow.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1961
Test URLs:
- After: https://exlm-1961--exlm--adobe-experience-league.hlx.live
=> fix: flicker on scroll exlm-1961

blocks/playlist/playlist-utils.js, blocks/playlist/playlist.js
Jira ID: UGP-11367
Test URLs:
- After:  https://ugp-11367--exlm--adobe-experience-league.hlx.page/en/playlists/aem-cloud-manager-skill-builder
=> Show Transcripts Not Available Message when applicable

blocks/playlist/playlist-utils.js, blocks/playlist/playlist.js, scripts/toast/toast.js, styles/styles.css, styles/styles.scss
Jira ID: UGP-11012
Test URLs:
- After: https://ugp-11012--exlm--adobe-experience-league.hlx.page/en/playlists/aem-cloud-manager-skill-builder?martech=off
=>  UGP-11012 - Show Notice when playlist is redirected from courses

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1957
Test URLs:
- After: https://revert-1128-exlm-1957--exlm--adobe-experience-league.hlx.live
=> Revert "Account URL update EXLM-1957"

blocks/header/header.js, blocks/product-interests/product-interests.css, scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1905--exlm--adobe-experience-league.hlx.live/
=> Sign up modal - Product interest alignment

scripts/events/signup-flow-event.js
Jira ID:
Test URLs:
- After: https://signup-flow--exlm--adobe-experience-league.hlx.live
=> Fixed typo for modalSeen

scripts/profile/profile-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2008
Test URLs:
- After: https://exlm-2008--exlm--adobe-experience-league.hlx.page
=> EXLM 2008 - Experience level block revert default value from blank to beginner

scripts/dropdown/dropdown.js, scripts/profile/profile-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2008
Test URLs:
- After: https://exlm-2008--exlm--adobe-experience-league.hlx.live
=> EXLM 2008 - Experience level block No request for default selections

scripts/events/signup-flow-event.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2009 
Test URLs:
- After: https://exlm-2009--exlm--adobe-experience-league.hlx.live
=> EXLM 2009 - Fix Config date not present in metadata for some pages

scripts/events/signup-flow-event.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2009
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live
After: https://revert-1146-exlm-2009--exlm--adobe-experience-league.hlx.live/
=> Revert "EXLM 2009 - Fix Config date not present in metadata for some pages"

blocks/bookmarks/bookmarks.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2019
Test URLs:
- After: https://exlm-2019--exlm--adobe-experience-league.hlx.live
=> feat: show recently added bookmarks up top EXLM-2019

blocks/bookmarks/bookmarks.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1857
Test URLs:
- After: https://fix-bookmark-order--exlm--adobe-experience-league.hlx.live
=> fix: ordering of bookmarks on profile layer

404.html, blocks/bookmarks/bookmarks.js, blocks/browse-filters/browse-filter-utils.js, blocks/tabbed-cards/tabbed-cards.js, component-models.json, scripts/browse-card/browse-card-utils.js, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-paths-adaptor.js, scripts/data-service/coveo/coveo-exl-pipeline-constants.js, scripts/data-service/coveo/coveo-exl-pipeline-helpers.js
Jira ID: EXLM-2026
Test URLs:
- After: https://exlm-2026--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2026 Update Course content type to Playlist

blocks/bookmarks/bookmarks.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1857
Test URLs:
- After: https://EXLM-1857-bookmark--exlm--adobe-experience-league.hlx.live
=> chore: read type from article data full meta EXLM-1857

blocks/marquee/marquee.js, blocks/sign-up/sign-up.js, component-models.json
Jira ID:
Test URLs:
- After: https://feature-exlm-2011--exlm--adobe-experience-league.hlx.live/
=> Marquee & Signup Blocks Changes

scripts/browse-card/browse-card-utils.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block?martech=off
- After: https://exlm-2026--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block?martech=off
=> EXLM-2026 Thumbnail for playlists

scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1972
Test URLs:
- After: https://playlist-exlm-1972--exlm--adobe-experience-league.hlx.live
=> feat: handle playlist bookmarks EXLM-1972

blocks/playlist/playlist.js
Jira ID:
Test URLs:
- After: https://ugp-11466--exlm--adobe-experience-league.hlx.page/en/playlists/create-calculated-fields-in-custom-forms?martech=off
=> update playlist length on progress

styles/lazy-styles.css, styles/theme/docs.css, styles/theme/docs.scss
Jira ID: UGP-11200
Test URLs:
- After: https://ugp-11200--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/implementing/developer-tools/maven-plugin?martech=off#using-the-aem-project-archetype-to-generate-aem-projects
=> UGP-11200 - Remove unwanted section spacing

blocks/profile-rail/profile-rail.js
Jira ID:
Test URLs:
- After: https://profile--exlm--adobe-experience-league.hlx.live
=> Moved hardcoded text to placeholders

blocks/marquee/marquee.js, blocks/product-experience-level/product-experience-level.js, blocks/sign-up/sign-up.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2011
Test URLs:
- After: https://marquee-fix--exlm--adobe-experience-league.hlx.live
=> EXLM-2011 - Marquee CTA issue 

blocks/user-profile-card/user-profile-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1983
Test URLs:
- After: https://user-profile-icons--exlm--adobe-experience-league.hlx.live
=> chore: user profile card icons fix

blocks/icon-block/icon-block.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2046
Test URLs:
- After: https://exlm-2046--exlm--adobe-experience-league.hlx.live
=> chore: open icon-block links in new tab exlm-2046

scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://hotfix-live-events--exlm--adobe-experience-league.hlx.live
=> Live events

scripts/dropdown/dropdown.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2058
Test URLs:
- After: https://feat-exlm-2058--exlm--adobe-experience-league.hlx.page
=> EXLM-2058 Dropdown class name fix

blocks/profile-tab/profile-tab.js, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://fix-profiletab--exlm--adobe-experience-league.hlx.live
=> Fix profile issues

blocks/bookmarks/bookmarks.css, scripts/data-service/article-data-service.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2046
Test URLs:
- After: https://article-locale--exlm--adobe-experience-league.hlx.live
=> chore: add locale for article URL

scripts/profile/profile-interests.js
Jira ID:
Test URLs:
- After: https://translation--exlm--adobe-experience-league.hlx.live
=> Placeholder key fix

scripts/user-actions/bookmark.js, scripts/user-actions/copy-link.js
Jira ID:
Test URLs:
- After: https://bugfix-bookmark-tooltip--exlm--adobe-experience-league.hlx.live/
=> Tooltip Fixes

blocks/playlist-browse/dom-helpers.js, blocks/playlist-browse/playlist-browse.js, blocks/playlist/playlist.js, scripts/scripts.js
=> Playlist Bugs: Translating Filters and fix video iframe url.

blocks/playlist/actions/playlist-bookmark-action.js, blocks/playlist/playlist.js, scripts/data-service/article-data-service.js, scripts/scripts.js
=> Playlist Bugs: Translating Filters, fix video iframe url, fix language bookmark issue

scripts/profile/personalized-home.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1990
Test URLs:
- After: https://exlm-1990--exlm--adobe-experience-league.hlx.live
=> EXLM 1990 - Rename common to shared for PHP

blocks/profile-welcome/profile-welcome.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2084
Test URLs:
- After: https://feat-exlm-2013-cssfix--exlm--adobe-experience-league.hlx.page
=> EXLM-2084 CSS fix

blocks/profile-welcome/profile-welcome.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2084
Test URLs:
- After: https://feat-exlm-2084--exlm--adobe-experience-league.hlx.page
=> EXLM-2084 Icon CSS fix

blocks/product-interests/product-interests.css, scripts/signup-flow/signup-flow.css
Jira ID:
Test URLs:
- After: https://feature-exlm-2063--exlm--adobe-experience-league.hlx.live/
=> Product List - 2 Column Changes

scripts/profile/personalized-home.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2087
Test URLs:
- After: https://exlm-2087--exlm--adobe-experience-league.hlx.live
=> EXLM 2087 - PHP IOS fix top-level await not supported

scripts/profile/profile.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2064
Test URLs:
- After: https://feat-exlm-2064--exlm--adobe-experience-league.hlx.page
=> EXLM-2064 Character added for industry

blocks/role-and-industry/role-and-industry.js, scripts/signup-flow/signup-flow.js
Jira ID:
Test URLs:
- After: https://feature-exlm-2044--exlm--adobe-experience-league.hlx.live/
=> Role - Validation Check

scripts/profile/personalized-home.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2087
Test URLs:
After: https://revert-1206-exlm-2087--exlm--adobe-experience-league.hlx.live/
=> Revert "EXLM 2087 - Retrieve profile from session storage due to issue in safari"

blocks/role-and-industry/role-and-industry.css, component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2082
Test URLs:
- After: https://feat-exlm-2082--exlm--adobe-experience-league.hlx.page
=> EXLM-2082 Heading type added for roles heading in role industry block

blocks/product-interests/product-interests.css, blocks/product-interests/product-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2083
Test URLs:
- After: https://bug-fix-2083--exlm--adobe-experience-league.hlx.live
=> Product Interest Block Font Size Update

scripts/analytics/lib-analytics.js
Jira ID: EXLM-2081
Test URLs:
- After: https://exlm-2081--exlm--adobe-experience-league.hlx.live
=> EXLM-2081 siteSubSection1 updates for perspectives

blocks/product-interests/product-interests.js
Jira ID:
Test URLs:
- After: https://feature-exlm-2070--exlm--adobe-experience-league.hlx.live/
=> Product Interest Validation

component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-2033
Test URLs:
- After: https://exlm-2033--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/profile/home/complete.html?ref=exlm-2033
=> EXLM-2033 Recommended content block

blocks/article-marquee/article-marquee.css, blocks/detailed-teaser/detailed-teaser.css, blocks/footer/footer.css, blocks/footer/footer.scss, blocks/marquee/marquee.css, blocks/playlist-browse/playlist-browse.css, blocks/sign-up/sign-up.css, blocks/teaser/teaser.css, scripts/articles/articles.css, styles/styles.css, styles/styles.scss, styles/theme/profile.css, styles/theme/profile.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2088
Test URLs:
- After: https://exlm-2088--exlm--adobe-experience-league.hlx.live
=> EXLM 2088 - Increase max-width for profile pages

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2032
Test URLs:
- After: https://feat-exlm-2032--exlm--adobe-experience-league.hlx.page
=> EXLM-2032 Removing content type from page metadata

scripts/profile/profile.js
Jira ID: EXLM-2104
Test URLs:
- After: https://exlm-2104--exlm--adobe-experience-league.hlx.live?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/profile/profile-settings.html?ref=exlm-2104
=> EXLM-2104 UE - Load Adobe Account card and User Profile Card

scripts/events/signup-flow-event.js, scripts/signup-flow/signup-flow.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2069
Test URLs:
- After: https://feat-incomplete-profile--exlm--adobe-experience-league.hlx.live
=> feat: incomplete profile modal

blocks/role-and-industry/role-and-industry.js
Jira ID:
Test URLs:
- After: https://feature-exlm-2044--exlm--adobe-experience-league.hlx.live/
=> Adding Default Selection Text

scripts/signup-flow/signup-flow.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2069
Test URLs:
- After: https://feat-incomplete-profile-2--exlm--adobe-experience-league.hlx.live
=> feat: incomplete profile modal path update

component-definition.json, component-filters.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2093 
Test URLs:
- After: https://exlm-2093--exlm--adobe-experience-league.hlx.live
=> EXLM 2093 - Add Iframe app to UE

component-models.json
Jira ID: EXLM-2092
Test URLs:
- After: https://exlm-2092--exlm--adobe-experience-league.hlx.live
=> EXLM-2092 Fixed aem-content model configuration

blocks/toc/toc.css, blocks/toc/toc.js, styles/lazy-styles.css, styles/lazy-styles.scss
Jira ID: UGP-10839 / UGP-10847
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/sites/administering/operations/troubleshoot
- After: https://feature-UGP-10839_47--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/sites/administering/operations/troubleshoot
=> UGP-10839_UGP-10847 Independent Scroll, Active Visibility

styles/theme/profile.css, styles/theme/profile.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2128 
Test URLs:
- After: https://exlm-2128--exlm--adobe-experience-league.hlx.live
=> EXLM 2128 - Remove extra borders from profile page

blocks/awards/awards.js, blocks/profile-rail/profile-rail.js
Jira ID: EXLM-2012
Test URLs:
- After: https://exlm-2012--exlm--adobe-experience-league.hlx.live?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/profile/awards.html?ref=exlm-2012
=> EXLM-2012 Always show awards container in UE mode

blocks/profile-welcome/profile-welcome.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2076
Test URLs:
- After: https://feat-exlm-2076-fix--exlm--adobe-experience-league.hlx.page
=> EXLM-2076 Industry name condition fix

blocks/awards/awards.css, blocks/iframe-app/iframe-app.js, blocks/profile-rail/profile-rail.css, scripts/auth/profile.js, styles/theme/profile.css, styles/theme/profile.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2129 
Test URLs:
- After: https://exlm-2129--exlm--adobe-experience-league.hlx.live
=> EXLM 2129 - Profile-rail bug fixes

blocks/awards/awards.css, blocks/profile-rail/profile-rail.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2140 
Test URLs:
- After: https://exlm-2140--exlm--adobe-experience-league.hlx.live
=> EXLM 2140 - Minor CSS fixes

scripts/signup-flow/signup-flow.js
Jira ID: EXLM-2131
Test URLs:
- After: https://exlm-2131--exlm--adobe-experience-league.hlx.page/?martech=off
=> EXLM-2131 - remove top-level await for placeholders causing chrome crashes

scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/data-service/coveo/coveo-exl-pipeline-helpers.js
Jira ID: EXLM-2152
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/publish
- After: https://exlm-2152--exlm--adobe-experience-league.hlx.live/en/publish
=> EXLM-2152 Updates for Playlist cards

blocks/featured-cards/featured-cards.js
Jira ID:
Test URLs:
- After: https://exlm-2152--exlm--adobe-experience-league.hlx.live
=> Featured cards fix when link text isn't authored

scripts/analytics/lib-analytics.js
EXLM-2065: solutionLevel to be part of dataLayer user object to be read on page load.
Jira ID: EXLM-2065
Test URLs:
- After: https://feature-exlm-2065--exlm--adobe-experience-league.hlx.live/
=> EXLM-2065: solutionLevel to be part of dataLayer user object to be read on page load.

blocks/article-metadata-createdby/article-metadata-createdby.css
Jira ID: UGP-10848
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/analytics/analyze/report-builder/data-requests/report-suites/use-excel-to-locate-a-report-suite-id
- After: https://feature-ugp-10848--exlm--adobe-experience-league.hlx.page/en/docs/analytics/analyze/report-builder/data-requests/report-suites/use-excel-to-locate-a-report-suite-id
=> feature/UGP-10848 Fix created by styles

scripts/signup-flow/signup-flow-dialog.js
Jira ID:
Test URLs:
- After: https://feature-exlm-2156--exlm--adobe-experience-league.hlx.live/
=> Signup Flow - Code Cleanup

scripts/editor-support.js
Jira ID:
Test URLs:
- After: https://profile-section--exlm--adobe-experience-league.hlx.live?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/profile.html?ref=profile-section
=> Profile section fix

blocks/product-interests/product-interests.js
Jira ID:
Test URLs:
- After: https://product-interests--exlm--adobe-experience-league.hlx.live?martech=off
=> Fetch Interests URL from getConfig

blocks/header/exl-header.css, blocks/header/exl-header.scss
Jira ID: UGP-1162
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/?martech=off
- After: https://ugp-11162--exlm--adobe-experience-league.hlx.page/?martech=off
Fix search-bar icon
Before:
After:
=> fixed clear button for search bar

blocks/iframe-app/iframe-app.css
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/iframe-app-test?martech=off
- After: https://exlm-2093--exlm--adobe-experience-league.hlx.page/en/iframe-app-test?martech=off
=> EXLM-2093 - Refactor CSS for Iframe app

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js, component-models.json, scripts/dropdown/dropdown.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2167
Test URLs:
- After: https://fix-exlm-2167--exlm--adobe-experience-league.hlx.live?martech=off
=> fix: recommended block content issues EXLM-2167

component-filters.json, scripts/editor-support.js
Jira ID: EXLM-2174
Test URLs:
- After: https://exlm-2174--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2174 Updated allowed blocks for PHP

scripts/browse-card/browse-card-utils.js
Jira ID: EXLM-2169
Test URLs:
- After: https://exlm-2169--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2169 Authorable card solution tag fix

styles/theme/profile.css, styles/theme/profile.scss
Jira ID: EXLM-2175
Test URLs:
- After: https://exlm-2175--exlm--adobe-experience-league.hlx.live
=> EXLM-2175 Profile css

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2167
Test URLs:
- After: https://fix-exlm-2167-2--exlm--adobe-experience-league.hlx.live?martech=off
=> fix: recommended block updates

styles/theme/profile.css, styles/theme/profile.scss
Jira ID: EXLM-2175
Test URLs:
- After: https://exlm-2175--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2175 Profile page CSS updates

blocks/header/header.js
this PR works the changes in Prod into Dev (eventually to stage as well)
https://github.com/adobe-experience-league/exlm-prod/pull/52
=> Header - adding production hotfix to lower env

scripts/scripts.js
Jira ID: EXLM-2117
Test URLs:
- After: https://feat-exlm-2117--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2117 Lang param for community and adobe account

scripts/profile/profile.js
Jira ID: EXLM-2089
Test URLs:
Before: [https://main--exlm--adobe-experience-league.hlx.live?martech=off](https://main--exlm--adobe-experience-league.hlx.live/?martech=off)
After: [https://feat-exlm-2117--exlm--adobe-experience-league.hlx.live?martech=off](https://feat-exlm-2117--exlm--adobe-experience-league.hlx.live/?martech=off)
=> EXLM-2089 Community Profile updates

blocks/profile-rail/profile-rail.js, helix-query.yaml, scripts/scripts.js, scripts/signup-flow/signup-flow-dialog.js
Jira ID: EXLM-2197
Test URLs:
- After: https://exlm-2197--exlm--adobe-experience-league.hlx.live
=> EXLM-2197 Update Profile to Home

blocks/marquee/marquee.js, component-definition.json, component-models.json, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2154
Test URLs:
- After: https://feat-exlm-2154--exlm--adobe-experience-league.hlx.page
=> EXLM-2154 Custom Hexcode added for marquee

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2154
Test URLs:
- After: https://feat-exlm-2154-fix--exlm--adobe-experience-league.hlx.page
=> EXLM-2154 Description change for toggle in UE

blocks/personalized-content-placeholder/personalized-content-placeholder.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2163 
Test URLs:
- After: https://exlm-2188--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/home.html?ref=exlm-2188
=> EXLM 2188 - Show incomplete pages in UE PHP

blocks/profile-welcome/profile-welcome.js, component-definition.json, component-models.json
Jira ID: EXLM-2176
Test URLs:
- After: https://exlm-2176--exlm--adobe-experience-league.hlx.live?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/home/profile-settings.html?ref=exlm-2176
=> EXLM-2176 Profile welcome block updates

component-models.json
Jira ID:
Test URLs:
- After: https://typo-fix--exlm--adobe-experience-league.hlx.live?martech=off
=> Fixed typo for personalized content block

blocks/profile-rail/profile-rail.js
Jira ID: EXLM-2204 
Test URLs:
- After: https://exlm-2204--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2204 Redirect awards to profile settings in case of no awards

blocks/profile-welcome/profile-welcome.js
Jira ID:
Test URLs:
- After: https://exlm-2176--exlm--adobe-experience-league.hlx.live?martech=off
=> Code cleanup - Profile welcome block

blocks/role-and-industry/role-and-industry.js, scripts/profile/profile-interests.js
Jira ID:
Test URLs:
- After: https://feature-exlm-2162--exlm--adobe-experience-league.hlx.live/?martech=off
=> Form validation - Profile and Signup Dialog

styles/theme/profile.css, styles/theme/profile.scss
Jira ID: EXLM-2184
Test URLs:
- After: https://exlm-2184--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2184 Dynamic height for profile section

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2173 
Test URLs:
- After: https://feature-exlm-2173--exlm--adobe-experience-league.hlx.live?martech=off
=> Redirect signed-in users to new personalized home page

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2194
Test URLs:
- After: https://exlm-2194--exlm--adobe-experience-league.hlx.live?martech=off
=> feat: prevent duplicate calls for same content-type exlm-2194

blocks/recommended-content/recommended-content.js, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2135
Test URLs:
- After: https://exlm-ue-2135--exlm--adobe-experience-league.hlx.live/en/teaser?martech=off
=> EXLM 2135 - UE changes in recommended block for target

scripts/profile/profile.js
Jira ID: EXLM-2231
Test URLs:
- After: https://exlm-2231--exlm--adobe-experience-league.hlx.live
=> EXLM-2231 Added pipe symbol in roles for user profile card

blocks/recommended-content/recommended-content.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2135
Test URLs:
- After: https://exlm-2135--exlm--adobe-experience-league.hlx.live/en/teaser
=> EXLM 2135 - Target based recommended content

styles/theme/profile.css, styles/theme/profile.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2232
Test URLs:
- After: https://EXLM-2232-text-issue--exlm--adobe-experience-league.hlx.live?martech=off
=> fix: update the grid dimensions to keep the texts inside the boundary when we have profile background img exlm-2232

blocks/announcement-ribbon/announcement-ribbon.css, blocks/announcement-ribbon/announcement-ribbon.js, component-definition.json, component-filters.json, component-models.json, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2139
Test URLs:
- After: https://feature-exlm-2139--exlm--adobe-experience-league.hlx.live?martech=off
=> Announcement Ribbon Block

blocks/recommended-content/recommended-content.js, component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2135
Test URLs:
- After: https://exlm-2135--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM 2135 - Fix recommended content for UE

component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2135
Test URLs:
- After: https://exlm-2135--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM 2135 - Camel-case select name in recommended content block

blocks/personalized-content-placeholder/personalized-content-placeholder.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2254
Test URLs:
- After: https://bugfix-exlm-2254--exlm--adobe-experience-league.hlx.live
=> Add decorateExternalLinks to home fragment pages

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2135 
Test URLs:
- After: https://exlm-2135--exlm--adobe-experience-league.hlx.live
=> EXLM 2135 - Respect profile context filters in recommended block

blocks/profile-rail/profile-rail.js, scripts/auth/profile.js, scripts/scripts.js
Jira ID: EXLM-2117
Test URLs:
- After: https://exlm-2117--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2117 Added lang param for community API

scripts/signup-flow/signup-flow-handler.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2245
Test URLs:
- After: https://exlm-2245--exlm--adobe-experience-league.hlx.live
=> chore: Incomplete profile condition update EXLM-2245

blocks/recommended-content/recommended-content.js, component-models.json, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2264
Test URLs:
- After: https://exlm-2264--exlm--adobe-experience-league.hlx.live
=> EXLM 2264 - Fix recommended block bug

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://UGP-11843--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> UGP-11843: Chrome workaround

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2243
Test URLs:
- After: https://exlm-2243--exlm--adobe-experience-league.hlx.live
=> feat: content updates EXLM-2243

scripts/scripts.js
Jira ID: EXLM-2246
Test URLs:
- After: https://exlm-2246--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2246 Remove Homepage redirection for Prod

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2249
Test URLs:
- After: https://feat-exlm-2249--exlm--adobe-experience-league.hlx.page
=> EXLM-2249 Recommended content no result text update

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2263 
Test URLs:
- After: https://exlm-2263--exlm--adobe-experience-league.hlx.live
=> Recommended Content Block | Dropdown icon fix

blocks/recommended-content/recommended-content.js, component-models.json, scripts/scripts.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2274 
Test URLs:
- After: https://exlm-2274--exlm--adobe-experience-league.hlx.live
=> EXLM 2274 - Change mapping IDs for recommended block

blocks/columns/columns.css, blocks/columns/columns.js
Jira ID: EXLM-2255
Test URLs:
- After: https://exlm-2255--exlm--adobe-experience-league.hlx.live?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/perspectives/transitioning-to-adobe-analytics.html?ref=exlm-2255
=> EXLM-2255 Columns css fix in UE mode

blocks/announcement-ribbon/announcement-ribbon.css, blocks/announcement-ribbon/announcement-ribbon.js, component-models.json
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2248
Test URLs:
- After: https://feature-exlm-2248--exlm--adobe-experience-league.hlx.live
=> Add image field to the Ribbon Block

blocks/recommended-content/recommended-content.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2208
Test URLs:
- After: https://feat-exlm-2208--exlm--adobe-experience-league.hlx.page
=> EXLM-2208 Heading and description fetch from target

blocks/html-app/html-app.js, component-definition.json, component-filters.json, component-models.json
Jira ID: UGP-11491
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs
- After: https://ugp-11491--exlm--adobe-experience-league.hlx.page/en/doc?martech=off
=> UGP-11491 - add HTML embed for trusted app embed, like Support

scripts/dropdown/dropdown.js
Jira ID:
Test URLs:
- After: https://dropdown-icon-fix--exlm--adobe-experience-league.hlx.live?martech=off
=> Dropdown Icon Fix

scripts/signup-flow/signup-flow-dialog.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2302 
Test URLs:
- After: https://exlm-2302--exlm--adobe-experience-league.hlx.live
=> EXLM 2303 - Add interaction on modal load

scripts/analytics/lib-analytics.js
Jira ID: EXLM-2308
Test URLs:
- After: https://bugfix-exlm-2308--exlm--adobe-experience-league.hlx.live/
-
=> EXLM-2308: add userCorporateName to user.userDetails datalayer.

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2185
Test URLs:
- After: https://exlm-2185--exlm--adobe-experience-league.hlx.live
=> Card level Shimmer + always return 4 cards for a recommendation type EXLM-2185 EXLM-2229

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2281
Test URLs:
- After: https://feat-exlm-2281--exlm--adobe-experience-league.hlx.page
=> EXLM-2281 Added all adobe products option for target

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2229
Test URLs:
- After: https://exlm-2229--exlm--adobe-experience-league.hlx.live
=> feat: remove card when fallback fails to load results as well EXLM-2229

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://profile-lang-fix--exlm--adobe-experience-league.hlx.live?martech=off
=> Call getConfig after setting lang parameter

blocks/header/exl-header.css, blocks/header/exl-header.scss
=> UGP-11911 - Fix header UI Bugs 

blocks/recently-reviewed/recently-reviewed.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2340
Test URLs:
- After: https://exlm-2340--exlm--adobe-experience-league.hlx.live
=> EXLM 2340 - Disable right arrow for recently reviewed block if there is no cards

blocks/profile-welcome/profile-welcome.js
Jira ID:
Test URLs:
- After: https://profile-welcome--exlm--adobe-experience-league.hlx.live?martech=off
=> Community API call for Profile welcome

blocks/recently-reviewed/recently-reviewed.js, scripts/swiper/swiper.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2340 
Test URLs:
- After: https://exlm-2340--exlm--adobe-experience-league.hlx.live
=> EXLM 2340 - Recently viewed block bug fix

component-filters.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2327 
Test URLs:
- After: https://exlm-2327--exlm--adobe-experience-league.hlx.live?martech=off
=> Add "Announcement Ribbon" to deafult section

blocks/header/exl-header.css, blocks/header/exl-header.scss
Jira ID: UPG-11911
Test URLs:
- After: https://ugp-11911--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> UGP-11911 -  better search alignment on mobile

blocks/header/exl-header.css, blocks/header/exl-header.scss, blocks/header/header.js
=> UGP-11911 - fix issues with product grid when signed in

blocks/header/exl-header.css, blocks/header/exl-header.scss
=> UGP-11911 - hide product grid if signed out

blocks/recommended-content/recommended-content.css
Jira ID: EXLM-2315
Test URLs:
- After: https://feature-exlm-2315--exlm--adobe-experience-league.hlx.live/?martech=off
=> Auto adjust card width - Recommended Content

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2229
Test URLs:
- After: https://exlm-2229-dup--exlm--adobe-experience-league.hlx.live
=> fix: render unique cards during the fallback approach EXLM-2229

blocks/bookmarks/bookmarks.js, blocks/personalized-content-placeholder/personalized-content-placeholder.js, blocks/product-experience-level/product-experience-level.js, blocks/product-interests/product-interests.js, blocks/profile-welcome/profile-welcome.js, blocks/role-and-industry/role-and-industry.js, blocks/user-profile-card/user-profile-card.js, scripts/bookmark/bookmark.js, scripts/events.js, scripts/profile/profile-interests.js, scripts/signup-flow/signup-flow-dialog.js, scripts/user-actions/bookmark.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2325
Test URLs:
- After: https://feat-events--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2325: Events refactor to have common instance and separate channels

scripts/signup-flow/signup-flow-dialog.js
Jira ID:
Test URLs:
- After: https://signup-dialog--exlm--adobe-experience-league.hlx.live?martech=off
=> Signup dialog

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2256
Test URLs:
- After: https://homePageRedirection-fix--exlm--adobe-experience-league.hlx.live?martech=off
=> Update Homepage Redirection logic

blocks/toc/toc-filter.css, blocks/toc/toc.css, blocks/toc/toc.js, icons/icon-clear.svg, icons/icon-filter.svg
Jira ID: UGP-10183
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/deploying/restructuring/dynamicmedia-repository-restructuring-in-aem-6-5
- After: https://feature-discoverability--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/deploying/restructuring/dynamicmedia-repository-restructuring-in-aem-6-5
=> feature/UGP-10183 TOC Filter with clear to original state

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js, scripts/target/target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2320 
Test URLs:
- After: https://exlm-2320--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM 2320 - Target Support and Fallback

scripts/analytics/lib-analytics.js, scripts/signup-flow/signup-flow-dialog.js
Jira ID: EXLM-2309
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs
- After: https://feature-exlm-2309--exlm--adobe-experience-league.hlx.live/en/docs
=> EXLM-2309: Sign up modal buttons AA events.

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js, scripts/data-service/coveo/coveo-exl-pipeline-helpers.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2316
Test URLs:
- After: https://exlm-2316--exlm--adobe-experience-league.hlx.live
=> feat: Filter tab display depending on the number of interests EXLM-2316

blocks/announcement-ribbon/announcement-ribbon.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2333
Test URLs:
- After: https://exlm-2333-ribbonFix--exlm--adobe-experience-league.hlx.page
=> EXLM-2333 Announcement ribbon icon name change

blocks/recommended-content/recommended-content.js, scripts/browse-card/browse-card.js
Jira ID: EXLM-2343
Test URLs:
- After: https://exlm-2343--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2343 PHP Analytics

blocks/recommended-content/recommended-content.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2316
Test URLs:
- After: https://fix-exlm-2316--exlm--adobe-experience-league.hlx.live
=> fix: correct css to show shimmers while waiting EXLM-2316

blocks/personalized-content-placeholder/personalized-content-placeholder.js, scripts/scripts.js, styles/theme/profile.css, styles/theme/profile.scss
Jira ID:
Test URLs:
- After: https://exlm-2363-fix--exlm--adobe-experience-league.hlx.live?martech=off
=> UE mode fix for PHP

blocks/personalized-content-placeholder/personalized-content-placeholder.js, blocks/profile-welcome/profile-welcome.css, blocks/profile-welcome/profile-welcome.js, blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2364
Test URLs:
- After: https://EXLM-2364--exlm--adobe-experience-league.hlx.live
=> feat: load profile-welcome block asynchronously without blocking

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2390 
Test URLs:
- After: https://exlm-2390--exlm--adobe-experience-league.hlx.live
=> EXLM 2390 - Fix Target filters and remove empty filters

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2405
Test URLs:
- After: https://exlm-2405--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM 2405 - Hide target block if no data

blocks/personalized-content-placeholder/personalized-content-placeholder.css, blocks/personalized-content-placeholder/personalized-content-placeholder.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2370
Test URLs:
- After: https://exlm-2370--exlm--adobe-experience-league.hlx.live
=> fix: address gap issue for PHP block exlm-2370

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2316
Test URLs:
- After: https://feat-exlm-2316--exlm--adobe-experience-league.hlx.live
=> feat: remove all my products tab & consider the duplicate card logic for all adobe tab exlm-2316

styles/theme/profile.css, styles/theme/profile.scss
Jira ID:
Test URLs:
- After: https://browse-cards--exlm--adobe-experience-league.hlx.live?martech=off
=> Browse cards tag css fix for Profile pages

blocks/profile-welcome/profile-welcome.js
Jira ID:
Test URLs:
- After: https://fix-welcome-block--exlm--adobe-experience-league.hlx.live?martech=off
=> Profile Welcome Block - Icon Fix

blocks/product-interests/product-interests.js, scripts/auth/profile.js, scripts/profile/profile-interests.js
…
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2407
Test URLs:
- After: https://fix-int-sol-changes--exlm--adobe-experience-league.hlx.live
=> fix: initial changes for solution and interest consistency from signup modal updates

blocks/toc/toc.css, blocks/toc/toc.js
Jira ID: UGP-10183
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/deploying/restructuring/dynamicmedia-repository-restructuring-in-aem-6-5
- After: https://feature-discoverability--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/deploying/restructuring/dynamicmedia-repository-restructuring-in-aem-6-5
=> feature/UGP-10183 Fix css and javascript bugs

blocks/personalized-content-placeholder/personalized-content-placeholder.css, blocks/personalized-content-placeholder/personalized-content-placeholder.js, styles/theme/profile.css, styles/theme/profile.scss
Jira ID:
Test URLs:
- After: https://exlm-2415--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2415 Personalized content block in UE mode

blocks/recently-reviewed/recently-reviewed.js
Jira ID: EXLM-2417
Test URLs:
- After: https://exlm-2417--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2417 Hide empty section for recently reviewed block

blocks/recently-reviewed/recently-reviewed.js
Jira ID:
Test URLs:
- After: https://recently-reviewed-fix--exlm--adobe-experience-league.hlx.live
=> Fix Recently reviewed block 

scripts/analytics/lib-analytics.js
Jira ID: EXLM-2430
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
- After: https://exlm-2430--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> EXLM-2430 Fixed dataLayer value for browse pages

scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://bugfix-tooltip-icon--exlm--adobe-experience-league.hlx.live?martech=off
=> Decorate Tooltip icon in Browse cards

scripts/scripts.js
Jira ID: EXLM-2426
Test URLs:
- After: https://exlm-2426--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2426 Enable A/B Testing for the PHP vs Current homepage

scripts/profile/profile-interests.js
…
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2407
Test URLs:
- After: https://exlm-2407-2--exlm--adobe-experience-league.hlx.live
=> chore: exp level value mapping update EXLM-2407

scripts/analytics/lib-analytics.js, scripts/signup-flow/signup-flow-dialog.js
Jira ID: EXLM-2453: Push signup-dialog event when sign up modal is shown
Test URLs:
- After: https://bugfix-exlm-2453--exlm--adobe-experience-league.hlx.live/?martech=off
=> EXLM-2453: Push signup-dialog event when sign up modal is shown

scripts/browse-card/browse-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2446
Test URLs:
- After: https://exlm-2446--exlm--adobe-experience-league.hlx.live?martech=off
=> Wrap browse card banner text 

blocks/browse-filters/browse-filters.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2444
Test URLs:
- After: https://feat-exlm-2444--exlm--adobe-experience-league.hlx.page
=> EXLM-2444 Search result dropdown CSS fixes

blocks/article-marquee/article-marquee.js
Jira ID: EXLM-2440
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives/unlocking-analytical-insight-harnessing-the-power-of-annotation?martech=off
- After: https://exlm-2440--exlm--adobe-experience-league.hlx.live/en/perspectives/unlocking-analytical-insight-harnessing-the-power-of-annotation?martech=off
=> EXLM-2440 Date localization for Perspectives

blocks/qualtrics/qualtrics.js, component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-2439 
Test URLs:
- After: https://exlm-2439--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM-2439 Qualtrics block

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js, scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2458
Test URLs:
- After: https://exlm-2458--exlm--adobe-experience-league.hlx.live
=> EXLM 2458 - Target data rendering issue fix

blocks/recommended-content/recommended-content.js
…
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2469
Test URLs:
- After: https://exlm-2469--exlm--adobe-experience-league.hlx.live
=> fix: v2 calls not going when cookies are disabled EXLM-2469

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://interests--exlm--adobe-experience-league.hlx.live?martech=off
=> Updated Interests URL

blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card-tooltip.js, scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://tooltip-bugfix--exlm--adobe-experience-league.hlx.live?martech=off
=> Call decorateIcons in tooltip.js

blocks/recently-reviewed/recently-reviewed.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2387
Test URLs:
- After: https://exlm-fix-rr--exlm--adobe-experience-league.hlx.live?martech=off
=> EXLM 2387- Recently reviewed bug fix

README.md, fstab.yaml, helix-sitemap.yaml, robots.txt, sitemap-index.xml
Reverting origin changes done as part of 
https://github.com/adobe-experience-league/exlm/commit/804a9aab6914a144b5ac375e76b8185e219280f1#diff-6da918dd5150a5af3884a88d23aa89b44cc2a1e48a2c0daa6bbbbd6ab4d00f17
Test URLs:
- After: https://revert-origin-changes--exlm--adobe-experience-league.hlx.live?martech=off
=> Revert to Dev origin

scripts/profile/profile-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2471
Test URLs:
- After: https://fix-signup-dropdown--exlm--adobe-experience-league.hlx.live?martech=off
=> fix: set dropdownId dynamically to address the issue of dropdown not working in signup modal

blocks/recommended-content/recommended-content.js, scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2479
Test URLs:
- After: https://exlm-2479--exlm--adobe-experience-league.hlx.live
=> EXLM 2479 - Recommended content bug fix

scripts/adobe-target/adobe-target.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2479
Test URLs:
- After: https://exlm-2479--exlm--adobe-experience-league.hlx.live
=> EXLM 2479 - Remove Empty sections for target

blocks/profile-welcome/profile-welcome.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2484 
Test URLs:
- After: https://exlm-2484--exlm--adobe-experience-league.hlx.live?martech=off
=> Fix padding in mini profile card

blocks/toc/toc.css, blocks/toc/toc.js
Jira ID: UGP-12112
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-platform/release-notes/2020/january-2020
- After: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-platform/release-notes/2020/january-2020
=> feature/UGP-12112 Refactor ensureElementInView to meet requirements

blocks/header/header.js
Jira ID:
Test URLs:
- After: https://ugp-11893--exlm--adobe-experience-league.hlx.page/en/docs
=> Use Nav link origin for relative links

blocks/toc/toc.css
Jira ID: UGP-12112
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/sites/administering/operations/operations-audit-log
- After: https://feature-ugp-12112--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/sites/administering/operations/operations-audit-log
=> UGP-12112 Safari scroll bugfix

blocks/article-marquee/article-marquee.js, blocks/author-bio/author-bio.js, blocks/author-summary/author-summary.js, blocks/browse-filters/browse-filters.js, blocks/featured-authors/featured-authors.js, blocks/featured-cards/featured-cards.js, blocks/featured-content/featured-content.js, blocks/header/header-utils.js, blocks/mini-toc/mini-toc.js, blocks/personalized-content-placeholder/personalized-content-placeholder.js, blocks/tabs/tabs.js, blocks/toc/toc.js, scripts/articles/articles.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/data-service/coveo/coveo-exl-pipeline-helpers.js, scripts/prev-next-btn.js, scripts/scripts.js, scripts/utils/author-utils.js, scripts/utils/path-utils.js, scripts/utils/ue-utils.js, styles/styles.css, styles/styles.scss
Test URLs:
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page?martech=off
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page/en/docs?martech=off
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page/en/browse?martech=off
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://clean-scripts--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service?martech=off
After: …
=> Cleanup scripts.js to remove code that needn't be there.

.github/pull_request_template.md, .github/workflows/update-pr-description.yaml
Please alos provide test paths followign the template below.
Jira ID:
> NOTE: `- After: https://pull-template-action--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://pull-template-action--exlm--adobe-experience-league.aem.page?martech=off
- After: https://pull-template-action--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://pull-template-action--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://pull-template-action--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> Update PR template automatically

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2475
> NOTE: `- After: https://fix-placeholder-block--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://fix-placeholder-block--exlm--adobe-experience-league.aem.page?martech=off
- After: https://fix-placeholder-block--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> EXLM-2475 remove only block section if empty

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2487
> NOTE: `- After: https://exlm-2487--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
Before: https://main--exlm--adobe-experience-league.aem.page?martech=off
After: https://exlm-2487--exlm--adobe-experience-league.aem.page?martech=off
=> Add Shimmer to header, description and tabs in recommended content block

component-definition.json
Jira ID: EXLM-2477
> NOTE: `- After: https://exlm-2477--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2477--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> EXLM-2477 Updated Blocks in content tree to be in alphabetical order

blocks/authorable-card/authorable-card.js, blocks/product-experience-level/product-experience-level.js, scripts/profile/profile-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2491 
> NOTE: `- After: https://fix-dropdown-id--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
-After: - After: https://fix-dropdown-id--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> Update Dropdown ID in Product Experience Level Block  & duplicate icon fix

blocks/recommended-courses/recommended-courses.js
Jira ID:
> NOTE: `- After: https://icon-issue--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://icon-issue--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> Recommended courses - Icon issue

blocks/recommended-content/recommended-content.js
Jira ID: EXLM-2497
> NOTE: `- After: https://exlm-2497--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2497--exlm--adobe-experience-league.aem.live/en/docs?martech=off
https://exlm-2497--exlm--adobe-experience-league.aem.live?martech=off
=> EXLM-2497 Recommended content - added data attribute for coveo blocks

blocks/browse-filters/browse-filter-utils.js, scripts/signup-flow/signup-flow-dialog.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2500
> NOTE: `- After: https://exlm-2500--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2500--exlm--adobe-experience-league.aem.page/en/browse?martech=off
=> Fix translation issues in Signup and Browse pages

blocks/announcement-ribbon/announcement-ribbon.css, blocks/announcement-ribbon/announcement-ribbon.js, component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2476
> NOTE: `- After: https://feat-exlm-2476--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2476--exlm--adobe-experience-league.aem.page?martech=off
=> EXLM-2476 Background color and theme added

scripts/placeholders/list-placeholder.css
Jira ID:
> NOTE: `- After: https://css-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://css-fix--exlm--adobe-experience-league.aem.live?martech=off
=> Removed duplicate css property

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2515
> NOTE: `- After: https://exlm-2515--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2515--exlm--adobe-experience-league.aem.page?martech=off
=> Fix - No Results Placeholder width in Recommended Content Block

scripts/scripts.js
Jira ID:
> NOTE: `- After: https://exlm-2537--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2537--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> EXLM-2537 Target PHP redirection - flicker issue

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse//EXLM-2515
Test URLs:
- After: https://exlm-2515--exlm--adobe-experience-league.hlx.live
=> fix: set empty context values for all products tab EXLM-2515

blocks/recommended-content/recommended-content.js
Jira ID:
> NOTE: `- After: https://recommended-content--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://recommended-content--exlm--adobe-experience-league.aem.live?martech=off
=> Recommended block updates

blocks/profile-welcome/profile-welcome.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2553
> NOTE: `- After: https://exlm-2553--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2553--exlm--adobe-experience-league.aem.page?martech=off
=> Fix Profile Welcome Block UE issue

blocks/announcement-ribbon/announcement-ribbon.css, blocks/announcement-ribbon/announcement-ribbon.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2562
> NOTE: `- After: https://feat-exlm-2562--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2562--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2562 Close icon button fix

scripts/qualtrics.js, scripts/scripts.js
Jira ID: UGP-12243
> NOTE: `- After: https://qualtrics-lang-map--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://qualtrics-lang-map--exlm--adobe-experience-league.aem.page
- After: https://qualtrics-lang-map--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://qualtrics-lang-map--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://qualtrics-lang-map--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> UGP-12243: Added Qualtrics Lang Codes

blocks/mini-toc/mini-toc.js
Jira ID: EXLM-2564
> NOTE: `- After: https://mini-toc-bug--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/docs/target/using/release-notes/target-documentation?martech=off
- After: https://mini-toc-bug--exlm--adobe-experience-league.aem.live/en/docs/target/using/release-notes/target-documentation?martech=off
=> EXLM-2564 Mini TOC issue

blocks/mini-toc/mini-toc.js
Jira ID: EXLM-2564
> NOTE: `- After: https://mini-toc-bug--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
Before: https://main--exlm--adobe-experience-league.aem.live/en/docs/target/using/release-notes/target-documentation?martech=off
After: https://mini-toc-bug--exlm--adobe-experience-league.aem.live/en/docs/target/using/release-notes/target-documentation?martech=off
=> EXLM-2564 Mini TOC issues

blocks/recently-reviewed/recently-reviewed.css, blocks/recommended-content/recommended-content.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2557
> NOTE: `- After: https://exlm-2557--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After:  https://exlm-2557--exlm--adobe-experience-league.aem.live?martech=off
=> EXLM 2557: Styling of link when received from Target

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2568
Test URLs:
- After: https://exlm-2568--exlm--adobe-experience-league.hlx.live
=> fix: clear off the no results container forcefully EXLM-2568

blocks/tabbed-cards/tabbed-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2470
> NOTE: `- After: https://exlm-2423-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs: 
- After: https://exlm-2423-fix--exlm--adobe-experience-league.aem.page
- After: https://exlm-2423-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2423-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2423-fix--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> Fix tabbed-cards shimmer issue

scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2470
> NOTE: `- After: https://feat-exlm-2521--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2521--exlm--adobe-experience-league.aem.page/?martech=off
=> Removing laptop container for image error

paths.json, paths.yaml
Jira ID:
> NOTE: `- After: https://taxonomy-debug--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://taxonomy-debug--exlm--adobe-experience-league.aem.live?martech=off
=> Taxonomy debug

blocks/header/header.js, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2583
> NOTE: `- After: https://feat-exlm-2583--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2583--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2583 Hyperlink fix for description

blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js, component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2583
> NOTE: `- After: https://feat-exlm-2583-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2583-fix--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2583 Recommended content heading type fix

blocks/target-insertion/target-insertion.js, blocks/topic-results/pagination/pagination.js, scripts/prev-next-btn.js, scripts/scripts.js, scripts/tutorial-widgets/tutorial-widgets.js
Jira ID: UGP-12242
> NOTE: `- After: https://add-last-container--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://add-last-container--exlm--adobe-experience-league.aem.page
- After: https://add-last-container--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://add-last-container--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://add-last-container--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Add last docs section for blocks and other functionality that require it

blocks/embed/embed.css, blocks/embed/embed.js, blocks/header/header.js
Jira ID:
> NOTE: `- After: https://UGP-12270--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/docs/analytics-learn/tutorials/analysis-workspace/attribution-iq/algorithmic-model-in-attribution-iq?martech=off
- After: https://UGP-12270--exlm--adobe-experience-league.aem.page/en/docs/analytics-learn/tutorials/analysis-workspace/attribution-iq/algorithmic-model-in-attribution-iq?martech=off
- After: https://UGP-12270--exlm--adobe-experience-league.aem.page/en/docs/analytics-learn/tutorials/analysis-wor …
=> handle MPC videos with placeholder images

scripts/browse-card/browse-cards-block.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2586
> NOTE: `- After: https://feat-exlm-2586--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2586--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2586 Bottom border overlap fix for browse cards

blocks/tabbed-cards/tabbed-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2587
> NOTE: `- After: https://exlm-2587--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2587--exlm--adobe-experience-league.aem.page
- After: https://exlm-2587--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2587--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2587--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM - 2587 Tabbed card issue fix

scripts/browse-card/browse-card.css
Jira ID: 
> NOTE: `- After: https://browseCard-borderFix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://browseCard-borderFix--exlm--adobe-experience-league.aem.page?martech=off
=> Browse cards border radius fix

blocks/recommendation-marquee/recommendation-marquee.css, blocks/recommendation-marquee/recommendation-marquee.js, scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2447
Test URLs:
- After: https://exlm-2447--exlm--adobe-experience-league.hlx.live
=> feat: recommended-marquee block changes EXLM-2447

scripts/coveo-analytics.js, scripts/data-service/coveo/coveo-token-service.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2582
> NOTE: `- After: https://exlm-2582--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2582--exlm--adobe-experience-league.aem.page?martech=off
=> Refresh Coveo Token based on Expiration Time

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2606
> NOTE: `- After: https://exlm-2608--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2608--exlm--adobe-experience-league.aem.page
- After: https://exlm-2608--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2608--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2608--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM - 2608 - Recommended content block card issue fix

blocks/recommendation-marquee/recommendation-marquee.css, scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2435
Test URLs:
- After: https://exlm-2435--exlm--adobe-experience-league.hlx.live
=> feat: recommended marquee target refactor exlm-2435

blocks/detailed-teaser/detailed-teaser.css, blocks/marquee/marquee.css, blocks/sign-up/sign-up.css, blocks/teaser/teaser.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2613 
> NOTE: `- After: https://exlm-2613--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2613--exlm--adobe-experience-league.aem.page?martech=off
=> Update Marquee, Teaser, Signup block styles to support PHP

scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2577
> NOTE: `- After: https://feat-exlm-2577--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2577--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2577 Corrupted symbols title fix for browse cards

blocks/article-marquee/article-marquee.js, blocks/browse-filters/browse-filters.js, blocks/marquee/marquee.js, scripts/delayed.js, styles/theme/article-landing.css
Jira ID: EXLM-2610
> NOTE: `- After: https://performance-2610--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://performance-2610--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
=> Performance 2610

scripts/adobe-target/adobe-target.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2569 
> NOTE: `- After: https://exlm-2569--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2569--exlm--adobe-experience-league.aem.page
=> EXLM 2569 - Add event listener for target error

blocks/browse-filters/browse-filters.js, blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2636
> NOTE: `https://exlm-2636--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2636--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2636--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2636--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2636--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> fix: first card css issue EXLM-2636

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.js, blocks/recommended-courses/recommended-courses.js, component-definition.json, scripts/browse-card/browse-cards-block.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2608
> NOTE: `- After: https://feat-exlm-2608--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2608--exlm--adobe-experience-league.aem.page/?martech=off
=> EXLM-2608 Heading type authoring fixes for cards

blocks/recommendation-marquee/recommendation-marquee.css, scripts/responsive-pill-list/responsive-pill-list.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2656
> NOTE: `- After: https://EXLM-2656--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2656--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2656--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2656--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2656--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> fix: recommendation marquee css issues exlm-2656

blocks/recommendation-marquee/recommendation-marquee.css, scripts/browse-card/browse-card.css, scripts/swiper/swiper.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2594 
> NOTE: `- After: https://exlm-2594--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2594--exlm--adobe-experience-league.aem.page
- After: https://exlm-2594--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2594--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2594--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2594 - Browse card thumbnail animation

blocks/mini-toc/mini-toc.js
Jira ID:
> NOTE: `- After: https://fix-minitoc--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://fix-minitoc--exlm--adobe-experience-league.aem.page?martech=off
- After: https://fix-minitoc--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://fix-minitoc--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://fix-minitoc--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
=> Fix highlighting in Mini-Toc

scripts/browse-card/browse-cards-target-data-adapter.js
Jira ID: EXLM-2665
> NOTE: `- After: https://exlm-2665--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2665--exlm--adobe-experience-league.aem.live
- After: https://exlm-2665--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2665--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2665--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: …
=> EXLM-2665 Perspective Target response

blocks/browse-filters/browse-filters.js
Jira ID: EXLM-2610
> NOTE: `- After: https://browse-filter-perf-revert--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://browse-filter-perf-revert--exlm--adobe-experience-league.aem.page
- After: https://browse-filter-perf-revert--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://browse-filter-perf-revert--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://browse-filter-perf-revert--exlm--adobe-experience-league.aem.page/en/docs/analyt …
=> revert: browse-filters perf updates

scripts/adobe-target/adobe-target.js
Jira ID:
> NOTE: `- After: https://hotfix-target--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://hotfix-target--exlm--adobe-experience-league.aem.page
- After: https://hotfix-target--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://hotfix-target--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://hotfix-target--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> add featureflag to recommendationMarquee

blocks/recommended-content/recommended-content.js
Jira ID:
> NOTE: `- After: https://hotfix-seeMore--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://hotfix-seeMore--exlm--adobe-experience-league.aem.page
- After: https://hotfix-seeMore--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://hotfix-seeMore--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://hotfix-seeMore--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> feature flag see more

scripts/auth/profile.js, scripts/signup-flow/signup-flow-handler.js
Jira ID: EXLM-2662
> NOTE: `- After: https://exlm-2662--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2662--exlm--adobe-experience-league.aem.live
- After: https://exlm-2662--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2662--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2662--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: …
=> EXLM-2662 Clean up post signin stream code

blocks/header/exl-header.css
Jira ID:
Test URLs:
- After: https://header-search-too-short--exlm--adobe-experience-league.aem.page?martech=off
- After: https://header-search-too-short--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> increase search max-width so text does not cut off

blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js, scripts/coveo-headless/index.js, scripts/search/search-utils.js
Jira ID: EXLM-2675
> NOTE: `- After: https://perf-fix-browse--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://perf-fix-browse--exlm--adobe-experience-league.aem.page
- After: https://perf-fix-browse--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://perf-fix-browse--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://perf-fix-browse--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Perspective - Browse Filter - Coveo Fixes

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID:
> NOTE: `- After: https://marquee-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://marquee-fix--exlm--adobe-experience-league.aem.page
- After: https://marquee-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://marquee-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://marquee-fix--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Recommended Marquee tooltip issue fix

scripts/auth/profile.js
Jira ID: EXLM-2662
> NOTE: `- After: https://exlm-2662--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2662--exlm--adobe-experience-league.aem.page
- After: https://exlm-2662--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2662--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2662--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2662 Signup modal code clean up

blocks/recommendation-marquee/recommendation-marquee.css, blocks/recommendation-marquee/recommendation-marquee.js, component-definition.json, component-models.json
Jira ID: EXLM-2663
> NOTE: `- After: https://exlm-2663--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2663--exlm--adobe-experience-league.aem.page
- After: https://exlm-2663--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2663--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2663--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2663 Recommendation Marquee Updates

blocks/browse-filters/browse-filters.js
…
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2705
> NOTE: `- After: https://EXLM-2705--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2705--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2705--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2705--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2705--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> fix: scroll the page to focus the filter section after coveo search EXLM-2705

404.html, scripts/delayed.js, scripts/lib-franklin.js, scripts/scripts.js
https://rum-v2--exlm--adobe-experience-league.aem.page/?rum=on
=> chore: update rum enhancer to v2

scripts/auth/profile.js, scripts/scripts.js, scripts/signup-flow/signup-flow-dialog.js, scripts/signup-flow/signup-flow-handler.js
Jira ID: EXLM-2741 
> NOTE: `- After: https://exlm-2741--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs: 
- After: https://exlm-2741--exlm--adobe-experience-league.aem.page
- After: https://exlm-2741--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2741--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2741--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2741 Updated signup modal rendering logic

scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-adls-adaptor.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2686
> NOTE: `- After: https://feat-exlm-2686--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2686--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2686--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2686--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2686--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2686 Date and time addition for ADLS cards

blocks/article-marquee/article-marquee.js
Jira ID: EXLM-2749
> NOTE: `- After: https://exlm-2749--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2749--exlm--adobe-experience-league.aem.page
- After: https://exlm-2749--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2749--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2749--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2749 Article marquee bg color fix

blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card-utils.js, scripts/browse-card/browse-cards-delegate.js, scripts/utils/date-utils.js
Jira ID:
> NOTE: `- After: https://exlm-2664--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2664--exlm--adobe-experience-league.aem.page
- After: https://exlm-2664--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2664--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2664--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2664--exlm--adobe-experience-league.aem.page/en/docs …
=> EXLM 2664 - Fetch community post within one year

styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2683 
> NOTE: `- After: https://exlm-2683--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2683--exlm--adobe-experience-league.aem.page?martech=off
- After: https://exlm-2683--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2683--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2683--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Reduce the max width of the first block inside the placeholder section

scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2721
> NOTE: `- After: https://exlm-2721--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2721--exlm--adobe-experience-league.aem.page
- After: https://exlm-2721--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2721--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2721--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2721 - Filter recommendation marquee data to remove duplicates

blocks/recently-reviewed/recently-reviewed.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2776 
> NOTE: `- After: https://exlm-2776--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2776--exlm--adobe-experience-league.aem.page
- After: https://exlm-2776--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2776--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2776--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXL 2776 - Recently reviewed See more bug fix

blocks/recently-reviewed/recently-reviewed.css, blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2778
> NOTE: `- After: https://feat-exlm-2778--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2778--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2778--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2778--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2778--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2778 fix for animation fade out

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2778
> NOTE: `- After: https://feat-exlm-2778-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2778-fix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2778-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2778-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2778-fix--exlm--adobe-experience-league.aem.page/en/docs/analyt …
=> EXLM-2778 Fix to scroll it to block

scripts/browse-card/browse-cards-delegate.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2775
> NOTE: `- After: https://exlm-2775--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2775--exlm--adobe-experience-league.aem.page
- After: https://exlm-2775--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2775--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2775--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2775 - Remove role facet for communities

blocks/playlist/playlist-action-menu.css, blocks/playlist/playlist-action-menu.js, blocks/playlist/playlist.css
…oolbar from the playlist
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2701, https://jira.corp.adobe.com/browse/EXLM-2702 
> NOTE: `- After: https://exlm-2701--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2701--exlm--adobe-experience-league.aem.page
- After: https://exlm-2701--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2701--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: …
=> Add Tooltip to playlist user action buttons 

scripts/pagination/pagination.js
Jira ID:
> NOTE: `- After: https://feat-exlm-2722--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2722--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2722--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2722--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2722--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2722 Pagination locale fix

scripts/lib-franklin.js
Jira ID:
> NOTE: `- After: https://sample-rum--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://sample-rum--exlm--adobe-experience-league.aem.page
- After: https://sample-rum--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://sample-rum--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://sample-rum--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Added export for sampleRUM method

blocks/announcement-ribbon/announcement-ribbon.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2781 
> NOTE: `- After: https://bugfix-2781--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://bugfix-2781--exlm--adobe-experience-league.aem.page
- After: https://bugfix-2781--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-2781--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-2781--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Announcement banner bug fix

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2793 
> NOTE: `- After: https://exlm-2793--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2793--exlm--adobe-experience-league.aem.page
- After: https://exlm-2793--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2793--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2793--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2793 - Fix Recommendation marquee description getting cut off 

blocks/recently-reviewed/recently-reviewed.js, blocks/recommended-content/recommended-content.js, scripts/browse-card/browse-card.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2794 
> NOTE: `- After: https://exlm-2794--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2794--exlm--adobe-experience-league.aem.page
- After: https://exlm-2794--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2794--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2794--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2794 - Fix thumbnail for all content types

blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2731 
> NOTE: `- After: https://exlm-2731--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2731--exlm--adobe-experience-league.aem.page
- After: https://exlm-2731--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2731--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2731--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Browse Topics | Support localized topics name

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2807
> NOTE: `- After: https://feat-exlm-2807-cssfix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2807-cssfix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2807-cssfix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2807-cssfix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2807-cssfix--exlm--adobe-experience-league.aem.page …
=> EXLM-2807 Hiding see more for smaller screens

blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2835
> NOTE: `- After: https://feat-exlm-2835--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2835--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2835--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2835--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2835--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2835 Number of rows fix for recommendation marquee

blocks/icon-block/icon-block.js, component-models.json
Jira ID: EXLM-2811
> NOTE: `- After: https://exlm-2811--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2811--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-2811--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2811--exlm--adobe-experience-league.aem.live/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-2811--exlm--adobe-experience-league.aem.live/?signup-wizard=on
- After: …
=> EXLM-2811 Icon Card updates

blocks/recommendation-marquee/recommendation-marquee.js, styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2829
> NOTE: `- After: https://feat-exlm-2829--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2829--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2829--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2829--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2829--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2829 Recommendation marquee css and target heading changes

helix-query.yaml
Jira ID: EXLM-2826
> NOTE: `- After: https://exlm-2826--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2826--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-2826--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2826--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: https://exlm-2826--exlm--adobe-experience-league.aem.live/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off …
=> EXLM-2826 Exclude JSON files from sitemap

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2827 , https://jira.corp.adobe.com/browse/EXLM-2817 
> NOTE: `- After: https://exlm-2817--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2817--exlm--adobe-experience-league.aem.page
- After: https://exlm-2817--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2817--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2817--exlm--adobe-experience-league.aem.page/en/docs/ana …
=> Recommended Marquee | New card design update

blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2815
> NOTE: `- After: https://feat-exlm-2815-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2815-fix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2815-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2815-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2815-fix--exlm--adobe-experience-league.aem.page/en/docs/analyt …
=> EXLM-2815 See more button fix for target

blocks/recommendation-marquee/recommendation-marquee.css, blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2839
> NOTE: `- After: https://feat-exlm-2839--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2839--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2839--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2839--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2839--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2839 See more button fix for smaller screens

blocks/recommendation-marquee/recommendation-marquee.css, scripts/browse-card/browse-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2855 
> NOTE: `- After: https://exlm-2855--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2855--exlm--adobe-experience-league.aem.page
- After: https://exlm-2855--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2855--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2855--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Recommendation Marquee | Play icon and tooltip fix

blocks/profile-rail/profile-rail.js
Jira ID:
> NOTE: `- After: https://profile-rail-issue--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://profile-rail-issue--exlm--adobe-experience-league.aem.page
- After: https://profile-rail-issue--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://profile-rail-issue--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://profile-rail-issue--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Profile rail console error

scripts/browse-card/browse-card.css
Jira ID: EXLM-2867
> NOTE: `- After: https://exlm-2867--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2867--exlm--adobe-experience-league.aem.page
- After: https://exlm-2867--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2867--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2867--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2867 Perspective content type color update

component-definition.json, component-filters.json, component-models.json, scripts/browse-card/browse-cards-live-events-adaptor.js
Jira ID: EXLM-2812
> NOTE: `- After: https://exlm-2812-ue--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2812-ue--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-2812-ue--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-2812-ue--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: https://exlm-2812-ue--exlm--adobe-experience-league.aem.live/en/docs/analytics/analyze/admin-overview/analytics-overvi …
=> EXLM-2812 Upcoming Events block

blocks/personalized-content-placeholder/personalized-content-placeholder.js, styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2866 
> NOTE: `- After: https://exlm-2866--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2866--exlm--adobe-experience-league.aem.page
- After: https://exlm-2866--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2866--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2866--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2866 - Remove graphics from PHP

scripts/dropdown/dropdown.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2863 
> NOTE: `- After: https://exlm-2863--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2863--exlm--adobe-experience-league.aem.page
- After: https://exlm-2863--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2863--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2863--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2863 - Add multiselect dropdown variant

scripts/browse-card/browse-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2877 
> NOTE: `- After: https://exlm-2877--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2877--exlm--adobe-experience-league.aem.page
- After: https://exlm-2877--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2877--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2877--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2877 - Remove play button on hover in card thumbnail

blocks/recommended-content/recommended-content.js, scripts/browse-card/browse-card-tooltip.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2857 
> NOTE: `- After: https://exlm-2857--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2857--exlm--adobe-experience-league.aem.page
- After: https://exlm-2857--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2857--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2857--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Browse cards | Fix tooltip in mobile view

blocks/recommendation-marquee/recommendation-marquee.css, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2868 
> NOTE: `- After: https://exlm-2868-css--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2868-css--exlm--adobe-experience-league.aem.page
- After: https://exlm-2868-css--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2868-css--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2868-css--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM 2868 - Remove inline styles from browse-card

blocks/recently-reviewed/recently-reviewed.css, blocks/recently-reviewed/recently-reviewed.js, blocks/recommendation-marquee/recommendation-marquee.css, blocks/recommended-content/recommended-content.css
Jira ID:
> NOTE: `- After: https://bugfix-2857--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://bugfix-2857--exlm--adobe-experience-league.aem.page
- After: https://bugfix-2857--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-2857--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-2857--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Tooltip | Show tooltip in IOS devices

scripts/browse-card/browse-card.css
Jira ID: EXLM-2884
> NOTE: `- After: https://exlm-2884--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2884--exlm--adobe-experience-league.aem.page
- After: https://exlm-2884--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2884--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2884--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2884 Certification color update

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2897 
> NOTE: `- After: https://exlm-2897--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2897--exlm--adobe-experience-league.aem.page
- After: https://exlm-2897--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2897--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2897--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2897 - Update Recommendation Marquee rounded corners

scripts/dropdown/dropdown.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2906 
> NOTE: `- After: https://exlm-2906--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2906 - Fix Play button overlay on dropdown

blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2894
> NOTE: `- After: https://feat-exlm-2894--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2894--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2894--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2894--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2894--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2894 See more button fix for target rec marquee

scripts/scripts.js
Jira ID: EXLM-2901
> NOTE: `- After: https://exlm-2901--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2901--exlm--adobe-experience-league.aem.page
- After: https://exlm-2901--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2901--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2901--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2901 Current homepage to PHP redirection

blocks/detailed-teaser/detailed-teaser.css, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2907
> NOTE: `- After: https://EXLM-2907--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2907--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2907--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2907--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2907--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> fix: scrollbar related issues EXLM-2907

scripts/qualtrics.js
Jira ID: EXLM-2915
> NOTE: `- After: https://exlm-2915--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2915--exlm--adobe-experience-league.aem.page
- After: https://exlm-2915--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2915--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2915--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2915 Update window.qualtricsLang when on PT-BR pages

blocks/recommendation-marquee/recommendation-marquee.css, scripts/browse-card/browse-card.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2893
> NOTE: `- After: https://exlm-2893--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2893--exlm--adobe-experience-league.aem.page
- After: https://exlm-2893--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2893--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2893--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Recommendation Marquee | Fix flashing of Adobe logo while loading thumbnail

blocks/upcoming-events/upcoming-events.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2812
> NOTE: `- After: https://exlm-2812--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2812 - Fix Remove tags when unselecting from dropdown

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js, scripts/dropdown/dropdown.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2899
> NOTE: `- After: https://exlm-2906--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2906--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2896 - Remove see more if less number of cards for coveo

blocks/upcoming-event/upcoming-event.css, blocks/upcoming-event/upcoming-event.js, component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-2812
> NOTE: `- After: https://exlm-2812--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2812--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2812 Renamed Upcoming Events to Upcoming Event block

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2899 
> NOTE: `- After: https://exlm-2899--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2899--exlm--adobe-experience-league.aem.page
- After: https://exlm-2899--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2899--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2899--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2899 - Remove see more if no data from coveo

styles/styles.css, styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2907
> NOTE: `- After: https://EXLM-2907-1--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2907-1--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2907-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2907-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2907-1--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> fix: css updates for the grid block to avoid scrollbar EXLM-2907

component-definition.json, component-filters.json, component-models.json, scripts/adobe-target/adobe-target.js
Jira ID: EXLM-2896
> NOTE: `- After: https://exlm-2896--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2896--exlm--adobe-experience-league.aem.page
- After: https://exlm-2896--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2896--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2896--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2896 New section for PHP

blocks/recommendation-marquee/recommendation-marquee.css, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2895 
> NOTE: `- After: https://exlm-2895--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2895 - Fix thumbnail image z-index for hover

scripts/scripts.js
Reverts adobe-experience-league/exlm#1605
=> Revert "EXLM-2934 Point stage env Coveo search to Prod coveo search"

scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2921 
> NOTE: `- After: https://exlm-2921--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2921--exlm--adobe-experience-league.aem.page
- After: https://exlm-2921--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2921--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2921--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2921 - Serialize target data

blocks/personalized-content-placeholder/personalized-content-placeholder.js, blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js, scripts/adobe-target/adobe-target.js, scripts/responsive-pill-list/responsive-pill-list.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2917 
> NOTE: `- After: https://exlm-2917--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2917--exlm--adobe-experience-league.aem.page
- After: https://exlm-2917--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2917--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2917--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Update recommendation blocks on signup modal close event

blocks/personalized-content-placeholder/personalized-content-placeholder.css, scripts/scripts.js, styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2931 
> NOTE: `- After: https://exlm-2931--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2931--exlm--adobe-experience-league.aem.page
- After: https://exlm-2931--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2931--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2931--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2931 - Fix spinner in personalized content placeholder

scripts/data-service/coveo/coveo-token-service.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2940 
> NOTE: `- After: https://exlm-2940--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2940--exlm--adobe-experience-league.aem.page
- After: https://exlm-2940--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2940--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2940--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> Skip coveo token validity check in Dev and Stage

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.css, blocks/recommended-content/recommended-content.js
Jira ID:
> NOTE: `- After: https://exlm-2899-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2899-fix--exlm--adobe-experience-league.aem.page
- After: https://exlm-2899-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2899-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2899-fix--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2899 - Fix see more target issues

scripts/browse-card/browse-card.css
Jira ID: EXLM-2943
> NOTE: `- After: https://exlm-2943--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2943--exlm--adobe-experience-league.aem.page
- After: https://exlm-2943--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2943--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2943--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2943 Fixed Play button overlay on the Learn menu dropdown

google25ab3d98d543c7c0.html, googled2c03bdbeb2745db.html
Jira ID:
> NOTE: `$` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
$
$/en/docs?martech=off
$/en/docs?martech=off
$/en/docs/analytics?martech=off
$/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
$/en/playlists?martech=off
$/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
$/en/docs/home-tutorials?martech=off
$/en/docs/analytics-learn/tutorials/overview?martech=off
$/en/perspectives?martech=off
$/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off …
=> Google Site Verification

blocks/profile-rail/profile-rail.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2851
> NOTE: `- After: https://feat-exlm-2851--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2851--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2851--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2851--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2851--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- …
=> EXLM-2851 Links opening in new tab for nav

blocks/profile-rail/profile-rail.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2979 
> NOTE: `- After: https://exlm-2979--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2979--exlm--adobe-experience-league.aem.page
- After: https://exlm-2979--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2979--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2979--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM 2979 - Add scroll to left nav when required

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2904
> NOTE: `- After: https://EXLM-2904--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2904--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2904--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> feat: changes to preload the cards for show more btn EXLM-2904

blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2937
> NOTE: `- After: https://EXLM-2937--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2937--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2937--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2937--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2937--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> feat: changes to consume saved card response for see more btn EXLM-2937

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2904
> NOTE: `- After: https://EXLM-2904-1--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2904-1--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2904-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904-1--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> feat: stop fallback card loading & consume the savedCard response EXLM-2904

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js
Jira ID: EXLM-2904
> NOTE: `- After: https://EXLM-2904-2--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2904-2--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2904-2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904-2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2904-2--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> feat: changes to handle target data EXLM-2904

blocks/recently-reviewed/recently-reviewed.js, blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js, scripts/analytics/analytics.js, scripts/scripts.js, scripts/utils/analytics-utils.js
Jira ID: EXLM-2951
> NOTE: `- After: https://exlm-2951--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2951 Updated Rec marquee and Rec content block coveo value for analytics

blocks/header/header.js
Jira ID:
> NOTE: `- After: https://UGP-12583--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs …
=> Add signin option to header

blocks/header/header.js
Jira ID:
> NOTE: `- After: https://UGP-12583--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs …
=> Header - Emit Decoration events

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js, scripts/scripts.js, scripts/utils/analytics-utils.js
Jira ID: EXLM-2951
> NOTE: `- After: https://exlm-2951--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> EXLM-2951 PHP blocks coveo value for analytics

scripts/utils/analytics-utils.js
Jira ID: EXLM-2951
> NOTE: `- After: https://exlm-2951--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2951--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2951 Updated block name for analytics

component-models.json, styles/styles.css, styles/styles.scss
Jira ID: EXLM-2924
> NOTE: `- After: https://exlm-2924--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: …
=> EXLM-2924 Center alignment options for section

blocks/header/header.js, blocks/header/load-profile.js
Jira ID: [UGP-12583](https://github.com/adobe-experience-league/exlm/tree/UGP-12583)
> NOTE: `- After: https://UGP-12583--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
=> UGP-12583 Enhance header loading by making profile picture optional

styles/styles.css, styles/styles.scss
Jira ID: EXLM-2924
> NOTE: `- After: https://exlm-2924--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2924--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
=> EXLM-2924 Section alignment

scripts/scripts.js
Jira ID:
> NOTE: `- After: https://placeholders--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://placeholders--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> Show label used in placeholder spans as attribute

blocks/playlist-browse/dom-helpers.js, blocks/playlist-browse/playlist-browse.js, blocks/playlist/actions/playlist-bookmark-action.js, blocks/playlist/playlist-utils.js, blocks/playlist/playlist.js
Jira ID: EXLM-3008
> NOTE: `- After: https://exlm-3008--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-3008--exlm--adobe-experience-league.aem.live/en/playlists?martech=off
- After: https://exlm-3008--exlm--adobe-experience-league.aem.live/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
=> EXLM-3008 Localization for Playlist pages

.stylelintrc.json, package-lock.json, package.json
Jira ID: 
Test URLs:
- After: https://remove-sass--exlm--adobe-experience-league.aem.page
- After: https://remove-sass--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://remove-sass--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://remove-sass--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://remove-sass--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://remove-sass--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
=> Remove SASS completely from codebase pt.2

scripts/responsive-pill-list/responsive-pill-list.css, scripts/responsive-pill-list/responsive-pill-list.js
Jira ID: EXLM-2988
Test URLs:
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-2988--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign …
=> fix: update dom hierarchy and scroll css EXLM-2988

blocks/marquee/marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2923
Test URLs:
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-2923-bug--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> Exlm 2923 - Fix marquee variation issue

blocks/recently-reviewed/recently-reviewed.css, blocks/recommendation-marquee/recommendation-marquee.css, blocks/recommended-content/recommended-content.css, styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3048
Test URLs:
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://feat-exlm-3048--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> EXLM-3048 CSS changes in rec blocks

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-a …
=> Ensure exl IMS is not loaded when header is embeded in community

blocks/block-quote/block-quote.css
Jira ID: EXLM-3057
Test URLs:
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3057--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign …
=> EXLM-3057 Block quote - Color update for external callout

blocks/marquee/marquee.js, component-definition.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3062
Test URLs:
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3062--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> EXLM 3062 - Marquee variation bugs

blocks/featured-authors/featured-authors.css, blocks/featured-authors/featured-authors.js, blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3032 
Test URLs:
- After: https://exlm-3032--exlm--adobe-experience-league.aem.page
- After: https://exlm-3032--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3032--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> Featured Content | New style guide update

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js
Jira ID: EXLM-2989
Test URLs:
- After: https://exlm-2989--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-2989--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-2989--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-2989--exlm--adobe-experience-league.aem.live/en/browse?martech=off
- After: https://exlm-2989--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> EXLM-2989 Rec marquee and rec content block for unauthenticated case

blocks/article-marquee/article-marquee.css, blocks/author-bio/author-bio.css, blocks/author-bio/author-bio.js, blocks/author-summary/author-summary.css, blocks/callout/callout.css, component-models.json, scripts/browse-card/browse-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3061
Test URLs:
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://feat-exlm-3061--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3061 External color changes

blocks/browse-filters/browse-topics.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3071
Test URLs:
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: …
=> EXLM 3071 - Remove horizontal scroll from browse-page

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js
Jira ID: EXLM-3074
Test URLs:
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
- After: https://exlm-3074--exlm--adobe-experience-league.aem.live/en/test-folder/user-groups?martech=off
=> EXLM-3074 Icon Block css fixes

blocks/icon-block/icon-block.css
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3071 
Test URLs:
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/docs/home-tutorials?martech=off
- After: https://exlm-3072--exlm--adobe-experience-league.aem.page/en/perspectives?martech=o …
=> EXLM 3071 - Fix Horizontal Scroll due to Icon Block

blocks/announcement-ribbon/announcement-ribbon.css
Jira ID: EXLM-3089
Test URLs:
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live/en/browse?martech=off
- After: https://exlm-3089--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> EXLM-3089 Announcement Ribbon css update

component-models.json
Jira ID:
Test URLs:
- After: https://exlm-3060--exlm--adobe-experience-league.aem.page
- After: https://exlm-3060--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> change marquee subject description

blocks/upcoming-event/upcoming-event.js
Jira ID: EXLM-3091
Test URLs:
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
- After: https://exlm-3091--exlm--adobe-experience-league.aem.live/en/test-folder/events?martech=off
=> EXLM-3091 Event block filters update

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID: EXLM-3035
Test URLs:
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3035--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign …
=> fix: pass browse-topic selection as el_product when applicable EXLM-3035

blocks/article-marquee/article-marquee.css, blocks/article-marquee/article-marquee.js, component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3053 
Test URLs:
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3053--exlm--adobe-experience-league.aem.page/en/perspectives/cloud-manager-onboarding-playbook?martech=off
- After: …
=> Article Marquee | Straight background variation

styles/styles.css
Jira ID: https://jira.corp.adobe.com/browse/UGP-11630
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://bugfix-UGP-11630--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> bugfix/UGP-11630 Bold text color inside links

scripts/responsive-pill-list/responsive-pill-list.css, scripts/responsive-pill-list/responsive-pill-list.js
Jira ID: EXLM-3056
Test URLs:
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3056--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign …
=> feat: arrow pill implementation EXLM-3056

blocks/footer/footer.css, blocks/header/exl-header.css, scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3107 
Test URLs:
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3107--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=o …
=> EXLM - 3107 | Fix horizontal scrollbar on Perspective pages

blocks/notification-banner/notification-banner.css, component-definition.json
Jira ID:
Test URLs:
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3055--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-a …
=> EXLM 3055 - Fix notification banner style issues

blocks/detailed-teaser/detailed-teaser.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3117
Test URLs:
Before: https://main--exlm--adobe-experience-league.aem.page/
After: [https://feat-exlm-3117--exlm--adobe-experience-league.aem.live?martech=off](https://feat-exlm-3031-uefix--exlm--adobe-experience-league.aem.live/?martech=off)
After: https://feat-exlm-3117--exlm--adobe-experience-league.aem.live/en/browse?martech=off
After: https://feat-exlm-3117--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> EXLM-3117 CSS fixes for inline banner

blocks/marquee/marquee.css
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3111
Test URLs:
- After: https://exlm-3111-v3--exlm--adobe-experience-league.aem.page
- After: https://exlm-3111-v3--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3111-v3--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3111-v3--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3111-v3--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM 3111 - Remove Perspective specific styles for marquee

blocks/carousel/carousel.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3113
Test URLs:
- After: https://feat-exlm-3113-fix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3113-fix--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://feat-exlm-3113-fix--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://feat-exlm-3113-fix--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3113 Carousel teaser fix

scripts/responsive-pill-list/responsive-pill-list.js
Jira ID: EXLM-3056
Test URLs:
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3056-1--exlm--adobe-experience-league.aem.page/en/playlist …
=> fix: minor css updates for pill EXLM-3056

blocks/carousel/carousel.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3113
Test URLs:
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://carousel-scroll--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
=> EXLM-3113 - Fix scroll due to carousel

blocks/detailed-teaser/detailed-teaser.css, scripts/responsive-list/responsive-list.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3071 
Test URLs:
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://exlm-3071--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: …
=> EXLM - 3071 | Fix horizontal scrollbar on PHP

blocks/upcoming-event/upcoming-event.js, component-models.json, scripts/scripts.js
Jira ID: EXLM-3088
Test URLs:
- After: https://exlm-3088--exlm--adobe-experience-league.aem.live/en/events?martech=off
- After: https://exlm-3088--exlm--adobe-experience-league.aem.live/en/events?martech=off
=> EXLM-3088 Event signup banner

blocks/carousel/carousel.js, blocks/profile-rail/profile-rail.css, blocks/profile-rail/profile-rail.js, scripts/browse-card/browse-card-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3121
Test URLs:
- After: https://feat-exlm-3121--exlm--adobe-experience-league.aem.live
=> EXLM-3121 Format id function change for all languages

blocks/detailed-teaser/detailed-teaser.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3031
Test URLs:
- After: https://feat-exlm-3031-css--exlm--adobe-experience-league.aem.live?martech=off
- After: https://feat-exlm-3031-css--exlm--adobe-experience-league.aem.live/en/browse?martech=off
- After: https://feat-exlm-3031-css--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> EXLM-3031 Max width fix

blocks/marquee/marquee.css
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3111 
Test URLs:
- After: https://exlm-3111-v4--exlm--adobe-experience-league.aem.page
- After: https://exlm-3111-v4--exlm--adobe-experience-league.aem.page/en/test-folder/marquee
=> Exlm 3111 - Marquee Variations fix

blocks/media/media.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3122 
Test URLs:
- After: https://exlm-3122--exlm--adobe-experience-league.aem.page
- After: https://exlm-3122--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
=> EXLM 3122 - Fix issues in media block

blocks/browse-filters/browse-filters.css, blocks/profile-rail/profile-rail.css, scripts/browse-card/browse-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3092
Test URLs:
- After: https://exlm-3092--exlm--adobe-experience-league.aem.page
- After: https://exlm-3092--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://exlm-3092--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3092 | Place Content type label above the thumbnail

blocks/notification-banner/notification-banner.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3055 
Test URLs:
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3125-fix--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: …
=> EXLM 3125 - Match Notification Banner styles with XD

blocks/notification-banner/notification-banner.css
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3143 
Test URLs:
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM 3143 - Center align close icon in Notification Banner

scripts/utils/button-utils.js
=> todo: filter undefined

blocks/upcoming-event/upcoming-event.js
Jira ID:
Test URLs: EXLM-3145
- After: https://exlm-3145--exlm--adobe-experience-league.aem.page/en/events?martech=off
=> EXLM-3145 Fixed Events block issue due to Profile failure

blocks/icon-block/icon-block.css, styles/styles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3099
Test URLs:
- After: https://feat-exlm-3099--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3099--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://feat-exlm-3099--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM-3099 Font size fix for heading

component-definition.json, component-filters.json
Jira ID:
Test URLs:
- After: https://feature-exlm-3139--exlm--adobe-experience-league.aem.page
=> Custom RTE Options

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3137
Test URLs:
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://feat-exlm-3137--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3137 White color added in background color list

component-models.json
Jira ID: EXLM-3090
Test URLs:
- After: https://exlm-3090--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3090--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3090--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3090--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
=> EXLM-3090 Added root path for aem content picker

blocks/notification-banner/notification-banner.css
Jira ID:
Test URLs:
- After: https://exlm-3164--exlm--adobe-experience-league.aem.page
- After: https://exlm-3164--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3164--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3164--exlm--adobe-experience-league.aem.page/en/docs/journey-optimizer/using/get-started/quick-start/marketer
- After: https://exlm-3164--exlm--adobe-experience-league.aem.page/en/docs/journey-optimizer/using/get-started/quick-start/quick-start
=> EXLM 3164 - Fix Notification Banner style override

scripts/auth/profile.js
Jira ID: EXLM-3090
Test URLs:
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> EXLM-3090 Sign out redirect URL

blocks/icon-block/icon-block.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3172
Test URLs:
- After: https://feat-exlm-3172--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3172--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://feat-exlm-3172--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM-3172 Removed line height from heading

scripts/auth/profile.js
Jira ID: EXLM-3090
Test URLs:
- After: https://exlm-3090-v2--exlm--adobe-experience-league.aem.live?martech=off
=> EXLM-3090 Enhance Sign out redirect URL

blocks/upcoming-event/upcoming-event.js, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-live-events-adaptor.js
Jira ID: EXLM-3162
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/events?martech=off
- After: https://exlm-3162--exlm--adobe-experience-league.aem.live/en/events?martech=off
=> EXLM-3162 Events - Remove empty filters

blocks/notification-banner/notification-banner.css, blocks/notification-banner/notification-banner.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3164 
Test URLs:
- After: https://exlm-3164-v3--exlm--adobe-experience-league.aem.page
- After: https://exlm-3164-v3--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3164-v3--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3164-v3--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
=> EXLM 3164 - Fix Notification banner issues in profile pages

blocks/announcement-ribbon/announcement-ribbon.js, blocks/upcoming-event/upcoming-event.js, component-definition.json, component-models.json
Jira ID: EXLM-3153
Test URLs:
- After: https://exlm-3153--exlm--adobe-experience-league.aem.live/en/events?martech=off
=> EXLM-3153 Upcoming Event banner

blocks/browse-filters/browse-filters.css
Jira ID: EXLM-3047
Test URLs:
- After: https://EXLM-3047--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://EXLM-3047--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://EXLM-3047--exlm--adobe-experience-league.aem.live/en/browse?martech=off
- After: https://EXLM-3047--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
=> fix: update css to adjust no results block dimension EXLM-3047

blocks/recommendation-marquee/recommendation-marquee.js, blocks/recommended-content/recommended-content.js, scripts/adobe-target/adobe-target.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-2935 
Test URLs:
- After: https://exlm-2935--exlm--adobe-experience-league.aem.page
- After: https://exlm-2935--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-2935--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM 2935 - Order Target Recommended cards based on meta sort field

blocks/recommendation-marquee/recommendation-marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3188
Test URLs:
- After: https://exlm-3188--exlm--adobe-experience-league.aem.page
- After: https://exlm-3188--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3188--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3188--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://exlm-3188--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3188 | Fix Recs Marquee shimmer

styles/theme/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3213 
Test URLs:
- After: https://exlm-3213--exlm--adobe-experience-league.aem.page
- After: https://exlm-3213--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3213--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3213--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
=> EXLM 3213 - Fix page height in profile theme

component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-3180
Test URLs:
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/playlists?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
=> EXLM-3180 UE Code Block

component-filters.json
Jira ID:
Test URLs:
- After: https://exlm-3180--exlm--adobe-experience-league.aem.page
- After: https://exlm-3180--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
=> Code block

blocks/footer/footer.js, blocks/header/header.js, scripts/scripts.js
Jira ID: EXLM-3171 
Test URLs:
- After: https://exlm-3171--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3171--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3171--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
=> EXLM-3171 Header updates

blocks/header/profile-menu.js
Jira ID:
Test URLs:
- After: https://fix-profile-links--exlm--adobe-experience-league.aem.page
- After: https://fix-profile-links--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://fix-profile-links--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> ensure learn links use the navLinkOrigin

blocks/header/header.js, component-models.json, scripts/scripts.js
Reverts adobe-experience-league/exlm#1749
=> Revert "Header - Decorate Links"

blocks/header/header.js, component-models.json, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://header-links--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://header-links--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://header-links--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://header-links--exlm--adobe-experience-league.aem.page/en/browse?martech=off
=> Updated header links

component-models.json
Jira ID:
Test URLs:
- After: https://exlm-3191--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3191--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3191--exlm--adobe-experience-league.aem.live/en/docs/home-tutorials?martech=off
- After: https://exlm-3191--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3191--exlm--adobe-experience-league.aem.live/en/browse?martech=off
=> Updated Block Options

scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://UGP-12862--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> UGP-12862 - only lowercase urls that are on the same origin

component-models.json
Jira ID:
Test URLs:
- After: https://exlm-3134-v2--exlm--adobe-experience-league.aem.page
- After: https://exlm-3134-v2--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3134-v2--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: https://exlm-3134-v2--exlm--adobe-experience-league.aem.page/en/browse?martech=off
=> Exlm - 3134 | Update subject Image description text for Marquee

blocks/code/code.js
Jira ID: EXLM-3180
Test URLs:
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/docs/analytics-learn/tutorials/overview?martech=off
- After: https://exlm-3180--exlm--adobe-experience-league.aem.live/en/perspectives/adobe-analytics-attribution-panel-and-lookback-windows
=> feat: Code block updates exlm-3180

blocks/announcement-ribbon/announcement-ribbon.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3152
Test URLs:
- After: https://feat-exlm-3152-fix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3152--exlm--adobe-experience-league.aem.page/en/events?martech=off
=> EXLM-3152 Storage key name change

scripts/auth/fetch-stale-while-revalidate.js, scripts/auth/profile.js, scripts/gainsight/gainsight.js
Jira ID:
Test URLs:
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://EXLM-3292-2--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> EXLM-3292 - Ensure requests to update profile are cached properly (or not where apropriate)

scripts/scripts.js
Jira ID: EXLM-3282
Test URLs:
- After: https://exlm-3282--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3282--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3282--exlm--adobe-experience-league.aem.live/en/docs/home-tutorials?martech=off
- After: https://exlm-3282--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
=> EXLM-3282 Metadata cleanup

scripts/adobe-target/adobe-target.js, scripts/scripts.js
Jira ID : https://jira.corp.adobe.com/browse/EXLM-3156
Test URLs:
- After: https://exlm-3156--exlm--adobe-experience-league.aem.page
- After: https://exlm-3156--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3156--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3156--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3156--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
=> EXLM - 3156 - Perspectives | Enable Target Recs Blocks

blocks/footer/footer.css
Jira ID: EXLM-3235
Test URLs:
- After: https://footer-new-tab--exlm--adobe-experience-league.aem.live?martech=off
=> Footer new tab icon css

blocks/footer/footer.js
Jira ID:  EXLM-3235
Test URLs:
- After: https://exlm-3235-v2--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3235-v2--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> EXLM-3235 Footer language selector code cleanup

blocks/code/code.js, scripts/delayed.js, scripts/utils/prism-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3281
Test URLs:
- After: https://exlm-3281-v1--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3281-v1--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3281-v1--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> Exlm 3281 - Refactor code block to avoid import form delayed.js

blocks/header/header.js
Jira ID: EXLM-3280
Test URLs:
- After: https://exlm-3280--exlm--adobe-experience-league.aem.page?martech=off
=> EXLM-3280 Removed title from Adobe logo

blocks/atomic-search/atomic-search.css, blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-facet.js, blocks/atomic-search/components/atomic-search-result.js, blocks/atomic-search/components/atomic-search-skeleton.js, blocks/atomic-search/components/atomic-search-template.js, blocks/atomic-search/components/atomic-search-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3328
Test URLs:
- After: https://exlm-3328--exlm--adobe-experience-league.aem.live/en/search?martech=off
=> feat: atomic-search optimizations EXLM-3328

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-no-results.js, blocks/atomic-search/components/atomic-search-pager.js, blocks/atomic-search/components/atomic-search-query-summary.js, blocks/atomic-search/components/atomic-search-result.js, blocks/atomic-search/components/atomic-search-template.js, blocks/atomic-search/components/atomic-search-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3368
Test URLs:
- After: https://exlm-3368--exlm--adobe-experience-league.aem.live/en/search?martech=off
=> fix: atomic search issues EXLM-3368

blocks/atomic-search/components/atomic-search-template.js
Jira ID:
Test URLs:
- After: https://exlm-3365--exlm--adobe-experience-league.aem.page
- After: https://exlm-3365--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search | Remove ellipses from the link title

blocks/header/header.js, scripts/scripts.js, scripts/search/search.js
Jira ID:
Test URLs:
- After: https://authorable-search--exlm--adobe-experience-league.aem.page
=> Make Search Page authorable in header fragment

scripts/search/search.js
Test URLs:
- After: https://search-query-fix--exlm--adobe-experience-league.aem.page
- After: https://search-query-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://search-query-fix--exlm--adobe-experience-league.aem.page/en/search?lang=en#sort=relevancy
- After: https://search-query-fix--exlm--adobe-experience-league.aem.page/en/search?lang=en#f-el_contenttype=Perspective&f-el_product=Acrobat
=> Support legacy search query params

blocks/browse-rail/browse-rail.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3405
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/browse
- After: https://exlm-3405--exlm--adobe-experience-league.aem.live/en/browse?martech=off
=> 3405-bug-fix

styles/theme/docs.css
Jira ID:
Test URLs:
- After: https://UGP-13078--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
=> fix: (UGP-13078) update background in docs only

scripts/analytics/lib-analytics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3382
Test URLs:
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page/en/docs/analytics-learn/tutorials/overview?martech=off
- After: https://feat-exlm-3382--exlm--adobe-experience-league.aem.page/en/certification-home?m …
=> EXLM-3382 Certifications added in datalayer

blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3402
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/perspectives
- After: https://exlm-3402--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
=> fix: prioritize productType dropdown facet selection over topic selection EXLM-3402

scripts/browse-card/browse-cards-block.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3406 , https://jira.corp.adobe.com/browse/EXLM-3404
Test URLs:
- After: https://exlm-3406--exlm--adobe-experience-league.aem.page
- After: https://exlm-3406--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://exlm-3406--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> Fix tooltip placement and browse cards width

blocks/secondary-search/secondary-search.js, component-models.json, scripts/scripts.js
Jira ID: EXLM-3408
Test URLs:
- After: https://exlm-3408--exlm--adobe-experience-league.aem.live/en/test-folder/search?martech=off
=> EXLM-3408 Secondary Search URL Update

blocks/secondary-search/secondary-search.js
Jira ID:
Test URLs:
- After: https://exlm-3408--exlm--adobe-experience-league.aem.page/en/test-folder/search?martech=off
=> Remove Secondary search fallback url

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-facet-manager.js, blocks/atomic-search/components/atomic-search-no-results.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3393
Test URLs:
- After: https://exlm-3393--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Exlm 3393 | Update Atomic Search no results page

blocks/article-marquee/article-marquee.css, blocks/author-bio/author-bio.css, blocks/author-summary/author-summary.css, blocks/block-quote/block-quote.css, blocks/callout/callout.css, blocks/featured-authors/featured-authors.css, blocks/featured-content/featured-content.css, scripts/browse-card/browse-card.css, styles/styles.css
Jira ID: EXLM-3411
Test URLs:
- After: https://exlm-3411--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3411--exlm--adobe-experience-league.aem.page/en/perspectives/quickstart-for-personalization-testing-and-roadmap-creation?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/perspectives/personalizing-the-customer-experience-in-adobe-commerce.html?ref=exlm-3411
=> EXLM-3411 Fix css overlapping with UE styles

styles/theme/articles.css
Jira ID: EXLM-3416
Test URLs:
- After: https://exlm-3416--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3416--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM-3416 Revert Perspective Background from Grey back to White background

component-models.json
Jira ID: EXLM-3403
Test URLs:
- After: https://exlm-3403--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3403--exlm--adobe-experience-league.aem.page/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
=> EXLM-3403 Updated model definition for aem-content picker

blocks/atomic-search/components/atomic-search-template.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3389
Test URLs:
- After: https://exlm-3389-fix--exlm--adobe-experience-league.aem.page
- After: https://exlm-3389-fix--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search | Add padding to no results page

blocks/atomic-search/components/atomic-search-facet-manager.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3435
Test URLs:
- After: https://exlm-3435--exlm--adobe-experience-league.aem.page
- After: https://exlm-3435--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search | Add timeframe facet

blocks/atomic-search/components/atomic-search-facet-manager.js, blocks/atomic-search/components/atomic-search-facet.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3436 , https://jira.corp.adobe.com/browse/EXLM-3437 
Test URLs:
- After: https://exlm-3436--exlm--adobe-experience-league.aem.page
- After: https://exlm-3436--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search | Fix Facet visibility

blocks/atomic-search/components/atomic-search-template.js
Jira ID:
Test URLs:
- After: https://fix-placeholder--exlm--adobe-experience-league.aem.page
- After: https://fix-placeholder--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search | Fix answered placeholder

scripts/signup-flow/signup-flow-dialog.css
Jira ID: #3455
Test URLs:
- After: https://exlm-3455--exlm--adobe-experience-league.aem.live?martech=off
=> Signup - Product Interests Alignment

blocks/recommended-content/recommended-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3407 
Test URLs:
- After: https://exlm-3407--exlm--adobe-experience-league.aem.page
=> Recommended Content | Fix see more button

blocks/atomic-search/components/atomic-search-template.js
Jira ID:
Test URLs:
- After: https://fix-placeholders--exlm--adobe-experience-league.aem.live
- After: https://fix-placeholders--exlm--adobe-experience-league.aem.live/en/search?martech=off
=> Search | Remove placeholders contd

component-filters.json
Jira ID: EXLM-3457
Test URLs:
- After: https://exlm-3457--exlm--adobe-experience-league.aem.page/en/browse?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse.html?ref=exlm-3457
=> EXLM-3457 Enabled Announcement Ribbon Block for all themes

blocks/atomic-search/atomic-search.css, blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-box.js, blocks/atomic-search/components/atomic-search-facet.js, blocks/atomic-search/components/atomic-search-result.js, blocks/fragment/fragment.js, scripts/load-atomic-search-scripts.js, scripts/scripts.js
Jira ID: EXLM-3438
Test URLs:
- After: https://EXLM-3438-1--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> EXLM-3438: atomic search performance feedback

scripts/editor-support-seo.js, styles/styles.css, styles/ue-styles.css
Jira ID: EXLM-3366
Test URLs:
- After: https://exlm-3366--exlm--adobe-experience-league.aem.page
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/test-folder/test-heading.html?ref=exlm-3366
=> EXLM-3366 UE specific CSS file

blocks/fragment/fragment.js
Jira ID: EXLM-3438
Test URLs:
- After: https://EXLM-3438-2--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> chore: revert fragment block change EXLM-3438

blocks/atomic-search/components/atomic-search-breadbox.js
Jira ID: EXLM-3458
Test URLs:
- After: https://EXLM-3458--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> fix: add spacing for breadbox element labels EXLM-3458

scripts/responsive-pill-list/responsive-pill-list.js
Jira ID: EXLM-3456
Test URLs:
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3456--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech …
=> fix: update conditions for right nav arrow visibility EXLM-3456

blocks/marquee/marquee.css, blocks/marquee/marquee.js, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3432
Test URLs:
Before: https://main--exlm--adobe-experience-league.aem.page/
After: https://3432-exlm--exlm--adobe-experience-league.aem.live?martech=off
=> EXLM-3432 Embed Video into Marquee component

blocks/product-interests/product-interests.js, scripts/analytics/lib-analytics.js
Jira Task: UGP-13083
Before: https://main--exlm--adobe-experience-league.aem.page/en/docs?martech=off
After: https://exlm3432--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://UGP-13083--exlm--adobe-experience-league.aem.page/en/home/profile-settings?martech=off
=> initial code to push interests event

blocks/marquee/marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3500
Test URLs:
- After: https://exlm-3500--exlm--adobe-experience-league.aem.live/?martech=off
- After: https://exlm-3500--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
=> cta-button-fix

blocks/atomic-search/atomic-search.css
Jira ID: EXLM-3492
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.aem.page/en/search?martech=off
- After: https://EXLM-3492--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> fix: update the maxwidth of the atomic-search block EXLM-3492

blocks/atomic-search/components/atomic-result-children.js
Jira ID: EXLM-3491
Test URLs:
- After: https://exlm-3491--exlm--adobe-experience-league.aem.page/en/search
=> fix: increase spacing on replies section EXLM-3491

blocks/upcoming-event/upcoming-event.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3378
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/events
- After:  https://exlm-3378--exlm--adobe-experience-league.aem.page/en/events
=> font weight change

blocks/upcoming-event/upcoming-event.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3378
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/events
- After: https://exlm-3378--exlm--adobe-experience-league.aem.page/en/events
=> EXLM-3378 | Media query change

blocks/slides/slider-utils.js, blocks/slides/slides.js
=> slides: use audio from html

blocks/playlist-browse/playlist-browse.js, blocks/upcoming-event/upcoming-event.js
Jira ID:
Test URLs:
- After: https://3479-placeholder-change--exlm--adobe-experience-league.aem.page/en/events?martech=off
=> No results error message-placeholder change

blocks/media/media.css
Jira ID:
Test URLs:
- After: https://exlm-3560--exlm--adobe-experience-league.aem.page
- After: https://exlm-3560--exlm--adobe-experience-league.aem.page/en/test-folder/3560?martech=off
=> Media block-hyperlink styling

blocks/slides/slider-utils.js, blocks/slides/slides.js
Jira ID:
Test URLs:
- After: https://slides-refactor--exlm--adobe-experience-league.aem.page
- After: https://slides-refactor--exlm--adobe-experience-league.aem.page/en/slides/cloud-content-fragments?martech=off
=> refactor callout parsing

scripts/browse-card/browse-card.css
Jira ID:
Test URLs:
- After: https://icon-fix--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
=> Browse cards - play icon placement fix

scripts/auth/profile.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3502 
Test URLs:
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://exlm-3502--exlm--adobe-experience-league.aem.page/en/certification-home?martech=off
- After: …
=> EXLM 3502 - Clear profile cache when signing out

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3495
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-65/content/implementing/deploying/introduction/aem-with-mongodb
- After: https://exlm-3495--exlm--adobe-experience-league.aem.live/en/docs/experience-manager-65/content/implementing/deploying/introduction/aem-with-mongodb
=> EXLM - 3495 | Code Block Updates

scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3378
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/events
- After: https://events-clean-up--exlm--adobe-experience-league.aem.page/en/events
=> Remove parenthesis from timezone

scripts/browse-card/browse-card.css
Jira ID: EXLM-3484
Test URLs:
- After: https://exlm-3484--exlm--adobe-experience-league.aem.page
- After: https://exlm-3484--exlm--adobe-experience-league.aem.live/en/events?martech=off
- After: https://exlm-3484--exlm--adobe-experience-league.aem.live/en/test-folder/events?martech=off
- After: https://exlm-3484--exlm--adobe-experience-league.aem.live/en/browse?martech=off
=> EXLM-3484 Font color update for Upcoming and On-Demand Events

blocks/slides/slider-utils.js, blocks/slides/slides.css, blocks/slides/slides.js
Jira ID: EXLM-3581
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides
- After: https://exlm-3581--exlm--adobe-experience-league.aem.live/en/slides/components-console-slides?martech=off
=> fix: slides observations EXLM-3581

blocks/atomic-search/components/atomic-search-result.js
Jira ID: EXLM-3568
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/search/
- After: https://exlm-3568--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> fix: recommendation badge misalignment EXLM-3568

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3573
Test URLs:
- After: https://exlm-3573--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> Remove #_blank from href

blocks/article-metadata/article-metadata.css, styles/theme/docs.css
Jira ID: UGP-13107
Test URLs:
- After: https://UGP-13107-2--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-cloud-service/content/security/configuring-advanced-networking?martech=off
=> UGP-13107 - Better selector and docs for adding a line after metadata

blocks/upcoming-event-v2/upcoming-event-v2.css, blocks/upcoming-event-v2/upcoming-event-v2.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3483
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/events
- After: https://exlm-3483-clean--exlm--adobe-experience-league.aem.page/en/test-folder/events
=> EXLM-3483 | Sorting events

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-facet.js, blocks/atomic-search/components/atomic-search-template.js, icons/minus.svg, icons/plus.svg
Jira ID: EXLM-3571
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/search/
- After: https://exlm-3571-1--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> feat: limit to 5 facets & custom show more functionality EXLM-3571

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3572
Test URLs:
- After: https://exlm-3572--exlm--adobe-experience-league.aem.hlx.live
=> Masking full profile page

blocks/atomic-search/components/atomic-search-facet.js
Jira ID: EXLM-3571
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/search/
- After: https://exlm-3571-2--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> feat: handle facets visibility in more cases EXLM-3571

blocks/upcoming-event-v2/upcoming-event-v2.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3483
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/events
- After: https://exlm-3483-clean--exlm--adobe-experience-league.aem.page/en/test-folder/events
=> EXLM - 3483 | centered banner text

blocks/atomic-search/components/atomic-search-facet.js
Jira ID: EXLM-3571
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/search/
- After: https://exlm-3571-3--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> fix: position the show more btn properly during facets collapse EXLM-3571

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3604
Test URLs:
- After: https://exlm3604--exlm--adobe-experience-league.aem.page
=> updated model file

blocks/marquee/marquee.css, blocks/marquee/marquee.js, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3604
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
- After: https://exlm3604--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
=> EXLM-3604 | Marquee Text color updates

blocks/marquee/marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3604
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
- After: https://exlm3604--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
=> minor color fix

blocks/slides/slider-utils.js, blocks/slides/slides.js
Jira ID: EXLM-3592
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides
- After: https://EXLM-3592--exlm--adobe-experience-league.aem.live/en/slides/components-console-slides
=> feat: have docs view as default for mobiles EXLM-3592

blocks/atomic-search/components/atomic-search-result.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID:
Test URLs:
- After: https://exlm-3621--exlm--adobe-experience-league.aem.page
- After: https://exlm-3621--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Search Page : Multisolution

scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-3611
Test URLs:
- After: https://exlm-3611--exlm--adobe-experience-league.aem.page
- After: https://exlm-3611--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
- After: https://exlm-3611--exlm--adobe-experience-league.aem.page/en/events?martech=off
=> EXLM 3611 - fix on demand events colors and thumbnail

blocks/mini-toc/mini-toc.js
=> UGP-13342 - fix: mini toc headers with illegal chars not appearing

blocks/code/code.js, scripts/editor-support.js, scripts/utils/prism-utils.js
Jira ID: EXLM-3646
Test URLs:
- After: https://exlm-3646--exlm--adobe-experience-league.aem.live/en/test-folder/test-page/test-page2?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/test-folder/test-page/test-page2.html?ref=exlm-3646
=> EXLM-3646 UE - Code Block Highlight

blocks/playlist/playlist.css, blocks/playlist/playlist.js
Jira ID:
Test URLs:
- After: https://UGP-13342--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
=> fix: (UGP-13342) fix broken playlist images

blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.js, blocks/mini-toc/utils.js, blocks/toc/toc.css, scripts/rails/rails.js
Jira ID: EXLM-3594
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/docs/core-services/interface/experience-cloud
- After: https://EXLM-3594--exlm--adobe-experience-league.aem.live/en/docs/core-services/interface/experience-cloud
=> EXLM-3594: Compact mini-toc changes

blocks/atomic-search/components/atomic-search-result.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3656
Test URLs:
- After: https://exlm-3656--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Exlm-3656-clickable link color

blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.js
Jira ID: EXLM-3594
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/docs/core-services/interface/experience-cloud
- After: https://EXLM-3594-1--exlm--adobe-experience-league.aem.live/en/docs/core-services/interface/experience-cloud
=> fix: compact toc visibility even with sibling content EXLM-3594

blocks/atomic-search/components/atomic-search-result.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID: EXLM-3652
Test URLs:
- After: https://EXLM-3652--exlm--adobe-experience-league.aem.live/en/search
=> fix: hide child products from tooltip content EXLM-3652

blocks/slides/slider-utils.js, blocks/slides/slides.css, blocks/slides/slides.js, scripts/coachmark/coachmark.css, scripts/coachmark/coachmark.js
Jira ID:
Test URLs:
- After: https://EXLM-3661--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides?martech=off
=> EXLM-3661 & EXLM-3685 - Callouts as Spectrum indicators

blocks/slides/slider-utils.js, blocks/slides/slides.css, blocks/slides/slides.js, scripts/preferences/preferences.js
Jira ID:
Test URLs:
- After: https://EXLM-3661--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides?martech=off
=> Slides - simplify impl and use global preferences

scripts/browse-card/browse-card-utils.js, scripts/browse-card/browse-card.js
Jira ID: EXLM-3779
Test URLs:
- After: https://exlm-3779--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3779--exlm--adobe-experience-league.aem.live/en/perspectives/drive-success-with-executive-summary-dashboards?martech=off
- After: https://exlm-3779--exlm--adobe-experience-league.aem.live/en/browse?martech=off
=> EXLM-3779 Author type badge updates

blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.js
Reverts adobe-experience-league/exlm#1951
see: https://jira.corp.adobe.com/browse/UGP-13458
=> Revert "fix: compact toc visibility even with sibling content EXLM-3594"

blocks/toc/toc.css, scripts/scripts.js
=> UGP-13458 - roll back TOC changes - 2

scripts/analytics/lib-analytics.js
Jira ID: EXLM-3741
Test URLs:
- After: https://exlm-3741--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
=> EXLM-3741 DataLayer - Added featureAttribute metadata

blocks/slides/slider-utils.js, blocks/slides/slides.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3777 
Test URLs:
- After: https://exlm-3769-v2--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides?martech=off
- After: https://exlm-3769-v2--exlm--adobe-experience-league.aem.page/en/slides/cloud-content-fragments?martech=off
=> EXLM 3777 - Fix intermittent Callout issue in slides pages

blocks/playlist-browse/playlist-browse.js
Jira ID:
Test URLs:
- After: https://playlist-xss-vuln--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
=> Fix XSS vuln with playlists

component-models.json
Jira ID: EXLM-3688
Test URLs:
- After: https://exlm-3688--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example/skill-track-1-of-learning-collection?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/learning-collections/learning-collection-1-workfront-example/skill-track-1-of-learning-collection.html?ref=exlm-3688
=> EXLM-3688 Skill track page authoring

blocks/header/header.js
Jira ID:
Test URLs:
- After: https://header-search--exlm--adobe-experience-league.aem.page?martech=off
- After: https://header-search--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://header-search--exlm--adobe-experience-league.aem.page/en/search?martech=off
=> Header search mobile issue fix

blocks/slides/slider-utils.js, blocks/slides/slides.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3769 
Test URLs:
- After: https://exlm-3769-v3--exlm--adobe-experience-league.aem.page
- After: https://exlm-3769-v3--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides?martech=off
=> EXLM 3769 - Fix Slides docs view issue in mobile

component-definition.json
Jira ID:
Test URLs:
- After: https://ue-blocks--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> Arrange UE blocks in alphabetical order

blocks/toc/toc.js
Jira ID: EXLM-3789
Test URLs:
- After: https://exlm-3789--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
=> EXLM-3789 Unlocalized strings on TOC

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3764
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example
- After: https://drill-in--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example
=> EXLM-3674 | rewriting the x&y pos descriptions

blocks/drill-in/drill-in.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3764
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example
- After: https://drillIn-fix--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example
=> EXLM-3764 | fixed height issue

blocks/slides/slider-utils.js, scripts/analytics/lib-analytics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3819 
Test URLs:
- After: https://exlm-3819--exlm--adobe-experience-league.aem.page/en/slides/cloud-content-fragments
=> EXLM 3819 - Add a new event to track autoplay in slides

component-filters.json
Test URLs:
- After: https://flipcard-fix--exlm--adobe-experience-league.aem.page
=> Add flip-cards inside learning collection section

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://community--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> Load lang specific placeholders for community

scripts/search/search.js
Jira ID: EXLM-3813 
Test URLs:
- After: https://exlm-3813--exlm--adobe-experience-league.aem.live/en/docs?martech=off
=> EXLM-3813 Pre-select product filter for Community Header Search

scripts/search/search.js
Reverts adobe-experience-league/exlm#2011
=> Revert "EXLM-3813 Pre-select product filter for Community Header Search"

blocks/slides/slider-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3819 
Test URLs:
- After: https://exlm-3819-v1--exlm--adobe-experience-league.aem.page/en/slides/cloud-content-fragments
=> Exlm 3819 - Slides Analytics Fix  - V2

scripts/browse-card/browse-card-video-clip-modal.js, scripts/browse-card/browse-card.js
Jira ID: EXLM-3900, EXLM-3901
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/home
- After: https://EXLM-3900--exlm--adobe-experience-league.aem.live/en/home
=> feat: hide thumbnail and open in new tab EXLM-3900 EXLM-3901

blocks/flip-card/flip-card.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3878
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/flip-card
- After: https://exlm-3878--exlm--adobe-experience-league.aem.page/en/test-folder/flip-card
=> EXLM-3878 | Mobile enhancement for Flip card block

blocks/header/exl-header.css, blocks/playlist/playlist-action-menu.css, blocks/question/question.css
Jira ID:https://jira.corp.adobe.com/browse/EXLM-3700
https://jira.corp.adobe.com/browse/EXLM-3728
Quiz checked options color change
Test URLs:
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/it/docs?martech=off
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/es/docs?martech=off
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/ja/docs?martech=off
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/pt-br/docs?martech=off
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/sv/docs?martech=off
- After: https://exlm-3700--exlm--adobe-experience-league.aem.page/nl/docs?martech=off
=> search dropdown truncations fix

blocks/question/question.js, blocks/quiz/quiz.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3861
Test URLs:
- After:https://exlm-3861--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example/skill-track-1-of-learning-collection/quiz-of-skill-track?martech=off
=> Shuffling Quiz Questions

blocks/quiz/quiz.js, scripts/hash-utils.js
Jira ID:
Test URLs:
- After: https://shuffle-question--exlm--adobe-experience-league.aem.page
- After:https://shuffle-question--exlm--adobe-experience-league.aem.page/en/learning-collections/learning-collection-1-workfront-example/skill-track-1-of-learning-collection/quiz-of-skill-track?martech=off
=> quiz salt update

blocks/atomic-search/components/atomic-search-facet.js
Jira ID: EXLM-3817
Test URLs:
- After: https://exlm-3817--exlm--adobe-experience-league.aem.live/en/search
=> fix: search issues EXLM-3817

blocks/media/media.css
Jira ID:
Test URLs:
- After: https://exlm-3911--exlm--adobe-experience-league.aem.page
- After: https://exlm-3911--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3911--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3911--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: https://exlm-3911--exlm--adobe-experience-league.aem.page/en/browse?martech=off
=> Media Block - Safari Fix

component-definition.json
Jira ID: EXLM-3857
Test URLs:
- After: https://exlm-3857-v2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> EXLM-3857 Corrected block name typo

component-definition.json, styles/theme/courses.css
Jira ID:
Test URLs:
- After: https://exlm-3857-v2--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts/fundamentals-of-marketo-engage/skill-track-quiz?martech=off
=> EXLM-3857 Courses - Section CSS updates

blocks/drill-in/drill-in.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3846
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
- After: https://drillin-mob--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
=> Drillin mob

helix-query.yaml
Jira ID:
Test URLs:
- After: https://exlm-3823--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> EXLM-3823 Excluded fragments and json files from sitemap

blocks/drill-in/drill-in.css, blocks/drill-in/drill-in.js, scripts/coachmark/coachmark.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3889
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
- After: https://exlm-3889--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
=> EXLM-3889 | Styling Updates for Drill-In Block

scripts/browse-card/browse-card.js
Jira ID: EXLM-3933
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/home
- After: https://EXLM-3933--exlm--adobe-experience-league.aem.live/en/home
=> feat: hide bookmark icon for video clips EXLM-3933

scripts/browse-card/browse-card.js
Jira ID: EXLM-3927
Test URLs:
- After: https://EXLM-3927--exlm--adobe-experience-league.aem.live?martech=off
=> feat: open video modal on all click actions except the card options EXLM-3927

blocks/course-marquee/course-marquee.css, blocks/course-marquee/course-marquee.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
- After: https://course-marquee--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts
=> fix: multiple product/experience level and duplicate values

styles/theme/courses.css
Jira ID:
Test URLs:
- After: https://exlm-3965--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts/fundamentals-of-marketo-engage/get-to-know-marketo-engage?martech=off
=> EXLM-3965 Updated section bg color

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-utils.js, scripts/analytics/lib-analytics.js
Jira ID: EXLM-3909
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides
- After: https://revert-2055-EXLM-3759--exlm--adobe-experience-league.aem.live/en/slides/components-console-slides
=> Revert "feat: atomic search analytics EXLM-3759"

blocks/toc/toc.js
Jira ID:
Test URLs:
- After: https://exl-v2--exlm--adobe-experience-league.aem.page
=> Support TOC v2 in addition to legacy - better error handling

component-filters.json
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/courses?martech=off
- After: https://blocks--exlm--adobe-experience-league.aem.page/en/courses?martech=off
=> Updated component filters

blocks/drill-in/drill-in.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3972
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/drill-in
- After: https://EXLM-3972--exlm--adobe-experience-league.aem.page/en/test-folder/drill-in
=> EXLM-3972| fix: plus button centered on drill-in block

styles/theme/courses.css
Jira ID:
Test URLs:
- After: https://course-bg--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts?martech=off
- After: https://course-bg--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts/fundamentals-of-marketo-engage?martech=off
- After: https://course-bg--exlm--adobe-experience-league.aem.page/en/courses/marketo-engage-core-concepts/fundamentals-of-marketo-engage/navigate-marketo-engage-platform?martech=off
=> Course background color update

scripts/utils/course-utils.js
Jira ID: Tech Task
Test URLs: 
- After: https://course-meta--exlm--adobe-experience-league.aem.page/en/courses
=> Add utilities for fetching course meta

scripts/utils/course-utils.js
Jira ID:
Test URLs:
- After: https://undefined-error--exlm--adobe-experience-league.aem.page/en/docs?martech=off
=> Course Utils - Fix undefined error

scripts/browse-card/browse-card-video-clip-modal.js
Jira ID: EXLM-3984
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/home
- After: https://EXLM-3984--exlm--adobe-experience-league.aem.live/en/home
=> feat: add tracking for video play from the browse card video clip modal EXLM-3984

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-result.js, blocks/atomic-search/components/atomic-search-utils.js, scripts/analytics/lib-analytics.js
Jira ID: EXLM-3759,  EXLM-3962
Test URLs:
- After: https://EXLM-3759--exlm--adobe-experience-league.aem.live/en/search
=> Atomic search analytics

blocks/atomic-search/atomic-search.js, blocks/atomic-search/components/atomic-search-template.js
Jira ID:
Test URLs:
- After: https://exlm-4078--exlm--adobe-experience-league.aem.live/es/search?martech=off
=> EXLM-3078 Map locale based on atomic

blocks/flip-card/flip-card.css, blocks/flip-card/flip-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-4044
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/flip-card
- After: https://exlm-4044--exlm--adobe-experience-league.aem.page/en/test-folder/flip-card
https://github.com/user-attachments/assets/a2ff67c0-88fb-403a-b893-9f019b45e8f4
=> EXLM-4044 - Remove flip card cta

blocks/course-marquee/course-marquee.js, component-models.json, helix-query.yaml, scripts/scripts.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.live/en/courses/marketo-engage-core-concepts?martech=off
- After: https://exlm-4042--exlm--adobe-experience-league.aem.live/en/courses/marketo-engage-core-concepts?martech=off
=> EXLM-4042 Page properties for Courses
