adobe-experience-league/exlm

- scripts/lib-franklin.js
Some pages, like: https://main--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet happen to have the first image (LCP image) where the image `src` is set to `about:error`
_it seems_ Helix services try to load the original image from the converter HTML, but that image returns a 404, so helix replaces it with `<img src="about:error" ...>`
For that img, in FireFox specifically, `img.complete` evaluates to false, and firefox (unlike chrome) does not trigger neither a `load` not a `error` event; which the franklin scripts expect, see `waitForLCP` here: 
https://github.com/adobe-experience-league/exlm/blob/36df32e23f75ff85538ce33ffb833ae1ec9f3c03/scripts/lib-franklin.js#L706
As such, this PR change force resolves `waitForLCP` when the image source is …
> Fix firefox specific issue with image loading

- scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-186
Test URLs:
- After: https://feature-exlm-186-link-updates--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
> links with single `p` as parent to not render as buttons

- blocks/table/table.js
- scripts/lib-franklin.js
- scripts/scripts.js
This PR adds support for nested (or synthetic blocks). these blocks are initially rendered as a table, and this PR converts that table structure into a block that's automatically loaded.
See: https://github.com/adobe-experience-league/exlm-converter/pull/27 for converter context.
Jira ID: EXLM-172
Test URLs:
- After: https://feat-exlm-172--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/syntax-style-guide
> build table synthetic blocks

- paths.yaml
Added new file paths.yaml with reference to mappings to the path /content/exlm for Universal Editor and Franklin Repo Mapping
Jira ID:https://jira.corp.adobe.com/browse/EXLM-64
Dummy Test URLs:
After: https://feature-EXLM-64-ue-paths--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
> EXLM 64 UE Paths Update

- package-lock.json
- package.json
- preview.js
Type `npm run preview [<path>, <ref>]` to generate a preview of the path from command line. Branch will be auto-picked.
ex: `npm run preview docs/authoring-guide-exl/using/markdown/cheatsheet main`
Test URLs:
- After: https://utils-preview-cmd--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
> ability to hit preview from command line

- component-definition.json
Removed the allowed component data from the template to avoid nested sections 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-357
Dummy Test URLs:
After: https://feature-exlm-357-compdef--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
> EXLM 357 Removed Nested Setions from Component Definitions 

- paths.yaml
Currently there is still an issue handling extension in the inbound mapping in the delivery servlet. This can be mitigated by directly mapping metadata.json to /content/exlm/metadata.json.
> fix: preserve metadata.json extension

- blocks/header/header.css
- blocks/header/header.scss
We should the references relative to the file. This makes importing them in the context of AEM easier.
Test URLs:
- After: https://buuhuu-patch-5--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
> fix: make icons reference base relative

- scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-373
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/button-samples
- After: N/A
> fix: allow new tab link nav for all non abobe exp sites EXLM-373

- blocks/breadcrumbs/breadcrumbs.css
Added the required CSS for static context from the Converter end 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-280
Test URLs:
- After: https://feature-exlm-280-breadcrumb--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
Franklin Published Site with Static Content :
> EXLM 280 Breadcrumb Block

- blocks/teaser/teaser.css
- If a rich text input only has one paragraph ,then the` <p>` element gets stripped when published (see 3rd teaser example in test page) .
-  If the input field has multiple paragraphs the `<p>` elements are preserved (see 4th teaser example in testpage.)
The CSS was adapted to take this into account and prevent wrong font styles.
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/teaser-test-page
- After: https://fix-teaser-dark-style--exlm--adobe-experience-league.hlx.page/en/teaser-test-page
> fixed css style for dark theme in teaser

- scripts/rails/rails.css
- scripts/rails/rails.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-293
Test URLs:
- After: https://bugfix-exlm-293-ipad-mini-toc--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/authoring/tables
> fix: mini-toc sticky nature on ipad exlm-293

- blocks/carousel/carousel.css
Small fix so that teasers in a carousel in mobile view also show same vertical alignment behavior as for desktop and tablet.
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/carousel
- After: https://carousel-mobile-css-fix--exlm--adobe-experience-league.hlx.page/en/carousel
> Carousel fix: Mobile  view should have same alignment as desktop

- blocks/carousel/carousel.css
- component-models.json
Small fixes for Carousel /teaser:
- Removed fixed teaser alignment inside carousel see comment in [comment in EXLM-254](https://jira.corp.adobe.com/browse/EXLM-254?focusedCommentId=39137074&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39137074)
- Added missing color green for background drop down for teaser, see comment in[ EXLM-9](https://jira.corp.adobe.com/browse/EXLM-9)
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/carousel
- After: https://carousel-alignment--exlm--adobe-experience-league.hlx.page/en/carousel
> Carousel/Teaser: removed carousel alignment options, added missing teaser color

- component-definition.json
- component-models.json
Updated the component-definition.json component-models.json FOR Secondary Search with required fields according to AC
Jira ID:https://jira.corp.adobe.com/browse/EXLM-343
Test URLs:
- After: https://feature-exlm-343-sec-search--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
AEM Author URL : 
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/secondary-search-test-page.html?ref=feature-EXLM-343-sec-search
> EXLM 343 Secondary Search Block UE

- styles/styles.css
- styles/styles.scss
Jira ID: EXLM-470 
Updated hyperlink color to match with links on https://spectrum.corp.adobe.com/page/body/ as per Nick's comment in the ticket.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/target-dev/developer/client-side/at-js-implementation/at-js/how-atjs-works
- After: https://feature-exlm-470--exlm--adobe-experience-league.hlx.page/docs/target-dev/developer/client-side/at-js-implementation/at-js/how-atjs-works
> EXLM-470 Hyperlink color updated

- component-models.json
To be able to work with before/after urls when creating new components we need to push the `components-model.json` to main branch first since the converter always loads the model definition from this branch. If not then any content for new components will not be visible/rendered on the Before/After pages.
Jira ID: none
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/collapsible
- After: https://accordion-model--exlm--adobe-experience-league.hlx.page/en/collapsible
> add accordion and accordion-group to model for testing

- component-definition.json
Jira ID: EXLM-74
Test URLs:
- After: https://feature-exlm-74-icon-card-block--exlm--adobe-experience-league.hlx.page/en/icon-card
> EXLM-74 Added resourceType for Icon card

- blocks/media/media.css
Increase Fontsize above 1200px,
default body font size for all breakpoints is 18px.
Jira ID:
Test URLs:
- After: https://media-font-fix--exlm--adobe-experience-league.hlx.page/en/media
> Media Block : increase font size above 1200px

- blocks/media/media.js
you can't use `:scope` on a document fragment selector in Safari+Firefox.
Jira ID: EXLM-618
Test URLs:
- After: https://exlm-618--exlm--adobe-experience-league.hlx.page/en/media
> Media Block: remove :scope from querySelector

- scripts/scripts.js
If  a page has an image (`<picture>`) followed by a heading 1 (`<h1>`) the default franklin boilerplate code will try to generate a hero block, which is not what we want. This PR removes this auto blocking.
Jira ID: [EXLM-604](https://jira.corp.adobe.com/browse/EXLM-604)
Editor Before:  https://author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/marquee-issue-test.html
Editor After: https://author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/marquee-issue-test.html?ref=exlm-604
> remove hero auto blocking

- component-models.json
Reverts adobe-experience-league/exlm#255
Jira ID: EXLM-17
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse-filters
After: https://revert-255-feature-EXLM-17--exlm--adobe-experience-league.hlx.live/en/browse-filters
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse-filters.html?ref=revert-255-feature-EXLM-17
> Revert "EXLM-17 Browse filters"

- styles/styles.css
- styles/styles.scss
fixes the @media defintion for browse rails. the old definition didnt trigger on ipad pro 
Jira ID:
Test URLs:
- After: https://fix-ipad--exlm--adobe-experience-league.hlx.page/en/browse/acrobat
> fixed media defition for rail

- styles/styles.scss
stylelinting automatically tries to replace min-width wit >= , which does not work on ipad pro safari.
Jira ID:
Test URLs:
- After: https://fix-ipad2--exlm--adobe-experience-league.hlx.page/en/browse/acrobat
> add stylelint ignore to avoid incorrect autofixing

- blocks/teaser/teaser.css
The right alignment stopped working after accidently removing a css width in the last update.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-859
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/demo-teaser
- After: https://exlm-859--exlm--adobe-experience-league.hlx.page/en/demo-teaser
> EXLM-859:  Teaser - Right alignment not working

- component-models.json
To be able to work with before/after urls when creating new components we need to push the components-model.json to main branch first since the converter always loads the model definition from this branch. If not then any content for new components will not be visible/rendered on the Before/After pages.
> EXLM-76: add new tabs and tab block to component-model

- blocks/tabs/tabs.css
- blocks/tabs/tabs.js
- blocks/tabs/tabs.scss
- component-definition.json
- component-models.json
- scripts/editor-support.js
- Extended existing Tabs block used in `/docs` to make it available in markting pages and editable in UE.
- Changed font size for content and tab title to 18px to be in line with font sizes on marketing pages.
- Extended event handler for UE change event to keep the proper tab open after an edit.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-76
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/tab-group-test-page
- After: https://exlm-76--exlm--adobe-experience-league.hlx.page/en/tab-group-test-page
AEM authoring:
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/tab-group-test-page.html?ref=exlm-76
The changes should not affect the current rendering of the tabs block on docs pages:
- …
> EXLM-76: Add Tabs

- blocks/browse-filters/browse-filters.css
- head.html
EXLM-843
Better fix for the IOS input zoom issue while removing maximum-scale=1 from "viewport" meta which is not accessible (per page speed insights) 
Test URLs:
- After: https://bugfix-exlm-843-friendlier-fix--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
> EXLM-843 - better fix for IOS input zoom issue

- head.html
- scripts/delayed.js
- scripts/lib-franklin.js
- scripts/scripts.js
improve LCP score just a bit by:
1. dynamically importing analytics scripts so that `scripts.js` does not depend on it immediately
2. delay print.css loading to delayed.js 
Test URLs:
- After: https://improve-lcp--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Improve LCP

- blocks/marquee/marquee.js
- component-models.json
- Remove First CTA Type from properties panel
- Hard-code First CTA as 'secondary' style
- Remove Second CTA Type from properties panel
- Hard-code Second CTA as 'primary' style
- Change the field label 'Second CTA Text' to 'Sign up CTA text'
- Caption: 'Button text to prompt unauthenticated visitors to sign in' 
- Change the field label 'Second CTA Link' to 'Sign up CTA link'
- Hide the second CTA (now 'Sign up CTA') from authenticated visitors, like the 'Sign up' button in the Header
Jira ID: https://jira.corp.adobe.com/browse/EXLM-896
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en
- After: https://exlm-896--exlm--adobe-experience-league.hlx.page/en
> Exlm-896: Marquee CTA updates

- blocks/marquee/marquee.js
- component-models.json
Second CTA is always fixed sign in click event. Only Text of button is editable.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-979
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/exlm-896
- After: https://exlm-979--exlm--adobe-experience-league.hlx.page/en/exlm-896
> Exlm 979: remove editing of sign in link, add sign in event handler instead

- blocks/featured-cards/featured-cards.css
When adding a featured card block to page with other types of card blocks it causes layout issues for the other blocks due to lack of specificality in the featured-cards.css
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/test-product
- After: https://fix-featured-cards--exlm--adobe-experience-league.hlx.page/en/browse/test-product
> Fix CSS issues for featured cards

- paths.yaml
updates paths.yaml to return the /en/top-products.json product list maintained by the AEM author.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-898
Test URLs:
(cant be tested on a branch)
> add /en/top-products.json to paths.yaml

- scripts/data-service/toc-data-service.js
- scripts/session-keys.js
Jira ID: EXLM-176
Storing toc data in session storage seems to be cause cache issue when switching between different languages.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/de/docs/analytics-platform/using/cja-landing
- After: https://feature-exlm-176-toc--exlm--adobe-experience-league.hlx.live/de/docs/analytics-platform/using/cja-landing
> EXLM-176 Updated session storage code block for TOC

- paths.yaml
Test URLs:
- After: https://feature-enable-config--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Add Config Path to serve .helix/config 

- scripts/editor-support.js
With this change instant block reloads with eventually guaranteed affinity for read after write will be implemented.
I also added some logic to restore the ui state. this was already in place for tabs and is now for carousels. there may be other blocks that have some ui state like scroll offsets etc that we may have to look at individually. 
kudos to @duynguyen for getting this sorted out.
> fix: block reloading behavior

- blocks/doc-actions/doc-actions.js
Jira ID: EXLM-1055
Test URLs: 
- After: https://bugfix-exlm-484-copylink--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> EXLM-1055: desktop copy link event listener not working. rearrange code.

- blocks/adls-cards/adls-cards.js
Added the missing content Type from ADLS post-Dirk's changes  and removed the default content type
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1042
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/adls-test-1042
After: https://feature-exlm-1042-adls--exlm--adobe-experience-league.hlx.live/en/adls-test-1042
> EXLM 1042 ADLS Card

- blocks/browse-filters/browse-filters.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-17
Test URLs:
- After: https://exp-level-dropdown-width--exlm--adobe-experience-league.hlx.live/en/browse
> fix: adjust browse filters dropdown width to handle text overlap

- blocks/teaser/teaser.css
Fixed regression:
- text width for /browse pages was used for non browse pages
- Some missmatch how background image should behave for different widths
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1004
Test URLs:
- Before: 
https://main--exlm--adobe-experience-league.hlx.live/en/browse/exlm-1004-test-page
https://main--exlm--adobe-experience-league.hlx.live/en/uat/exlm-1004-test-page
- After: 
https://exlm-1004--exlm--adobe-experience-league.hlx.live/en/browse/exlm-1004-test-page
https://exlm-1004--exlm--adobe-experience-league.hlx.live/en/uat/exlm-1004-test-page
> exlm-1004: fix teaser text width on browse/non-browse pages

- helix-sitemap.yaml
Jira ID:
Test URLs:
- After: https://bugfix-sitema-include-en-lang--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Sitemaps - Add en as href lang

- scripts/editor-support.js
Currently changing properties for default content (title, text, image, button) require manual reload due to the new UE eventing.
This PR adds the necessary code to trigger the page update for changes made to this elements.
Test URLs:
- Before: 
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/uat/mirko-test.html
- After: 
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/uat/mirko-test.html?ref=default-content-event
> Add content-patch event handling for default content

- paths.json
- paths.yaml
Move helix config to page instead of dam file.
Test URLs:
- After: https://feature-move-config-to-page--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Move configuration to page instead of dam

- scripts/scripts.js
see: https://github.com/adobe-experience-league/exlm-converter/pull/187
Custom anchors will be present in headings at the end, as icons, and will have the special prefix `icon-anchor-` in the icon class name. We then use that class name (sans prefix) as the custom anchor for the heading.
Jira ID: EXLM-1117
Test URLs:
- After: https://feature-custom-anchors--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Custom Anchors

- scripts/scripts.js
Test URLs:
- After: https://feature-ims-based-on-hlx--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Authentication - base ims_clientid on weather current hostname is helix hostname or not

- scripts/editor-support.js
- scripts/lib-franklin.js
This implements the latest events for in-place reloading authored content:
- update / patch
- add 
- remove
- reorder
for sections, blocks and all default content.
As this does not require to reload the page anymore for all these actions, but uses the rendered content from AEM as returned by the service we don't see affinity issues anymore.
> feat: update editor support

- blocks/detailed-teaser/detailed-teaser.css
- Eyebrow sub-title, dark theme
- Color is #8C8C8C
- Appears too dark on some backgrounds, changing to #ccc
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1127
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/uat/exlm-1127-test-page
- After: https://detailed-teaser-color-fix--exlm--adobe-experience-league.hlx.live/en/uat/exlm-1127-test-page
> fixed eyebrow subtitle color for dark theme

- scripts/scripts.js
fedsConfig.privacy must be defined before privacy-standaone.js executes
Jira ID: EXLM-1132
Test URLs:
- After: https://bugfix-exlm-1132--exlm--adobe-experience-league.hlx.live/
> EXLM-1132:  fedsConfig.privacy must be defined before privacy-standaone.js executes

- styles/styles.css
- styles/styles.scss
There is an unwanted top padding added for the browse rail above 1440px
Before:
After:
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
- After: https://browse-rail-padding--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
> fix top padding for browse rail > 1440px

- scripts/editor-support-rte.js
- scripts/editor-support.js
> fix: decoreate richtext after blocks

- blocks/back-to-browsing/back-to-browsing.css
- blocks/back-to-browsing/back-to-browsing.js
- scripts/editor-support-rte.js
Navigating to a document page that has been rebuilt with the latest converter changes should show a "Back to browsing" link at the top of the page. The link should be hidden any other time.
I've been using: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/analyze/admin-overview/analytics-overview as the test page by changing the CTA anchor in the banner on the browse page to this and navigating to the docs page that way.
Jira ID: https://jira.corp.adobe.com/browse/UGP-10031
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/analytics/analyze/admin-overview/analytics-overview as the test page
- After: …
> UGP-10031: Back to Browsing button

- scripts/feedback/feedback.js
eds-dev has an outdated qualtrics.json that is causing errors. This resolves the issue where the error would continually print to console every 500 ms.
Jira ID:
Test URLs:
- After: https://feedback-fix--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Qualtrics clears retry interval on error

- scripts/analytics/lib-analytics.js
- scripts/scripts.js
This saves bytes on the critical path to LCP, but still loads these things as early as needed. 
Test URLs:
- After: https://defer-scripts--exlm--adobe-experience-league.hlx.live/?martech=off
Loading Seq. before
Loading Seq. after
Details for detailed PSI reports see: https://thinktanked.org/tools/deep-psi/deep-psi.html?url1=https%3A%2F%2Fmain--exlm--adobe-experience-league.hlx.live%2F%3Fmartech%3Doff&url2=https%3A%2F%2Fdefer-scripts--exlm--adobe-experience-league.hlx.live%2F%3Fmartech%3Doff
main (fcp, si, lcp, tti, tbt, cls)
defer-scripts (fcp, si, lcp, tti, tbt, cls)
the main difference I am looking at is in LCP avg: *(1391 ± 400.352)*  vs *(1220 ± 232.057)*
> fix: defer ffetch, lib-analyitics and profile-service

- blocks/browse-breadcrumb/browse-breadcrumb.js
- blocks/browse-rail/browse-rail.js
- After doing an edit with UE that affects a section (add , remove section, add remove blocks to a section), it will cause a reloading of the blocks.
- There 2 blocks , browse-breadcrumb and browse-rail that are auto blocks and dynamically generate content. 
- Currently this causes a new instance of the generated content added after each edit.
Test URLs:
- After: https://fix-autoblock-ue-edit--exlm--adobe-experience-league.hlx.live/en/browse
Author URLS:
- Before:
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse.html
- After:
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canva …
> Fix: Avoid dublication of autogenerated content after UE edit

- blocks/browse-rail/browse-rail.js
- component-definition.json
- component-filters.json
- component-models.json
- scripts/scripts.js
- styles/styles.css
- styles/styles.scss
Currently the browse rail for browse pages is created completely dynamic via auto blocking.
The request is to be able to override this with a custom navigation per page. This PR makes the following proposal:
- On a browse page , add a new `Editable Browse Rail Section` to main
- this will replace the autoblocking with `browse rail section` which contains a` browse rail` block:
- selecting the browse rail, you can edit the navigation via richtext:
- This PR is backward compatible, meaing if you delete `Browse Rail Section` it reverts back to autoblocking a dynamic navigation as before.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1217
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/exlm-1217-test-product/exm-1217-product-version-page-1/exlm-1217-produ …
> EXLM-1217: Browse: Authorable headings for left navigation 

- blocks/img-md/img-md.css
- blocks/img-md/img-md.js
- blocks/img-md/img-md.scss
- scripts/image-modal.js
- scripts/scripts.js
- styles/image-modal.css
- styles/styles.css
- styles/styles.scss
This PR handles images as inline elements with image options provided as a sibling text node.
see: https://github.com/adobe-experience-league/exlm-converter/pull/306
Jira ID: UGP-10614
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/support-resources/data-sheets/test-page
- After: https://ugp-10614--exlm--adobe-experience-league.hlx.page/en/docs/support-resources/data-sheets/test-page
> Handle images are inline elements, not blocks.

- scripts/scripts.js
Second PR to handle image errors
see: https://github.com/adobe-experience-league/exlm-converter/pull/306
Jira ID: UGP-10614
Test URLs:
- After: https://ugp-10614--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Handle images are inline elements, not blocks - handle erroring images

- blocks/carousel/carousel.css
The css import for the `detailed-teaser.css` inside `carousel.css` was missing. 
Initially only discovered on stage, its also reproducible on dev env, when cache is cleared in developer tools.
Jira ID:
Test URLs:
- After: https://exlm-1293--exlm--adobe-experience-league.hlx.page
Dev Author:
- Before : https://author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en.html
- After: https://author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en.html?ref=exlm-1293
> EXLM-1293:  Detailed teasers in carousel broken

- blocks/browse-filters/browse-filters.js
headingElement.firstChild.nodeType = 3 (TEXT_NODE) whether with style or not.
Note: The changes to revert to text component (headingStyle pattern) was already merged to main branch.
Jira ID: EXLM-1342
Test URLs:
- After: https://bugfix-exlm-1342-topics--exlm--adobe-experience-league.hlx.live/
> EXLM-1342: Topics font size issue

- blocks/block-quote/block-quote.css
- blocks/block-quote/block-quote.js
- component-definition.json
- component-filters.json
- component-models.json
- styles/styles.css
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1304
Block Quote vertical bar color will be picked up from Article Page Metadata Properties
By default it's set to External Indigo Color
Test URLs:
- After: https://feature-exlm-1304-block-quote--exlm--adobe-experience-league.hlx.live
> EXLM 1304 Block Quote

- blocks/block-quote/block-quote.css
Updated the CSS to override the default RTE styles with Block Quote content Style
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1364
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager
After: https://feature-exlm-1364-blocl--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager
Before 
After
> EXLM 1364 Block Quote RTE Issue

- scripts/analytics/lib-analytics.js
EXLM-1272: deselecting the browse topic, previous value is still in datalayer
Jira ID: EXLM-1272
Test URLs:
- After: https://bugfix-exlm-1272--exlm--adobe-experience-league.hlx.live/
> EXLM-1272: deselecting the browse topic, previous value is still in datalayer

- component-models.json
Updated page metadata to include page title 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1580
Test URLs:
- After: https://feature-exlm-1580-page-title--exlm--adobe-experience-league.hlx.live
> EXLM 1580 Page metadata to include Page Title

- component-filters.json
- scripts/editor-support.js
Hi Team - the only change related to this was the first commit (component-filters.json). The editor-support.js change was because code quality was complaining to an earlier PR.
Jira ID: EXLM-1696
Test URLs:
- After: https://feature-exlm-1696--exlm--adobe-experience-league.hlx.live/
> EXLM-1696:  enable the Browse Filters block on Article Landing pages

- component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1695
Test URLs:
- After: https://feat-exlm-1695--exlm--adobe-experience-league.hlx.page
> default heading for article marquee changed to h1

- scripts/browse-card/browse-card.css
Updated the CSS for the Article Card Heading from Celery to Grey
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1703
Test URLs:
After: https://feature-exlm-1705-insights--exlm--adobe-experience-league.hlx.live/
> EXLM 1703 Updates to Actionable Insights card

- blocks/toc/toc.css
Jira ID: UGP-10839
**User Story:** As a user of documentation and tutorials table of contents, I want the often long table of contents to have an independent scroll from the rest of the page so that I don't have to sacrifice my current reading location on the page to explore the TOC.
**Acceptance Criteria:**
- The scroll bar only appears when the user scrolls within the TOC area.
- The scroll bar is not visible when the TOC area is not being scrolled.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/deploying/restructuring/dynamicmedia-repository-restructuring-in-aem-6-5
- After: …
> UGP-10839 Removing transition that causes bug on mouse over, other CSS Fixes

- blocks/toc/toc.js
Jira ID: UGP-10847
**Problem:**
For users seeing a very long TOC, the active page may not be in view of the TOC when the page loads, especially on smaller browser window sizes.
**Proposed Solution:**
Enhance the current implementation to ensure the active page is visible in the TOC when the page loads. This involves scrolling the TOC to the active item with an appropriate offset to ensure it is in view.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/implementing/developing/introduction/getting-started
- After: https://feature-ugp-10847--exlm--adobe-experience-league.hlx.page/en/docs/experience-manage …
> Feature UGP-10847 - Improve Visibility of Active Page in Table of Contents

- blocks/header/header.js
Jira ID: EXLM-1780
This reverts the PR https://github.com/adobe-experience-league/exlm/pull/935
Test URLs:
- After: https://revert-935-remove-article-filter--exlm--adobe-experience-league.hlx.live
> EXLM-1780 Revert "Show Article search filter in lower envs only"

- blocks/browse-filters/browse-filter-utils.js
- blocks/header/header.js
PR to hide the "Perspectives" from header search dropdown and Browse Filters in Prod.
https://github.com/adobe-experience-league/exlm/pull/935
https://github.com/adobe-experience-league/exlm/pull/931
Test URLs:
- After: https://remove-perspectives--exlm--adobe-experience-league.hlx.live
> Disable Perspective in Prod Only

- scripts/prev-next-btn.js
- scripts/scripts.js
- styles/theme/docs.css
- styles/theme/docs.scss
This is a permanent fix that replaces the temp fix made here:
https://github.com/adobe-experience-league/exlm-prod/pull/38
Jira ID: UGP-11165
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/assets/dynamicmedia/using-rulesets-to-transform-urls?martech=off
- After: https://ugp-11165--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/assets/dynamicmedia/using-rulesets-to-transform-urls?martech=off
> UGP-11165 - Fix issue where pages with large TOC caused large gaps between sections

- blocks/browse-filters/browse-filter-utils.js
- blocks/header/header.js
- scripts/scripts.js
Adds a simple API to check if a feature flag is enabled by metadata.
and an example usage for `perspectives`
Authors can update bulk metadata value for `feature-flags` which can be comma separated to enable features.
Test URLs:
- After: https://feature-flag--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Feature Flags

- blocks/adls-cards/adls-cards.js
- blocks/bookmarks/bookmarks.js
- blocks/browse-filters/browse-filter-utils.js
- blocks/events-cards/events-cards.js
- blocks/featured-cards/featured-cards.js
- scripts/browse-card/browse-card-utils.js
- scripts/browse-card/browse-card.js
- scripts/browse-card/browse-cards-adls-adaptor.js
- scripts/browse-card/browse-cards-constants.js
- scripts/browse-card/browse-cards-coveo-data-adaptor.js
- scripts/browse-card/browse-cards-delegate.js
- scripts/browse-card/browse-cards-live-events-adaptor.js
- scripts/browse-card/browse-cards-paths-adaptor.js
- scripts/data-service/coveo/coveo-exl-pipeline-constants.js
- scripts/data-service/coveo/coveo-exl-pipeline-helpers.js
- scripts/scripts.js
This is to enable the creation of wrappers for additional pipelines or other data sources in the future and the ability to fetch exl pipeline queries without relying on browse card specific code.
Jira ID:
Test URLs:
- After: https://browse-card-split--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
> Pull common coveo logic out of browse card 

- scripts/profile/personalized-home.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2087 
Test URLs:
- After: https://exlm-2087--exlm--adobe-experience-league.hlx.live
> EXLM 2087 - Retrieve profile from session storage due to issue in safari

- blocks/header/header.js
reverting #1263
using `firstChild ` with the old markup would mean `firstchild.textContent` is `'\n            '`  actually  which is not desired. acurate.
> Revert #52

- blocks/switch/switch.css
- blocks/switch/switch.scss
- blocks/toc/toc.css
- blocks/toc/toc.js
Jira ID: UGP-10849
As an experienced user of documentation who is familiar with my product(s) tables of content, I want to be able to always see all items in the table of contents so that I have to expend less effort clicking to find the headlines I want. 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/commerce/storefront/authoring/authoring-commerce-experiences
- After: https://feature-ugp-10849--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-65/content/commerce/storefront/authoring/authoring-commerce-experiences
> UGP-10849 Expand All Switch

- blocks/playlist/playlist.css
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/playlists/advanced-tasks-in-adobe-acrobat?martech=off
- After: https://ugp-11746--exlm--adobe-experience-league.hlx.page/en/playlists/advanced-tasks-in-adobe-acrobat?martech=off
> Fix extra vertical spacing between playlist items and header

- blocks/browse-filters/browse-filters.js
- blocks/mini-toc/mini-toc.js
- blocks/mini-toc/utils.js
- blocks/toc/toc.js
- scripts/editor-support.js
- scripts/lib-franklin.js
- scripts/scripts.js
- styles/styles.css
- styles/styles.scss
- styles/theme/docs-solution-landing.css
- styles/theme/docs-solution-landing.scss
This PR enhanced theme handling and CLS issues in Doc pages specifically.
Also refactors how we determine which theme is which.
Test URLs:
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page?martech=off
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page/en/docs?martech=off
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page/en/docs/mix-modeler?martech=off
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page/en/docs/mix-modeler/using/overview?martech=off
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page/en/docs/mix-modeler/using/get-started/about?martech=off
- After: https://theme-handling--exlm--adobe-experience-league.hlx.page …
> Better theme handling for docs and other pages/themes

- scripts/adobe-target/adobe-target.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2623
> NOTE: `- After: https://exlm-2623--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2623--exlm--adobe-experience-league.aem.page
- After: https://exlm-2623--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2623--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2623--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> fix: target event handler scope EXLM-2623

- scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2591
> NOTE: `- After: https://exlm-2591-tr--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2591-tr--exlm--adobe-experience-league.aem.page
- After: https://exlm-2591-tr--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2591-tr--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2591-tr--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> fix: prevent truncation of description in JS, allow it via css exlm-2591

- scripts/responsive-pill-list/responsive-pill-list.css
- scripts/responsive-pill-list/responsive-pill-list.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2656
> NOTE: `- After: https://EXLM-2656-css--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2656-css--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2656-css--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2656-css--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2656-css--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> fix: responsive pill list ipad css issues exlm-2656

- component-definition.json
Jira ID: EXLM-2734
> NOTE: `- After: https://exlm-2734--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM-2734 Default content tree for new perspectives page

- component-definition.json
Jira ID: EXLM-2734
> NOTE: `- After: https://exlm-2734--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2734--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM-2734 Updated placeholder text for Perspective template

- blocks/recommendation-marquee/recommendation-marquee.js
Jira ID:
> NOTE: `- After: https://exlm-2818--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs: EXLM-2818
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: …
> EXLM-2818 Placeholders fix for recommendation marquee

- scripts/scripts.js
Jira ID: EXLM-2819
> NOTE: `- After: https://exlm-2819--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2819--exlm--adobe-experience-league.aem.page
- After: https://exlm-2819--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2819--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2819--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM-2819 Removed prehiding snippet for the existing home page

- blocks/recommendation-marquee/recommendation-marquee.js
- blocks/recommended-content/recommended-content.js
Jira ID: EXLM-2818
> NOTE: `- After: https://exlm-2818--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page?martech=off
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-2818--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off …
> EXLM-2818 Static default value for analytics product name

- helix-query.yaml
Jira ID: EXLM-2826
> NOTE: `- After: https://exlm-2826--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2826--exlm--adobe-experience-league.aem.page
- After: https://exlm-2826--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2826--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2826--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> Exclude JSON files from sitemap

- blocks/recommendation-marquee/recommendation-marquee.css
- blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2868
> NOTE: `- After: https://feat-exlm-2868-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://feat-exlm-2868-fix--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-2868-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2868-fix--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-2868-fix--exlm--adobe-experience-league.aem.page/en/docs/analyt …
> EXLM-2868 CSS changes for no thumbnail img

- scripts/adobe-target/adobe-target.js
Jira ID:
> NOTE: `- After: https://php-css-fix--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://php-css-fix--exlm--adobe-experience-league.aem.live?martech=off
- After: https://php-css-fix--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://php-css-fix--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: https://php-css-fix--exlm--adobe-experience-league.aem.live/en/docs/analytics/analyze/admin-overview/analytics-overview? …
> Append PHP Target blocks before Profile Rail section

- scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2895 
> NOTE: `- After: https://exlm-2895--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2895--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM 2895 - show laptop only when img is loaded

- blocks/recently-reviewed/recently-reviewed.js
- blocks/recommendation-marquee/recommendation-marquee.js
- blocks/recommended-content/recommended-content.js
…
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2888
> NOTE: `- After: https://EXLM-2888--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2888--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2888--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2888--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2888--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> fix: retain previous H-tag elements while updating the copy from target EXLM-2888

- scripts/scripts.js
Jira ID: EXLM-2934
> NOTE: `- After: https://exlm-2934--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2934--exlm--adobe-experience-league.aem.page
- After: https://exlm-2934--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2934--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2934--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM-2934 Point stage env Coveo search to Prod coveo search

- blocks/recommendation-marquee/recommendation-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2941
> NOTE: `- After: https://EXLM-2941--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://EXLM-2941--exlm--adobe-experience-league.aem.page
- After: https://EXLM-2941--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2941--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-2941--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> fix: correct recommendation marquee card ordering as per the new authoring order EXLM-2941

- blocks/profile-rail/profile-rail.css
- blocks/profile-rail/profile-rail.js
Jira ID: EXLM-2944
> NOTE: `- After: https://exlm-2944--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2944--exlm--adobe-experience-league.aem.page
- After: https://exlm-2944--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2944--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2944--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM-2944 Profile Rail - whitespace issue

- blocks/browse-filters/browse-filters.css
- scripts/browse-card/browse-card.css
- scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-2982
> NOTE: `- After: https://exlm-2982--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://exlm-2982--exlm--adobe-experience-league.aem.page
- After: https://exlm-2982--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2982--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-2982--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: …
> EXLM 2982 - Fix thumbnail load in browse cards

- blocks/header/header.js
Jira ID:
> NOTE: `- After: https://UGP-12583--exlm--adobe-experience-league.aem.page` will be automatically replaced with the proper origin (using your branch) to test performance against with AEM Sync Bot.
Test URLs:
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://UGP-12583--exlm--adobe-experience-league.aem.page/en/docs …
> Add messages and notifications urls for community

- blocks/recommendation-marquee/recommendation-marquee.js
- blocks/recommended-content/recommended-content.js
Jira ID: EXLM-3003
Test URLs:
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3003-1--exlm--adobe-experience-league.aem.page/en/playlist …
> fix: send facets to v2 call even when having features EXLM-3003

- blocks/recommendation-marquee/recommendation-marquee.js
- blocks/recommended-content/recommended-content.js
Jira ID: EXLM-3003
Test URLs:
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://EXLM-3003-2--exlm--adobe-experience-league.aem.page/en/playlist …
> feat: remove exclusion of duplicates EXLM-3003

- blocks/awards/awards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3132
Test URLs:
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://feat-exlm-3132--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
> EXLM-3132 Awards block date locale fix

- blocks/notification-banner/notification-banner.js
- scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3141 
Test URLs:
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/docs/analytics-learn/tutorials/overview?martech=off
- After: https://exlm-3141--exlm--adobe-experience-league.aem.page/en/perspectives?martech=off
- After: …
> EXLM 3141 - Fetch fragment based on Language

- component-definition.json
- component-filters.json
Jira ID: EXLM-3125 
Test URLs:
- After: https://exlm-3125--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3125--exlm--adobe-experience-league.aem.live/en/perspectives?martech=off
- After: https://exlm-3125--exlm--adobe-experience-league.aem.live/en/certification-home?martech=off
- After: https://exlm-3125--exlm--adobe-experience-league.aem.live/en/browse/analytics?martech=off
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/test-folder/fragments/notification-banner.html?ref=exlm-3125
> EXLM-3125 Remove header options from notification banner RTE

- scripts/scripts.js
... to ensure that themes are loaded first, then all blocks, including the ones in premain
Jira ID:
Test URLs:
- After: https://premain-order--exlm--adobe-experience-league.aem.page
- After: https://premain-order--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://premain-order--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://premain-order--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://premain-order--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://premain-order--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: …
> Move load blocks to lazy phase for premain

- blocks/featured-cards/featured-cards.css
- blocks/featured-cards/featured-cards.js
- blocks/recently-reviewed/recently-reviewed.css
- blocks/recently-reviewed/recently-reviewed.js
- blocks/recommendation-marquee/recommendation-marquee.css
- blocks/recommended-content/recommended-content.css
- blocks/recommended-content/recommended-content.js
- blocks/tabbed-cards/tabbed-cards.css
- blocks/tabbed-cards/tabbed-cards.js
- scripts/browse-card/browse-card-shimmer.css
- scripts/browse-card/browse-card.css
- scripts/browse-card/browse-cards-block.css
EXLM-3059 
This PR uses [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries) to address an issue with card widths on browse pages. It ensure a specific number of clolumns in card grid is used based on the _container width_ NOT the _view port width_
https://github.com/user-attachments/assets/ccebde23-0760-4172-b2dd-dc77e39028ef
Jira ID:
Test URLs:
- After: https://EXLM-3059-v2--exlm--adobe-experience-league.aem.page
- After: https://EXLM-3059-v2--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://EXLM-3059-v2--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: …
> EXLM-3059 -  browser cards - always show 4 cards - base the column number on the container width

- blocks/code/code.js
Jira ID: EXLM-3281
Test URLs:
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3281--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign …
> fix: Code block rendering in UE mode exlm-3281

- blocks/article-metadata-appliesto/article-metadata-appliesto.css
- blocks/article-metadata-createdby/article-metadata-createdby.css
Jira ID: UGP-9959 Show version(s) as 'Applies to' in ExL pages
Test URLs:
- After: https://feature-ugp-9959--exlm--adobe-experience-league.aem.page
- After: https://feature-UGP-9959--exlm--adobe-experience-league.aem.page
- After: https://feature-UGP-9959--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://feature-UGP-9959--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-components/create-an-adaptive-form-on-forms-cs/template-editor-core-components?martech=off
- After: https://feature-UGP-9959--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: …
> feature/UGP-9959 Fix spacing order on blocks

- blocks/article-metadata-appliesto/article-metadata-appliesto.css
- blocks/article-metadata-createdby/article-metadata-createdby.css
- blocks/article-metadata-topics/article-metadata-topics.css
Jira ID: UGP-9929
Test URLs:
- After: https://ugp-9959-1--exlm--adobe-experience-league.aem.page
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page/en/docs/internal-test/test/table-spans?martech=off
- After: https://UGP-9959-1--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-c …
> UGP-9959 Adding separator to "Applies to" items

- styles/theme/docs.css
Jira ID: UGP-13000 - Caution badges rendering as gray instead of yellow
Test URLs:
- After: https://bugfix-ugp-1300--exlm--adobe-experience-league.aem.page
- After: https://Bugfix-UGP-1300--exlm--adobe-experience-league.aem.page
- After: https://Bugfix-UGP-1300--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://Bugfix-UGP-1300--exlm--adobe-experience-league.aem.page/en/docs/internal-test/test/feature-testing/badge?martech=off
- After: https://Bugfix-UGP-1300--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-cloud-service/content/implementing/developing/universal-editor/page-editor-universal-editor?martech=off
> Bugfix/UGP-13000  Caution badges rendering as gray instead of yellow

- scripts/search/search.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3328 
Test URLs:
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page/en/docs?martech=off
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page/en/docs/analytics?martech=off
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page/en/docs/analytics/analyze/admin-overview/analytics-overview?martech=off
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page/en/playlists?martech=off
- After: https://exlm-3328-query--exlm--adobe-experience-league.aem.page/en/playlists/acrobat-sign-perform-advanc …
> EXLM 3328 - Fix Search URL query parameter format

- blocks/browse-rail/browse-rail-utils.js
- blocks/browse-rail/browse-rail.js
Jira ID:
Test URLs:
- After: https://browse-rail--exlm--adobe-experience-league.aem.page/en/browse/experience-manager?martech=off
- After: https://browse-rail--exlm--adobe-experience-league.aem.page/en/browse?martech=off
- After: https://browse-rail--exlm--adobe-experience-league.aem.page/en/browse/analytics?martech=off
- After: https://browse-rail--exlm--adobe-experience-league.aem.page/en/browse/journey-optimizer?martech=off
- After: https://browse-rail--exlm--adobe-experience-league.aem.page/en/browse/journey-optimizer-b2b-edition?martech=off
> Fix Browse rail sub page issue

- blocks/atomic-search/atomic-search.js
Jira ID:
Test URLs:
- After: https://atomic-search-token--exlm--adobe-experience-league.aem.page
> chore: consume correct coveo token for atomic search

- scripts/search/search.js
Jira ID:
Test URLs:
- After: https://atomic-search-filters--exlm--adobe-experience-league.aem.page/en/search
> fix: send correct urlParams to coveo atomic search to honour filters

- component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-3604
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
- After: https://EXLM-3604--exlm--adobe-experience-league.aem.page/en/test-folder/marquee-text-color
> adding maxsize 6 to marquee block

- scripts/search/search.js
Jira ID: EXLM-3641
Test URLs:
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live?martech=off
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live/en/docs?martech=off
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live/en/docs/analytics?martech=off
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live/en/playlists?martech=off
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live/en/playlists/acrobat-sign-perform-advanced-tasks-administrators?martech=off
- After: https://exlm-3641--exlm--adobe-experience-league.aem.live/en/docs/home-tutorials?martech=off
- After: …
> EXLM-3641 Default filter/(s) set if user uses search from various page types

- blocks/atomic-search/components/atomic-search-result.js
Jira ID: EXLM-3706
Test URLs:
- After: https://EXLM-3706-3--exlm--adobe-experience-league.aem.live/en/search
> fix: consider elements with '|' symbol in name as child elements EXLM-3706

- blocks/slides/slides.css
... otherwise the callouts do not lineup.
Jira ID:
Test URLs:
- After: https://slides-container--exlm--adobe-experience-league.aem.page/en/slides/components-console-slides?martech=off
> use container queries for slides because it will be used in docs content (not full width)

- scripts/scripts.js
potential fix for UGP-13417
adding this property will let IMS ALWAYS cleanup token fragment in the URL regardless or the token origin.
see: https://git.corp.adobe.com/pages/IMS/imslib2.js/classes/adobe-id_AdobeIdData.AdobeIdData.html#alwaysremovetokenfromurl
> IMS to always remove token from URL

- blocks/mini-toc/mini-toc.js
Jira ID: EXLM-3797
Test URLs:
- Before: https://main--exlm--adobe-experience-league.aem.page/en/docs/experience-manager-cloud-service/content/assets/overview
- After: https://EXLM-3797-toc--exlm--adobe-experience-league.aem.live/en/docs/experience-manager-cloud-service/content/assets/overview
> fix: exclude header elements from tabs component EXLM-3797
