package-lock.json, styles/fonts.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-113
Test URLs:
- After: https://feature-exlm-113-typography--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> typography updates to body and heading fonts - Part 1/n

sass-compile.js, styles/fonts.css, styles/sass/_breakpoints.scss, styles/styles.css, styles/styles.scss
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-114
Test URLs:
- After:  https://feature-exlm-114-breakpoints--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Add breakpoints Mixin

.stylelintrc.json, package.json, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-43
Test URLs:
- After: https://feature-exlm-43-tooling--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> tooling updates - sass

blocks/badge/badge.css, blocks/badge/badge.js, blocks/badge/badge.scss
Jira ID:#144
Test URLs:
- After: https://feature-exlm-144-badge--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/syntax-style-guide
=> Badge Decorate Changes

blocks/embed/embed.css, blocks/embed/embed.scss
Jira ID: [EXLM-152](https://jira.corp.adobe.com/browse/EXLM-152)
Test URLs:
- After: https://feat-exlm55-video--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-152 Video block

blocks/related-articles/related-articles.css, blocks/related-articles/related-articles.js, blocks/related-articles/related-articles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-88
Test URLs:
- After: https://feature-exlm-88-relatedarticles--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Feature EXLM-88 relatedarticles Block

head.html
Jira ID: [EXLM-155](https://jira.corp.adobe.com/browse/EXLM-155)
Test URLs:
- After: https://fix-exlm-155-firefox--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-155 Firefox issue

blocks/table/table.css, blocks/table/table.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-94
Test URLs:
- After: https://feature-exlm94-table-block--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-94: add table block. Copied from Block Party.

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-115
Test URLs:
- After: https://feature-exlm-115-spacing--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM 115 add Spacing variables

blocks/tabs/tabs.css, blocks/tabs/tabs.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-164
Test URLs:
- After: https://feature-exlm-164-tabs-scroll--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> update tabs to not see scollbar

head.html, styles/print/print.css, styles/print/print.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-127
Test URLs:
- After: https://feature-exlm-127-print-css--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> print styles from existing site

blocks/tabs/tabs.css, blocks/tabs/tabs.js, blocks/tabs/tabs.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-166
Test URLs:
- After: https://fix-exlm-166-tabs-bugfix--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-166 tabs bugfix

blocks/code/code.css, scripts/prism.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-56
Test URLs:
After: https://feature-exlm-56-code--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM 56 Code Highlight and Toggle wrap fix

blocks/badge/badge.js
Jira ID:EXLM-169
Test URLs:
- After: https://bugfix-exlm-169-badge-target--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/syntax-style-guide
=> Added Target Attribute

README.md, fstab.yaml
Jira ID:
Test URLs:
- After: https://bugfix-undo-gandal-fstab-change--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> undo fork merge mistake

.stylelintrc.json, package-lock.json, package.json, sass-compile.js, styles/sass/_typography.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-184
Test URLs:
- After: https://feature-exlm-184-text-styles--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-184 text styles

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-188
Test URLs:
- After: https://feature-exlm-188-inline-code--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> exlm-188: inline code block styles

blocks/code/code.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-210
Test URLs:
- After: https://feature-exlm-56-code--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Code Block CSS issue fix

blocks/video-transcript/video-transcript.css, blocks/video-transcript/video-transcript.js, blocks/video-transcript/video-transcript.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-177
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/target-learn/tutorials/activities/create-ab-tests
- After: https://feature-exlm-177-transcript--exlm--adobe-experience-league.hlx.page/docs/target-learn/tutorials/activities/create-ab-tests
=> Add Video Transcript Block

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-266
Test URLs:
- After: https://bugfix-exlm-266-inline-code-lh--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix line-height for inline-code block

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-270
Test URLs:
- After: https://bugfix-exlm-270-target-blank--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> handle external links on client side

icons/rail.svg, scripts/scripts.js, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-224
Test URLs:
- After: https://feature-exlm-224-layout--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> feat: layout EXLM-224

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-270
Test URLs:
- After: https://bugfix-exlm-270-target-blank--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Handle external URL

styles/styles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-224
Test URLs:
- After: https://feature-exlm-224-layout--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: push missing css file EXLM-224

blocks/badge/badge.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-271
Test URLs:
- After: https://bugfix-exlm-271-badge--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/syntax-style-guide
=> fix New Tab issue in Badge

blocks/article-metadata-createdby/article-metadata-createdby.css, blocks/article-metadata-createdby/article-metadata-createdby.scss, blocks/article-metadata-topics/article-metadata-topics.css, blocks/article-metadata-topics/article-metadata-topics.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-180
Test URLs:
- After: https://bugfix-exlm-180-created-by--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> changes to createdby and topic

scripts/lib-franklin.js
Jira ID: 
Test URLs:
- After: https://bugfix-section-load--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Fix for right rail early load

blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.scss, styles/styles.css, styles/styles.scss
Jira ID: EXLM-209
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
After: https://bugfix-mini-toc-width--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> mini toc width issue

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-283
Test URLs:
- After: https://bugfix-exlm-283-sublist--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> update sublist to be alphabetical

blocks/table/table.css, blocks/table/table.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-276
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/authoring/tables
After: https://bugfix-exlm-276-table--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/authoring/tables
=> Table Bug Fix

blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.scss, scripts/scripts.js, scripts/utilities.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-209
Test URLs:
- After: https://bugfix-exlm-286--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: toc layout footer ui updates EXLM-286

blocks/article-metadata-createdby/article-metadata-createdby.css, blocks/article-metadata-createdby/article-metadata-createdby.scss, blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID:
https://jira.corp.adobe.com/browse/EXLM-286
https://jira.corp.adobe.com/browse/EXLM-288
https://jira.corp.adobe.com/browse/EXLM-308
Test URLs:
- After: https://bugfix-exlm-288--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: ui issues for footer, layout EXLM-288 EXLM-308 EXLM-286

blocks/article-metadata-createdby/article-metadata-createdby.css, blocks/article-metadata-createdby/article-metadata-createdby.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-286
Test URLs:
- After: https://bugfix-exlm-286--mini-toc--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: meta bottom margin EXLM-286

component-definition.json, component-models.json
Raised PR Awaiting Review and Approval
Added new files components-models and components-definition with three different groups Default Content, Containers, Blocks with required sample components
Components Included
**Default Content**
Text,Title,Image,Button,Section
**Containers**
Section
**Blocks**
None
Jira ID:https://jira.corp.adobe.com/browse/EXLM-92
After: https://feature-EXLM-92-components-models-ue--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM 92 UE Components and Models

component-models.json
Jira ID:https://jira.corp.adobe.com/browse/EXLM-92
Dummy Test URLs:
After: https://feature-exlm-92-components--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Updated component-models.json

blocks/footer/footer.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-331
Test URLs:
- After: https://bugfix-exlm-331-footer-ipad--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: footer ui ipad issue EXLM-331

paths.yaml
Jira ID:
Test URLs:
- After: https://<BRANCH NAME>--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> feat: add bulk metadata json

paths.yaml
Jira ID: EXLM-96 
Test URLs:
- After: https://feature-EXLM-96-Paths-mapping--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> EXLM-96 Updated paths mapping

blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.js, blocks/mini-toc/mini-toc.scss, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs: https://jira.corp.adobe.com/browse/EXLM-293
- After: https://bugfix-exlm-293--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> fix: mini toc issues EXLM-293

blocks/header/header.css, blocks/header/header.scss
Jira ID: EXLM-328
Test URLs:
- After: https://bugfix-exlm-328--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> defect-fix

package.json
Jira ID:
Test URLs:
- After: https://utils-preview-cmd--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> update aem to hlx in command line

paths.yaml
Jira ID: EXLM-96
Test URLs:
After: https://feature-exlm-96-paths-mapping--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Feature exlm 96 paths mapping

blocks/img/img.css, blocks/img/img.js, blocks/img/img.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-322, https://jira.corp.adobe.com/browse/EXLM-323,  https://jira.corp.adobe.com/browse/EXLM-325
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
- After: https://exlm-323-img-block--exlm--adobe-experience-league.hlx.page/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
=> feat: img block updates EXLM-323

paths.yaml
Reverts adobe-experience-league/exlm#85
=> Revert "fix: preserve metadata.json extension"

blocks/img/img.css, blocks/img/img.js, blocks/img/img.scss, scripts/delayed.js
Jira ID: EXLM-324
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
- After: https://feature-exlm-324-img--exlm--adobe-experience-league.hlx.live/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
=> image-zoomable

blocks/table/table.css, blocks/table/table.js, blocks/table/table.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-273 
Test URLs:
- After: https://feature-exlm-273-table--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/authoring/tables
=> Add HTML table 

blocks/accordion/accordion.css, blocks/accordion/accordion.js, blocks/accordion/accordion.scss, blocks/shade-box/shade-box.css, blocks/shade-box/shade-box.scss, icons/chevron_right.svg, styles/styles.css, styles/styles.scss
Jira ID: EXLM-83
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/test/collapsible-content
- After: https://feature-exlm-83-accordion--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/test/collapsible-content
=> EXLM-83: accordion block

scripts/lib-franklin.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-347
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/button-samples
- After: NA
=> feat: button block ui EXLM-73

blocks/header/header.scss, styles/sass/_breakpoints.scss, styles/sass/_typography.scss, styles/styles.css, styles/styles.scss
Jira ID:#EXLM-348
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/markdown/syntax-style-guide
- After: https://feature-exlm-348-styles--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/markdown/syntax-style-guide
=> Header and Content Stylings - Changes

scripts/scripts.js
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
- After: https://feature-toc--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
=> Fix issue with rails not loading

scripts/delayed.js, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://feature-toc--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Load rails in delayed.js

blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, blocks/header/header.js, package.json, scripts/delayed.js, styles/rail-styles.css, styles/rail-styles.scss, styles/styles.css, styles/styles.scss
A collection of changes to improve SEO, a11y and performance scores
... although performance still not great... but this is a step in the right direction
Jira ID:
Test URLs:
- After: https://bugfix-improve-score--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Improve pagespeed score

styles/styles.css, styles/styles.scss
Jira ID:EXLM-348
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/markdown/cheatsheet
- After: https://feature-exlm-348-new-styles--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Font Fixes

blocks/accordion/accordion.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-83
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
- After: https://bugfix-exlm-83-accordion--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
=> Fix nested blocks in Accordion 

.prettierignore, scripts/delayed.js, scripts/rails/rails.css, scripts/rails/rails.js, scripts/rails/rails.scss, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-390--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-390 - Move rails loading to just before delayed, and fix missing icons

blocks/mini-toc/mini-toc.css, scripts/rails/rails.css, scripts/rails/rails.scss
Jira ID: EXLM-390 
Test URLs:
- After: https://bugfix-exlm-390--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/authoring/tables
=> EXLM-390 - Fix rail toggle alignment

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-386
Test URLs:
- After: https://bugfix-exlm-386-button-ui--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Bugfix/exlm 386 button UI

paths.yaml, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-384
Test URLs:
- After: https://bugfix-exlm-384-btn-target--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Getting external links only to open in new window

blocks/article-metadata-createdby/article-metadata-createdby.css, blocks/article-metadata-createdby/article-metadata-createdby.js, blocks/article-metadata-createdby/article-metadata-createdby.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-286
https://jira.corp.adobe.com/browse/EXLM-293
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
- After: https://bugfix-exlm-286-article-tag--exlm--adobe-experience-league.hlx.page/docs/blueprints-learn/architecture/customer-journeys/journey-optimizer/journey-optimizer
=> fix: article metadata mobile issues & hide mini-toc section on mobile EXLM-286, EXLM-293

fstab.yaml
Jira ID:
Test URLs:
- After: https://bugfix-fix-fstab--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> update fstab that was mistakenly merged

blocks/embed/embed.css, blocks/embed/embed.scss
Jira ID:
Test URLs:
- After: https://feature-fix-embed-css--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Fixed Embed CSS and SCSS

component-definition.json, component-models.json
Jira ID: [EXLM-74](https://jira.corp.adobe.com/browse/EXLM-74)
Added Icon Block and Icon Card blocks in component-definition.json
Added Icon Card in component-models.json
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en
- After: https://feature-exlm-74-icon-card-block--exlm--adobe-experience-league.hlx.page/en
=> EXLM-74 Icon Card Block

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js, blocks/icon-block/icon-block.scss
Jira ID:
Test URLs:
- After: https://feature-exlm-422-icon-block-m--exlm--adobe-experience-league.hlx.page/en/icon-card
=> icon-card block mobile styles

blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-287
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/docs/experience-manager-guides-learn/tutorials/user-guide/manage-content/authoring-file-management
After: https://bugfix-exlm-287--exlm--adobe-experience-league.hlx.page/docs/experience-manager-guides-learn/tutorials/user-guide/manage-content/authoring-file-management
=> EXLM-287 header changes per design

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-423
Test URLs:
- After: https://feature-exlm-423-icon-block--exlm--adobe-experience-league.hlx.page/en/icon-card
=> tablet and desktop styles for icon-block

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-344
Test URLs:
- After: https://feature-exlm-344-code--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Change Inline code style

head.html
Story : Metadata Processing - Enhance with clue template meta tags
Jira ID: https://jira.corp.adobe.com/browse/EXLM-261
Updated head.html to include the static Clue Template meta tags 
Test URLs:
-After: https://feature-elxm-261-clueTemplate--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM 261 Clue Template

blocks/accordion/accordion.css, blocks/accordion/accordion.scss, blocks/note/note.css, blocks/note/note.scss, blocks/shade-box/shade-box.css, blocks/shade-box/shade-box.scss
Jira ID: 
- https://jira.corp.adobe.com/browse/EXLM-378
- https://jira.corp.adobe.com/browse/EXLM-379
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
After: https://bugfix-exlm-378-accordion--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/test/collapsible-content
=> Bugfix accordion (EXLM-378, 379)

.eslintrc.cjs, .prettierrc, .releaserc.cjs, 404.html, README.md, blocks/badge/badge.js, blocks/cards/cards.js, blocks/code/code.js, blocks/embed/embed.js, blocks/footer/footer.js, blocks/header/header.js, blocks/img-md/img-md.js, blocks/mini-toc/mini-toc.css, blocks/mini-toc/mini-toc.js, blocks/mini-toc/mini-toc.scss, blocks/mini-toc/utils.js, blocks/table/table.js, blocks/tabs/tabs.js, blocks/teaser/teaser.js, build/sass-util.js, package.json, preview.js, sass-compile.js, scripts/delayed.js, scripts/editor-support.js, scripts/lib-franklin.js, scripts/scripts.js, styles/fonts.scss, styles/styles.css, styles/styles.scss
Increase prettier print width to 120 and format all files accordingly
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
After: https://prettier-larger-printwidth--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Prettier Update - Larger Print Width (120)

blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss
Jira ID:
Test URLs:
- After: https://bugfix-exlm-287--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-287 - Additional bugfixes to match design

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-390
Test URLs:
- After: https://bugfix-exlm-390-layout--exlm--adobe-experience-league.hlx.live/docs/authoring-guide-exl/using/authoring/tables
=> Removed extra padding in doc pages for desktop

blocks/columns/columns.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-372
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/column-samples
- After: https://feature-exlm-372-column--exlm--adobe-experience-league.hlx.page/en/column-samples
=> Add Column block

blocks/table/table.css, blocks/table/table.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-411
Test URLs:
- After: https://bugfix-exlm-411-table--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/authoring/tables
=> Table block update styles

component-models.json
Jira ID: [EXLM-393](https://jira.corp.adobe.com/browse/EXLM-393)
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en
After: https://feature-exlm-393--exlm--adobe-experience-league.hlx.page/en
=> EXLM-393 curated card block

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js, blocks/icon-block/icon-block.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-425
Test URLs:
- After: https://feature-exlm-425-icon-block--exlm--adobe-experience-league.hlx.page/en/icon-card
=> updates to handle valid links - icon block

blocks/breadcrumbs/breadcrumbs.css
Updated the Font Color and Params from Global Style.css 
Added the required changes for Line Height and Spacing 
Updated the order according to the standards
Jira ID: https://jira.corp.adobe.com/browse/EXLM-462
Test URLs:
- After: https://bugfix-exlm-462-breadcrumb--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Bugfix EXLM 462 Breadcrumb UI

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js, blocks/icon-block/icon-block.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-473
Test URLs:
- After: https://bugfix-exlm-473-icon-card-ui--exlm--adobe-experience-league.hlx.page/en/icon-card
=> icon block bug fixes

blocks/icon-block/icon-block.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-473
Test URLs:
- After: https://bugfix-exlm-473-icon-card-js--exlm--adobe-experience-league.hlx.page/en/icon-card
=> fix for js error when no link is authored

styles/styles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-465
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/column-samples
- After: https://bugfix-exlm-465-column--exlm--adobe-experience-league.hlx.page/en/column-samples
=> fix free text style in div

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.scss
Jira ID: 473
Test URLs:
- After: https://bugfix-exlm-473-ic-fonts-fix--exlm--adobe-experience-league.hlx.page/en/icon-card
=> font size regression issue fixed

component-models.json
Jira ID: EXLM-11
Test URLs:
- After: https://feature-exlm-11-marquee--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> EXLM-11 Marquee

blocks/columns/columns.css, styles/styles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-465
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/column-samples
- After: https://bugfix-exlm-465-column--exlm--adobe-experience-league.hlx.page/en/column-samples
=> Make free text style specific to column

blocks/header/header.css, blocks/header/header.scss
Jira ID: EXLM-287
Test URLs:
- After: https://bugfix-exlm-287-styles--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> exlm-287-styles

component-models.json
Jira ID: EXLM-485
Added missing (Green) color.
Test URLs:
- After: https://feature-exlm-11-marquee--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> EXLM-485 Marquee block changes

blocks/header/header.css, blocks/header/header.scss
Jira ID: EXLM-287
Test URLs:
- After: https://bugfix-exlm-287-color--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> color-updates

blocks/marquee/marquee.css, blocks/marquee/marquee.js, icons/play.svg, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-415
Test URLs:
- After: https://feature-exlm-11-marquee--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> Marquee CSS

blocks/article-metadata-topics/article-metadata-topics.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-278
Test URLs:
- Before: https://experienceleague.adobe.com/docs/target-dev/developer/client-side/at-js-implementation/at-js/how-atjs-works.html?lang=en
- After: https://feat-exlm278--exlm--adobe-experience-league.hlx.page/docs/target-dev/developer/client-side/at-js-implementation/at-js/how-atjs-works
=> margin fixed

blocks/article-metadata-createdby/article-metadata-createdby.css, blocks/article-metadata-createdby/article-metadata-createdby.js, blocks/article-metadata-createdby/article-metadata-createdby.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-458
Test URLs:
- After: https://bugfix-exlm-458-created-by--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> refactor createdby

blocks/mini-toc/mini-toc.js, styles/styles.css, styles/styles.scss
Jira ID: EXLM-486
Test URLs:
- After: https://feature-EXLM-486-scroll--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> scroll-to-highlight

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.scss
Jira ID: 473
Test URLs:
- After: https://bugfix-exlm-473-ic-width--exlm--adobe-experience-league.hlx.page/en/icon-card
=> enable link to have maximum possible text

blocks/marquee/marquee.js, component-definition.json, component-models.json
Jira ID: EXLM-485 Marquee
Test URLs:
- After: https://feature-exlm-485-marquee--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/marquee-variations-test-page.html?ref=feature-EXLM-485-marquee
=> EXLM-485 Marquee

blocks/header/header.css, blocks/header/header.scss
Fix for Sub nav content z-index
Test URLs:
- After: https://bugfix-sub-nav-z-index--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> sub-nav-conetnt-z-index

blocks/mini-toc/mini-toc.js, blocks/mini-toc/utils.js
Jira ID: EXLM-486
Test URLs:
- After: https://bugfix-exlm-486--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> highlight-to-scroll-tablet

blocks/header/header.css, blocks/header/header.scss
Fix for Sub nav content z-index for mobile view.
Test URLs:
- After: https://bugfix-sub-nav-z-index--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> mobile-sub-nav-content-z-index

blocks/marquee/marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-485
Test URLs:
- After: https://bugfix-exlm-513-marquee--exlm--adobe-experience-league.hlx.page/en/marquee-variations-test-page
=> Change Marquee button styles

blocks/video-embed/video-embed.css, blocks/video-embed/video-embed.js, component-definition.json, component-models.json
Jira ID: EXLM-72
Test URLs:
- After: https://feature-exlm-72-video-block--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
AEM: https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/embed-samples.html?ref=feature-exlm-72-video-block
=> EXLM-72 Video Embed block

head.html, scripts/delayed.js
Jira ID:
Test URLs:
- After: https://target--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Load Target Script - Launch

blocks/article-metadata/article-metadata.js
Jira ID:
Test URLs:
- After: https://feat-lastUpdateFE--exlm--adobe-experience-league.hlx.page/docs/authoring-guide-exl/using/markdown/cheatsheet
=> last update date logic added

scripts/delayed.js
Jira ID:
Test URLs:
- After: https://feature-remove-target--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Remove Launch script as it was merged by mistake

blocks/header/header.css, blocks/header/header.scss
Fix for Sub nav content z-index
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en
After: https://bugfix-sub-nav-z-index--exlm--adobe-experience-league.hlx.page/en
=> sub-nav-content-z-index

scripts/feedback/feedback.css
Jira ID: 600
Test URLs:
- After: https://bugfix-exlm-600-feedback-ui--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Feedback bar ui issues fixed

blocks/secondary-search/secondary-search.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-601
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/secondary-search-test-page 
- After: https://bugfix-exlm-601-search--exlm--adobe-experience-league.hlx.page/en/secondary-search-test-page
=> Secondary Search bug fix

blocks/media/media.css, component-definition.json, component-models.json
- Some fontsize and font color ajustments based on feedback by QA
- UE editor should use 'Image Alignment' and not 'Text Alignment'
Test URLs:
- After: https://media-fix-2--exlm--adobe-experience-league.hlx.page/en/media
=> fix fonts colors and sizes

blocks/media/media.css
fix primary button color
Jira ID:
Test URLs:
- After: https://mediafix3--exlm--adobe-experience-league.hlx.page/en/media
=> Media: fix primary button colors

scripts/feedback/feedback.css
Jira ID: 600
Test URLs:
- After: https://bugfix-exlm-600-feedback-minor--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> minor alignment fix - feedback bar

blocks/media/media.css
- removed unneeded css
- improved responsive design for max and min widths
Test URLs:
- After: https://mediafix5--exlm--adobe-experience-league.hlx.page/en/media
=> Media: css cleanup, improve responsive design

scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-adls-adaptor.js, scripts/browse-card/browse-cards-delegate.js, scripts/data-service/adls-data-service.js, scripts/session-keys.js, scripts/urls.js
EXLM 483 ADLS Integration
Instruction Led Courses for Curated Cards API Integration 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-483
Test URLs:
- After: https://feature-exlm-483-adl--exlm--adobe-experience-league.hlx.live/en/curated-cards-adls
=> EXLM 483 ADLS Integration

scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-delegate.js, scripts/data-model/browse-cards-model.js, scripts/data-service/coveo/coveo-data-service.js, scripts/urls.js
Jira ID:https://jira.corp.adobe.com/browse/EXLM-595
Test URLs:
- After: https://feature-exlm-595-comm--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> EXLM 595 Community Integration Change

blocks/curated-cards/curated-cards.js, component-definition.json, component-models.json
Jira ID: [EXLM-8](https://jira.corp.adobe.com/browse/EXLM-8) [EXLM-17](https://jira.corp.adobe.com/browse/EXLM-17)
Test URLs:
- After: https://feature-EXLM-8-17--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/authorable-cards-block.html?ref=feature-EXLM-8-17
=> EXLM-8 EXLM-17 EXLM-59 Authorable Card, Browse Filters and Curated Cards Block

.gitignore
Jira ID: EXLM-XXXX
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/
- After: https://bugfix-gitgnore-additions--exlm--rogerblanton.hlx.page/
=> Trivial: adding aio and env to gitignore

component-models.json
Jira ID: EXLM-59
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
After: https://feature-EXLM-59-UE--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/curated-cards-single.html?ref=feature-EXLM-59-UE
=> EXLM-59 Added tag-picker

blocks/header/header.js, scripts/data-service/coveo/coveo-token-service.js, scripts/data-service/profile-service.js, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://feature-better-ims-loading--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> better ims loading and dependency on window object.

component-models.json
Jira ID: EXLM-59
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/curated-cards-single
After: https://feature-exlm-59-ue--exlm--adobe-experience-league.hlx.page/en/curated-cards-single
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/curated-cards-single.html?ref=feature-EXLM-59-UE
=> Updated curated cards fields

blocks/curated-cards/curated-cards.css, scripts/browse-card/browse-card.css
Card styling and scrolling CSS
Jira ID: https://jira.corp.adobe.com/browse/EXLM-620
Test URLs:
- After:  https://feature-exlm-607--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> EXLM-607/Sub task : EXLM-620 - Card styling and scrolling CSS

component-models.json
Jira ID: EXLM-59
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
After: https://feature-exlm-59-ue--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/curated-cards-single.html?ref=feature-EXLM-59-UE
=> EXLM-59 Curated cards

blocks/curated-cards/curated-cards.js, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card-placeholder.js, scripts/browse-card/browse-cards-delegate.js, styles/styles.css, styles/styles.scss
EXLM-664-Placeholder code
Jira ID: https://jira.corp.adobe.com/browse/EXLM-664
Test URLs:
- After: https://feature-exlm-664-loader--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> EXLM-664-Placeholder code

blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js
Jira ID: EXLM-607
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/live-events-cards
After: https://fix-cards-tooltip--exlm--adobe-experience-league.hlx.live/en/live-events-cards
=> Tooltip icon for cards

blocks/curated-cards/curated-cards.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js
Jira ID: EXLM-59
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/curated-cards
After: https://feature-exlm-596-coveo-fields--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> Disabling Lessons count

component-models.json
Jira ID: EXLM-17
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse-filters
- After: https://feature-exlm-17--exlm--adobe-experience-league.hlx.live/en/browse-filters
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse-filters.html?ref=feature-exlm-17
=> EXLM-17 Browse filters

blocks/events-cards/events-cards.js, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-live-events-adaptor.js, scripts/data-model/browse-cards-model.js
Jira ID: EXLM-607
Enhancements:
1. Added filter for past events and removing them.
2. Displaying "time" key value from the events JSON for cards date and time.
3. Sorting the cards by "time" key.
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/live-events-cards
After: https://feature-exlm-607-events-cards--exlm--adobe-experience-league.hlx.live/en/live-events-cards
=> EXLM-607 Events cards

blocks/featured-cards/featured-cards-constants.js, blocks/featured-cards/featured-cards.css, blocks/featured-cards/featured-cards.js, scripts/browse-card/browse-cards-constants.js, scripts/data-service/coveo/coveo-data-service.js, scripts/data-service/solutions-data-service.js, scripts/session-keys.js, scripts/urls.js
Featured Card Block
Jira ID:https://jira.corp.adobe.com/browse/EXLM-12
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/featured-card-test-main
- After: https://feature-exlm-12-feattest--exlm--adobe-experience-league.hlx.live/en/featured-card-test-main
=> EXLM 12 Featured Card Block

blocks/authorable-card/authorable-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-8
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
- After: https://bugfix-exlm-8-authorable-cards--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
=> Fix links not appearing in UE.

blocks/marquee/marquee.css, blocks/teaser/teaser.css
Fixes based on QA feed back for teaser and marquee when used on browse page with rails.
Jira ID:
Test URLs:
- After: https://exlm-751--exlm--adobe-experience-league.hlx.page/en/browse/acrobat
=> Exlm-751: fixes for teaser and marquee when on browse page 

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js
Jira ID: EXLM-717
Test URLs:
- After: https://feature-exlm-717--exlm--adobe-experience-league.hlx.live/en/browse
=> hide-sorting-when-no-result

scripts/browse-card/browse-cards-constants.js
Fixed the ADLS Label for ADLS Component 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-742
Test URLs:
- After: https://feature-exlm-742-adls--exlm--adobe-experience-league.hlx.live/en/browse
-
=> ADLS Label Fix

scripts/browse-card/browse-cards-constants.js
Just reordered the roles in Constants File
Jira ID:https://jira.corp.adobe.com/browse/EXLM-742
Test URLs:
- After: https://feature-exlm-742-adls--exlm--adobe-experience-league.hlx.live/en/browse
=> Roles Order Change 

scripts/browse-card/browse-cards-constants.js
Changed the Default Roles Option Value 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-742
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse
After: https://feature-exlm-742-adls--exlm--adobe-experience-league.hlx.live/en/browse
=> Roles Default Value Change

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, scripts/browse-card/browse-card.js, scripts/coveo-headless/index.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-766
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse 
- After: https://bugfix-exlm-766--exlm--adobe-experience-league.hlx.live/en/browse
=> Browse results updates

scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-block.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-764
Test URLs:
- After: https://bugfix-exlm-764-curated-card-ui--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Bugfix/exlm 764 curated card UI

scripts/browse-card/browse-card.css
Update CSS class name for troubleshooting card as per JS
Jira ID: https://jira.corp.adobe.com/browse/EXLM-742
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
After: https://troubleshooting-card-name-change--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> troubleshooting-card-name-change

blocks/media/media.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-736
Test URLs:
- After: https://uat-exlm-736-media--exlm--adobe-experience-league.hlx.page/en/media
=> Media block layout fix

scripts/browse-card/browse-cards-constants.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-764
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/curated-cards
- After: https://feat-exlm768--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> EXLM-764 On Event Label Change

scripts/browse-card/browse-card.css, styles/styles.css
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/featuredcardtest
- After: https://exlm-764-community-tag-color--exlm--adobe-experience-league.hlx.live/en/featuredcardtest
=> Exlm 764 community tag color

component-definition.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-712
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/text-test
- After: https://feat-exlm712--exlm--adobe-experience-league.hlx.page/en/text-test
=> placeholder text added for text component

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, blocks/header/header.js, blocks/mini-toc/mini-toc.js, blocks/mini-toc/utils.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/coveo-headless/index.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-606 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse#f-el_type=Documentation
- After: https://feature-exlm-606--exlm--adobe-experience-league.hlx.page/en/browse#f-el_type=Documentation
=> feat: browse filters pagination impl exlm-606

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-837
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Documentation
- After: https://bugfix-exlm-837--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Documentation
=> fix: avoid scroll on filter update

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, scripts/coveo-headless/index.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-770
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Documentation
- After: https://bugfix-exlm-770--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Documentation
=> fix: browse filters result page updates exlm-770

blocks/authorable-card/authorable-card.js, scripts/browse-card/browse-cards-adls-adaptor.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-live-events-adaptor.js
Jira ID:
Test URLs:
- After: https://bugfix-author-instance-api-calls--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> UE Placeholder Fix

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, blocks/footer/footer.css, blocks/footer/footer.scss, blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.scss, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card-placeholder.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-735
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/test-product
- After: https://exlm-735-animation-browse-card--exlm--adobe-experience-league.hlx.live/en/browse/test-product
=> Exlm 735 animation browse card

blocks/carousel/carousel.js, blocks/teaser/teaser.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-734
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/carousel
- After: https://uat-exlm-374-teaser--exlm--adobe-experience-league.hlx.live/en/carousel
=> Carousel UAT fixes

blocks/browse-topics/browse-topics.js, component-definition.json, component-models.json
Jira ID: EXLM-793
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/test-product
- After: https://feature-exlm-793--exlm--adobe-experience-league.hlx.live/en/browse/test-product
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/test-product.html?ref=feature-exlm-793
=> EXLM-793 Browse Topics block

helix-query.yaml
Jira ID: EXLM-18
Added another indexing logic for browse all pages.
=> Updated yaml to index only browse pages

blocks/browse-topics/browse-topics.js, component-models.json
Jira ID: EXLM-793
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/acrobat
After: https://feature-exlm-793--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/acrobat.html?ref=feature-exlm-793
=> EXLM-793 Updated tags path

scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-delegate.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-761-multi-product--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Display Product

blocks/authorable-card/authorable-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-741 
Test URLs:
- Before:  https://main--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
- After: https://bugfix-exlm-741-authorable-card--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
=> Bugfix Authorable cards block UE

component-definition.json
Jira ID: EXLM-850
Test URLs:
- After: https://feature-exlm-850--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/acrobat.html?ref=feature-exlm-850
=> updated icon card with default content

scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-delegate.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-761-multi-product--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Browse Page and Curated Cards Fix

blocks/columns/columns.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-487--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/acrobat.html?ref=bugfix-exlm-487
=> Handled case of button inside column

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-839
Test URLs:
- After: https://bugfix-exlm-839-browse-filters--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Tutorial
=> Browser Filters Icon bug fix

blocks/authorable-card/authorable-card.js, blocks/browse-filters/browse-filters.css, scripts/browse-card/browse-card-placeholder.css
Placeholder fixes
Jira ID: https://jira.corp.adobe.com/browse/EXLM-845
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse
After: https://exlm-845-plain-text-appearing--exlm--adobe-experience-league.hlx.live/en/browse#f-el_type=Tutorial
=> Placeholder fixes

blocks/featured-cards/featured-cards.js, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-cards-block.css
fixes done for font style and color
Jira ID:
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/featuredcardtest
After: https://exlm-847-feature-card-font-style--exlm--adobe-experience-league.hlx.live/en/featuredcardtest
=> fixes done for font style and color

blocks/icon-block/icon-block.css
Jira ID:
Test URLs:
- After: https://feature-exlm-851--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/acrobat.html?ref=feature-exlm-851
=> Removed angle from anchor

blocks/featured-cards/featured-cards.js
Make shimmer visible on the Feature card page while changing the dropdown values.
Jira ID:
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/featuredcardtest
After: https://exlm-847-feature-card-font-style--exlm--adobe-experience-league.hlx.live/en/featuredcardtest
=> Feature card shimmer on dropdown value change

blocks/authorable-card/authorable-card.js
making shimmer hide in Authorable card
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/authorable-cards-block
- After: https://exlm-847-feature-card-font-style--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
=> making shimmer hide in Authorable card

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
- After: https://bugfix-exlm-770-search-results--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
=> EXLM-770 - Search Results Fix

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js
Fixing visibility for card
Jira ID: https://jira.corp.adobe.com/browse/EXLM-845
Test URLs:
- After: https://exlm-845-plain-text-appearing--exlm--adobe-experience-league.hlx.live/en/browse
=> Fixing visibility for card

blocks/browse-topics/browse-topics.css, blocks/browse-topics/browse-topics.js, scripts/coveo-headless/index.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-341
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
- After: https://feat-exlm-341-browse-topics--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
=> feat: browse topics selection impl EXLM-341

blocks/browse-rail/browse-rail.js
Jira ID: EXLM-18
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/experience-manager
- After: https://feature-exlm-18--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> EXLM-18 Removed Topics from left rail

scripts/browse-card/browse-card.js
Adding views and replies tag only for community
Jira ID:
Test URLs:
- After: https://exlm-840-community-view-reply--exlm--adobe-experience-league.hlx.page/en/curated-cards
=> Adding views and replies tag only for community

blocks/browse-topics/browse-topics.js
Jira ID: EXLM-885
Test URLs:
- After: https://bugfix-exlm-885--exlm--adobe-experience-league.hlx.live/en/browse
=> fixed undefined tags

blocks/tabbed-cards/tabbed-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-874
Fixed All the tab selections should remain as it is when changes are made in other blocks
Fixed View all community post link should open in a new tab (External Links)
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/tabtest
- After: https://feature-exlm-874-tabbed-card--exlm--adobe-experience-league.hlx.live/en/tabtest
=> EXLM 874 Tabbbed Cards

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-871
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
- After: https://bugfix-exlm-871-cards--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
=> Fix undefined links in cards

blocks/browse-rail/browse-rail.css, blocks/featured-cards/featured-cards.css, scripts/browse-card/browse-card-placeholder.css
Fixed width for desktop screen and hide left nav for tablet and mobile.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-848
Test URLs:
- After: https://EXLM-848-feature-card-width--exlm--adobe-experience-league.hlx.live/en/browse
=> Fixed width for desktop screen and hide left nav for tablet and mobile.

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/browse-filters/browse-filters.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.js, blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js
Updated Browse Cards Js to include No Results method and Browse Cards Css for corresponding Styling
Updated the Tabbed Block to Include No Results generic Card Description 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-874
https://jira.corp.adobe.com/browse/EXLM-19
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/tabtest
- After: - https://feature-exlm-874-tabbed-card--exlm--adobe-experience-league.hlx.page/en/tabtest
**When There is Error in fetching data ot No Results from API**
**When nothing is authored in UE**
=> EXLM 19 Tabbed Card Block No Results

blocks/tabbed-cards/tabbed-cards.css
Updated the Font Size for Tab Elements
Jira ID:https://jira.corp.adobe.com/browse/EXLM-874-
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/tabtest
After: - https://feature-exlm-874-tabbed-card--exlm--adobe-experience-league.hlx.page/en/tabtest
=> EXLM 874 CSS Font Size Tabbed Block

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js, component-definition.json, component-models.json
Jira ID: EXLM-852
Test URLs:
- After: https://feature-exlm-852--exlm--adobe-experience-league.hlx.live/en/browse
=> fixed icon card in case if the links are not authored

component-definition.json, component-filters.json
adds filtering for components.
Jira ID: https://jira.corp.adobe.com/browse/SITES-16556
Author URL:
https://experience.adobe.com/#/@amc/aem/editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/tab-group-test-page.html?ref=allowed-filters
=> SITES-16556: add component filters

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-911
Test URLs:
- Before:  https://main--exlm--adobe-experience-league.hlx.page/en/browse
- After: https://fix-exlm-911--exlm--adobe-experience-league.hlx.page/en/browse
=> fix: no results ui update

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-770
Test URLs:
- After: https://fix-exlm-770-browse--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: browse results updates

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/browse-filters/browse-filters.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.js, blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card-placeholder.js, scripts/browse-card/browse-cards-constants.js, scripts/browse-card/browse-cards-delegate.js
Jira ID:
Test URLs:
- After: https://exlm-881-community-exclude-user--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> Exlm 881 community exclude user and fixes applied for shimmer

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.css, blocks/featured-cards/featured-cards.js, blocks/tabbed-cards/tabbed-cards.js
Jira ID:
Test URLs:
- After: https://exlm-881-community-exclude-user--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> Exlm 881 community exclude user

blocks/curated-cards/curated-cards.css, blocks/featured-cards/featured-cards.js, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js
Remove cursor pointer
Jira ID:
Test URLs:
- After: https://comunity-tag-cursor--exlm--adobe-experience-league.hlx.live/en/curated-cards
=> Remove cursor pointer

blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-913
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
- After: https://fix-exlm-913--exlm--adobe-experience-league.hlx.live/en/browse/acrobat
=> fix: browse topics

blocks/browse-rail/browse-rail.css, blocks/browse-rail/browse-rail.js
Jira ID: EXLM-18
Test URLs:
- After: https://bugfix-left-nav--exlm--adobe-experience-league.hlx.page/en/browse
=> View more and view less for Browse All

blocks/carousel/carousel.js, blocks/featured-cards/featured-cards.js, blocks/teaser/teaser.js, scripts/scripts.js
Test URLs:
- After: https://bugfix-fix-undefined-errors--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Fix undefined errors impacting some blocks

styles/styles.css, styles/styles.scss
Jira ID: EXLM-995
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/technotes/client-hints
- After: https://bugfix-exlm-995--exlm--adobe-experience-league.hlx.live/en/docs/analytics/technotes/client-hints
=> TOC fixes for mobile and tablet

scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-block.css
Jira ID: EXLM-983 & 949
Test URLs:
- After: https://bugfix-EXLM-983-id-tooltip--exlm--adobe-experience-league.hlx.live/en/browse
=> id-tooltip

blocks/toc/toc.js, scripts/data-service/toc-data-service.js
Jira ID: EXLM-176
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/de/docs/experience-manager-cloud-service/content/assets/accessibility
- After: https://feature-exlm-176-toc--exlm--adobe-experience-league.hlx.live/de/docs/experience-manager-cloud-service/content/assets/accessibility
https://feature-exlm-176-toc--exlm--adobe-experience-league.hlx.live/en/docs/analytics/technotes/client-hints
=> EXLM-176 TOC for translated pages

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-913
Test URLs:
- Before:  https://main--exlm--adobe-experience-league.hlx.live/en/browse
- After: https://bugfix-exlm-913--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: browse filter and topics

.github/pull_request_template.md, blocks/authorable-card/article-data-adapter.js, scripts/analytics/lib-analytics-orig.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/scripts.js
Jira ID: EXLM-967 
Test URLs:
- After: https://feature-doc-url-rewrite--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-967 - Rewrite Language URLs

blocks/browse-filters/browse-filters.js, blocks/tabbed-cards/tabbed-cards.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/authoring-guide-exl/using/markdown/cheatsheet
- After: https://console-errors--exlm--adobe-experience-league.hlx.live/en/docs/authoring-guide-exl/using/markdown/cheatsheet
=> Fixed Unexpected console statement

blocks/cloud-solutions/cloud-solutions.css, blocks/guides-list/guides-list.css, blocks/related-resources/related-resources.css, blocks/tutorial-tiles/tutorial-tiles.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-889
Test URLs:
- Before: https://main-ui--exlm--adobe-experience-league.hlx.live/en/docs
- After: https://fix-exlm-889-ui--exlm--adobe-experience-league.hlx.live/en/docs
=> fix: solutions page css updates exlm-889

scripts/browse-card/browse-card.js
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1001
Updated the type for Recommended Courses Block so that the correct class name can be appended to the content div to fix the styling issue
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/rec
- After: https://bugfix-exlm-100-rc--exlm--adobe-experience-league.hlx.live/en/rec
=> EXLM 1001 RC Style Changes

scripts/analytics/lib-analytics.js, scripts/bookmark/bookmark.js, scripts/copy-link/copy-link.js, scripts/feedback/feedback.js
Analytics : asset interaction events for bookmark, copy, & feedback thumbs up, down.
Test URLs:
- After: https://feature-exlm-949-asset-analytics--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-949: Analytics (EXLM-467) asset interaction events

blocks/browse-breadcrumb/browse-breadcrumb.js, blocks/browse-rail/browse-rail.js, helix-query.yaml, helix-sitemap.yaml, paths.yaml
Jira ID:
Test URLs:
- After: https://feature-sitemaps--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Sitemaps U& Indices updates -  Language based

blocks/sign-up/sign-up.js, component-definition.json, component-models.json
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-897
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/signup 
- After: https://feature-exlm-897-sign-up--exlm--adobe-experience-league.hlx.live/en/signup
=> Sign Up block Update

blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss, scripts/language.js, styles/language.css
Test URLs:
- After: https://feature-language-changes--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Language Selector for both Header and Footer

blocks/header/header.css, blocks/header/header.scss
Jira ID: EXLM-1026
Test URLs:
- After: https://bugfix-exlm-1026-scss--exlm--adobe-experience-league.hlx.live/en/browse
=> scss-inclusion

scripts/analytics/lib-analytics.js
Jira ID: EXLM-954
Test URLs: 
- After: https://bugfix-exlm-954-pdf-download--exlm--rogerblanton.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> trivial: fixing link click for download

scripts/browse-card/browse-card.js
Test URLs:
- After: https://feature-exlm-949-copylink-id--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> exlm-949: articleId always present for both public and signed-in users

scripts/delayed.js, scripts/language.js
Jira ID:
Test URLs:
- After: https://fix-load-css-base--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> fix: loadCSS relative to code base path

scripts/scripts.js
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/signup
- After: https://feature-do-nott-load-page--exlm--adobe-experience-league.hlx.page/en/signup
=> POC for existing EXL pages - do not load pages if explicitly set

blocks/toc/toc.css
Fixes for font differences
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1019
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/integrations-learn/experience-cloud/integrations-between-applications/experience-manager/experience-manager-workfront
After: https://exlm-1019-font-changes-toc--exlm--adobe-experience-league.hlx.live/en/docs/integrations-learn/experience-cloud/integrations-between-applications/experience-manager/experience-manager-workfront
=> Update arrow color and plus minus weight

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-913
Test URLs:
- After: https://bugfix-exlm-913-topics--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: multiple browse topics filter issue exlm-913

styles/styles.css, styles/styles.scss
Fixes for font differences
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1036
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/marketo-measure/using/home
After: https://exlm-1036-pipe-dot-color-toc--exlm--adobe-experience-league.hlx.live/en/docs/marketo-measure/using/home
=> TOC pipe and dot color

component-filters.json, scripts/editor-support.js
This configures the default rte for text components with what is allowed and possible with hlx. 
It also adds an editor support script, which wraps consecutive paragraphs in a wrapper div to be compatible with the Universal Editor for now.
=> EXLM-387: RTE

blocks/article-metadata-topics/article-metadata-topics.css, blocks/icon-block/icon-block.css, scripts/rails/rails.css, scripts/rails/rails.js, scripts/rails/rails.scss, styles/styles.css, styles/styles.scss
There will be more to come here but this is a good first step
Jira ID: n/a
Test URLs:
will add later
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/authoring-guide-exl/using/markdown/cheatsheet
- After: https://css-cleanup--exlm--adobe-experience-league.hlx.live/en/docs/authoring-guide-exl/using/markdown/cheatsheet
=> css cleanup and refactoring to support allowing more than one content section

blocks/authorable-card/authorable-card.js, blocks/browse-breadcrumb/browse-breadcrumb.js, blocks/browse-filters/browse-filters.js, blocks/browse-rail/browse-rail.js, blocks/doc-actions/doc-actions.js, blocks/tabbed-cards/tabbed-cards.js, blocks/toc/toc.js, paths.yaml, scripts/bookmark/bookmark.js, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-adls-adaptor.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-live-events-adaptor.js, scripts/browse-card/browse-cards-paths-adaptor.js, scripts/feedback/feedback.js, scripts/language.js, scripts/scripts.js
Test URLs:
- After: https://feature-language-placeholders--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Language based Placeholders

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://feature-language-placeholders--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Remove Debug Log

scripts/scripts.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/ko/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feature-placeholders--exlm--adobe-experience-league.hlx.live/ko/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Fallback logic in case placeholders for specified Language is 404

404.html
Jira ID:
Test URLs:
- After: https://feature-404--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> 404 pages - match existing EXL 404 page

blocks/article-metadata/article-metadata.js, blocks/mini-toc/mini-toc.js, blocks/tutorial-tiles/tutorial-tiles.js, scripts/scripts.js
Jira ID: EXLM-1049
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/technotes/client-hints
- After: https://bugfix-exlm-1049--exlm--adobe-experience-league.hlx.live/en/docs/analytics/technotes/client-hints
=> EXLM-1049 Added static labels in placeholders

blocks/tutorial-list/tutorial-list.js
Jira ID: EXLM-860
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics
- After: https://feature-exlm-860--exlm--adobe-experience-league.hlx.live/en/docs/analytics
=> EXLM-860 Static content in placeholders

blocks/guides-list/guides-list.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-860
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/fr/docs/commerce
- After: https://bugfix-exlm-860-fr-css--exlm--adobe-experience-league.hlx.live/fr/docs/commerce
=> fix: handle extra ul li structure for fr/de locale exlm-860

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/recommended-courses/recommended-courses.js, blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card-tooltip.js, scripts/browse-card/browse-cards-block.css
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1085-tooltip-fix--exlm--adobe-experience-league.hlx.live/en/browse
=> Tooltip Fix

blocks/featured-cards/featured-cards.js, component-definition.json, component-models.json, scripts/browse-card/browse-cards-delegate.js
Added Keyword and Sort Options for Featured Card 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1044?workflowName=EXLM+Default+Workflow&stepId=2
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse/test-product
- After: https://feature-exlm-1044-featured--exlm--adobe-experience-league.hlx.live/en/browse/test-product
=> EXLM 1044 Featured Card

blocks/doc-actions/doc-actions.js
Jira ID: EXLM-1072
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
- After: https://bugfix-exlm-1072-bookmark--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
=> EXLM-484/1072: click bookmark on desktop does not work.

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1005
Test URLs:
- After: https://feat-exlm-1005--exlm--adobe-experience-league.hlx.live/en/browse
=> feat: adjust page layout exlm-1005

blocks/featured-cards/featured-cards.css, blocks/footer/footer.css, blocks/header/header.css, blocks/header/header.scss, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1053
Test URLs:
- After: https://bugfix-exlm-1053--exlm--adobe-experience-league.hlx.live
=> fix: ui spacing issues, alignments & fonts exlm-1053

blocks/doc-actions/doc-actions.css
Jira ID: EXLM-1076
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/analytics/release-notes/releases
- After: https://bugfix-exlm-1076--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
=> Bugfix/exlm 1076  translation widget toggle checkbox css issue 

blocks/badge/badge.css, blocks/badge/badge.js, blocks/badge/badge.scss
Jira ID:  EXLM-1092
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/campaign-classic/using/getting-started/starting-with-adobe-campaign/faq/tutorials
- After: https://bugfix-exlm-1092--exlm--adobe-experience-league.hlx.live/en/docs/campaign-classic/using/getting-started/starting-with-adobe-campaign/faq/tutorials
=> EXLM-1092 Badge UI issues

scripts/editor-support.js
Reverts adobe-experience-league/exlm#462
=> Revert "fix: adapt breaking change in UE event"

scripts/feedback/feedback.js
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
- After: https://bugfix-exlm-949--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
=> EXLM-949: Feedback analytics.

blocks/doc-actions/doc-actions.js
Jira ID: EXLM-1073
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
- After: https://feature-exlm-1073--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
=> EXLM-1073: Translation Feedback radio analytics data layer events.

scripts/bookmark/bookmark.js, scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1057 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/curated-cards-single 
- After: https://feature-exlm-1057-clickable-card--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Change Cards to Clickable cards

robots.txt
Test URLs:
- After: https://robots--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> add initial robots.txt - blocks everything

scripts/scripts.js
Test URLs:
- After: https://feature-ims-prod-client-exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Use ims prod client in prod

blocks/featured-cards/featured-cards.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1053
Test URLs:
- After: https://bugfix-exlm-1053-gap--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: update margin values to adjust the gap exlm-1053

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1038
Test URLs:
- After: https://bugfix-exlm-1038--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: show no filters layer after hitting search input exlm-1038

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1114
Test URLs:
After: https://bugfix-exlm-1114--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: ui issues on browse all page exlm-1114

blocks/sign-up/sign-up.js, scripts/editor-support.js
Test URLs:
- After: https://bugfix-format--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Prettier format

blocks/carousel/carousel.css, blocks/featured-cards/featured-cards.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1053
Test URLs:
After: https://bugifx-exlm-1053-gap--exlm--adobe-experience-league.hlx.live/
=> fix: spacing issues between sections in homepage exlm-1053

blocks/header/header.js, scripts/scripts.js, scripts/urls.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/de/browse
- After: https://feature-exlm-1120-language--exlm--adobe-experience-league.hlx.live/de/browse
=> Multi-Language Support

blocks/header/header.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1111--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Fix Page Header items not opening on hover

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1114
Test URLs:
After: https://bugfix-exlm-1114-css--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: css gaps for larger screen resolutions exlm-1114

blocks/carousel/carousel.css, blocks/doc-actions/doc-actions.css, blocks/doc-actions/doc-actions.js, blocks/toc/toc.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1078 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/certification/program/technical-certifications/aw/aw-overview
- After: https://bugfix-exlm-1078-mt--exlm--adobe-experience-league.hlx.live/en/docs/certification/program/technical-certifications/aw/aw-overview
=> Machine Translation Issues Fix

scripts/scripts.js
Jira ID: EXLM-1129
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics
- After: https://feature-exlm-1129--exlm--adobe-experience-league.hlx.live/en/docs/analytics
=> EXLM-1129 Hide the Feedback Component on landing pages

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1012
Test URLs:
After: https://feature-exlm-1012--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> feat: multi-level topics selection impl exlm-1012

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1121
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/analytics
After: https://bugfix-exlm-1121--exlm--adobe-experience-league.hlx.live/en/docs/analytics
=> fix: layout overlapping issue for docs page with rails closed exlm-1121

blocks/browse-filters/browse-filters.js, scripts/scripts.js, styles/styles.css, styles/styles.scss
Test URLs:
After: https://browse-graphic-display--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: show graphic on browse pages once the block is loaded

scripts/urls.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1042
Test URLs:
- After: https://feature-adls-cors-test--exlm--adobe-experience-league.hlx.live/en/browse
=> ADLS URL to test CORS issue

paths.json, paths.yaml
Jira ID: EXLM-1075
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feature-exlm-1075--exlm--adobe-experience-league.hlx.live/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-1075 Added qualtrics json

blocks/browse-filters/browse-filter-utils.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1086-dropdown--exlm--adobe-experience-league.hlx.page/en/browse
=> Dropdown Title and Description Changes

scripts/browse-card/browse-cards-adls-adaptor.js, scripts/urls.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1042
Updated back the endpoint of ADLS 
Test URLs:
- After: https://feature-exlm-1042-adls-cors--exlm--adobe-experience-league.hlx.live
=> EXLM 1042 ADLS CORS Issue

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1131
Test URLs:
After: https://bugfix-exlm-1131--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> fix: css gap & icon issue in browse page exlm-1131

blocks/header/header.js
See: https://github.com/adobe-experience-league/exlm-converter/pull/193 to see changes to header fragment.
This PR hides all nav-items whose links have `auth-only` attribute - defined in the header fragment
Test URLs:
- After: https://feature-auth-only-links--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Show auth-only links when user is authenticated only

blocks/featured-cards/featured-cards.js
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1044
Updated the code to handle duplicate results for multiple content types
Test URLs:
- After: https://feature-exlm-1044-featured-card--exlm--adobe-experience-league.hlx.live
=> EXLM 1044 Featured Card UAT Change Request

blocks/browse-rail/browse-rail-utils.js
Jira ID: EXLM-1138
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
- After: https://bugfix-exlm-1138--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> EXLM-1138 Updated code to handle correct categorization of sub-pages

blocks/featured-cards/featured-cards.js, scripts/scripts.js
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1044
Converted Content Type to Pascal Case
Test URLs:
After: https://feature-exlm-1044-featured-card--exlm--adobe-experience-league.hlx.live/
=> EXLM 1044 Featured Card UAT Change Req

paths.json, paths.yaml
=> fix: remove json extension from configuration

blocks/staff-picks/staff-picks.css, blocks/table/table.css, blocks/table/table.scss
To be merged after https://github.com/adobe-experience-league/exlm-converter/pull/196
Jira ID: EXLM-1147
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/platform-learn/tutorials/overview
- After: https://feature-EXLM-1147--exlm--adobe-experience-league.hlx.live/en/docs/platform-learn/tutorials/overview
=> EXLM-1147 Staff-picks block

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js, scripts/coveo-headless/index.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1012
Test URLs:
After: https://feature-exlm-1012-solution--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> feat: solution filter impl on browse pages exlm-1012

blocks/browse-rail/browse-rail.js
Jira ID: EXLM-1054 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/workfront
- After: https://bugfix-exlm-1054--exlm--adobe-experience-league.hlx.live/en/browse/workfront
=> EXLM-1054 Display all products when product pages do not have sub-pages

component-models.json
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1042
Updated Component Model for Solutions Names in ADLS Cards According to the latest learning. adobe.com Site 
Test URLs:
- After: https://feature-exlm-1042-adls-cors--exlm--adobe-experience-league.hlx.live
=> EXLM 1042 Solutions Update

blocks/featured-cards/featured-cards.js
Test URLs:
- After: https://feature-exlm-uat-fixes--exlm--adobe-experience-league.hlx.live
=> Moved Text to Placeholders for Translation

scripts/gainsight/gainsight.js
=> Updated gainsight language map

scripts/scripts.js
Jira ID: EXLM-1139
Test URLs:
- After: https://feature-EXLM-1139-staging-prod-containers--exlm--rogerblanton.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> adding logic to toggle launch containers

scripts/feedback/feedback.js
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/analytics/release-notes/releases
- After: https://bugfix-exlm-949-feedback--exlm--adobe-experience-league.hlx.live/en/docs/analytics/release-notes/releases
=> Bugfix/EXLM-949: Modified interaction type per AA review.

scripts/analytics/lib-analytics.js, scripts/scripts.js
Jira ID:
Test URLs:
- After: https://bugfix-ims-api-for-analytics--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Analytics - User Data from profile service

blocks/marquee/marquee.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1008
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/testpage
- After: https://exlm-1008-2--exlm--adobe-experience-league.hlx.live/en/browse/testpage
=> exlm-1008: Ractivate accidently commented css value

blocks/browse-filters/browse-filters.js, scripts/coveo-headless/index.js, scripts/editor-support.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1152
Test URLs:
After: https://bugfix-exlm-1152--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> fix: change the typeField to contentType to match PROD behaviour EXLM-1152

blocks/browse-filters/browse-filters.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1152
Test URLs:
After: https://bugfix-exlm-1152-1--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> fix: community cards width

blocks/browse-rail/browse-rail.js, blocks/doc-actions/doc-actions.js, blocks/tabbed-cards/tabbed-cards.js, scripts/urls.js
Moved links from placeholders to urls.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1049
Test URLs:
- After: https://placeholder-urls--exlm--adobe-experience-league.hlx.live/
=> EXLM-1049 Moved links from placeholders to urls.js

scripts/urls.js
Jira ID:
Test URLs:
- After: https://placeholder-urls--exlm--adobe-experience-league.hlx.live
=> Updated view all courses link for tabbed cards

scripts/bookmark/bookmark.js
Test URLs:
- After: https://bugfix-exlm-949-bookmark--exlm--adobe-experience-league.hlx.live
=> EXLM-949: Modified AA interaction types per Sidd's review.

paths.json, paths.yaml
Updated the path.yaml to include Featured Card Product List 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1141
Test URLs:
- After: https://feature-exlm-1141-featured--exlm--adobe-experience-league.hlx.live
=> EXLM 1141 Featured Card Product List

blocks/featured-cards/featured-cards.css, blocks/featured-cards/featured-cards.js, scripts/dropdown/dropdown.css, scripts/dropdown/dropdown.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1087
Test URLs:
- After: https://feature-exlm-1087-featured--exlm--adobe-experience-league.hlx.live
=> Featured card filters

blocks/img-md/img-md.js
Jira ID: https://jira.corp.adobe.com/browse/UGP-10277
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/cloud-service/caching/cdn-cache-hit-ratio-analysis
After: https://bugfix-ugp-10277--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/cloud-service/caching/cdn-cache-hit-ratio-analysis
=> fix: set img width to only non-zoomable images ugp-10277

scripts/urls.js
Jira ID:
Test URLs:
- After: https://placeholder-urls--exlm--adobe-experience-league.hlx.live/
=> Updated links for tabbed cards

scripts/search/search.js
Handled language-specific search redirection.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/de/docs
- After: https://search-issue--exlm--adobe-experience-league.hlx.live/de/docs
=> Language specific search redirection

blocks/browse-rail/browse-rail.css, blocks/browse-rail/browse-rail.js
Jira ID: https://jira.corp.adobe.com/browse/UGP-10313
Test URLs:
- After: https://browse-left-nav--exlm--adobe-experience-league.hlx.live/
=> Fixed browse rail issue

blocks/featured-cards/featured-cards.js, scripts/scripts.js
Updated Product Dropdown in Featured Card component to get data from Spreadsheet
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1141
Test URLs:
- After: https://feature-exlm-1141-featured--exlm--adobe-experience-league.hlx.live
=> EXLM 1141 Featured Card Product List from Spreadsheet

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1167--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> handle custom anchors as next node sibling to a special anchor

styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://feature-highlight--exlm--adobe-experience-league.hlx.page/en/docs/workfront/using/manage-work/projects/project-finances/override-role-billing-rates-and-calculate-project-revenue
=> Style highlights

scripts/analytics/lib-analytics.js
Jira ID: UGP-10288
Test URLs:
- After: https://bugfix-ugp-10288--exlm--adobe-experience-league.hlx.live/
=> UGP-10288: remove sub-solution from solution if present

blocks/docs-cards/docs-cards.css, blocks/docs-cards/docs-cards.js
Jira ID:
Test URLs:
- After: https://feature-docs-cards--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-learn/sites/document-authoring/overview
=> Docs Cards Block

scripts/browse-card/browse-cards-paths-adaptor.js, scripts/urls.js
Updated Recommended Courses Redirection URL for Continue Course to redirect to the learning dashboard and open the particular course directly 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1137
Test URLs:
- After: https://feature-exlm-1137-rc--exlm--adobe-experience-league.hlx.live
Uploading Recommended Courses Block Continue Course View Course Recording.mp4…
=> EXLM 1137 Recommended Courses URL

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1154
Test URLs:
After: https://bugfix-exlm-1154--exlm--adobe-experience-league.hlx.live/en/browse/experience-manager
=> fix: remove users from community results exlm-1154

scripts/urls.js
Updated the URL for Recommended Courses to include origin
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1137
Test URLs:
- After: https://feature-exlm-1137-rc--exlm--adobe-experience-league.hlx.live
=> EXLM 1137 Recommended Courses URL 

scripts/browse-card/browse-cards-delegate.js
Updated ADLS to restrict the content to only English for now 
Jira ID:https://jira.corp.adobe.com/browse/UGP-10339
Test URLs:
- After: https://feature-ugp-10339-adls--exlm--adobe-experience-league.hlx.live
=> UGP 10339 ADLS 

blocks/docs-cards/docs-cards.css, blocks/docs-cards/docs-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1174
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/sites/edge-delivery-services/overview
After: https://feature-exlm-1174--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/sites/edge-delivery-services/overview
=> feat: doc cards overlapping & layout updates exlm-1174

blocks/mini-toc/utils.js
Jira ID: UGP-10352
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/experience-platform
- After: https://bugfix-ugp-10352--exlm--adobe-experience-league.hlx.live/en/docs/experience-platform
=> UGP-10352 Mini-toc for Solution Landing pages

scripts/scripts.js
Jira ID:
Test URLs: EXLM-954
- After: https://bugfix-analyticslinkclicklangaugepopover--exlm--rogerblanton.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> adding link click for language popover

blocks/teaser/teaser.css, scripts/scripts.js
try to avoid text overlap with background picture as good as possible.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1162
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/exlm-1162-test-page
- After: https://breadcrumb-editor--exlm--adobe-experience-league.hlx.live/en/browse/exlm-1162-test-page
=> exlm-1162: Text overlap issues on banner images

scripts/browse-card/browse-cards-delegate.js, scripts/scripts.js, scripts/urls.js
Updated English as default for all languages and Japanese for Ja
Jira ID:https://jira.corp.adobe.com/browse/UGP-10339
Test URLs:
- After: https://feature-ugp-10339-adls--exlm--adobe-experience-league.hlx.live
Japanese 
English
=> EXLM 10339 ADLS Lang Param Update

blocks/docs-cards/docs-cards.css, blocks/docs-cards/docs-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1174
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/sites/edge-delivery-services/overview
After: https://bugfix-exlm-1174-layout--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-learn/sites/edge-delivery-services/overview
=> fix: two card layout for docs-cards exlm-1174

blocks/browse-filters/browse-filters.js, scripts/browse-card/browse-cards-constants.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1154
Test URLs:
After: https://bugfix-exlm-1154-updates--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: set community users condition as part of aq while searching for input texts exlm-1154

blocks/article-metadata/article-metadata.js, scripts/browse-card/browse-cards-delegate.js, scripts/urls.js
Fixed the localization Issue for Last Update Date in the Article Metadata 
Updated Lang Param for ADLS
Removed Export from Url.js for lang param
Jira ID: https://jira.corp.adobe.com/browse/UGP-10348
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live
After: https://feature-ugp-10348-localization--exlm--adobe-experience-league.hlx.live
=> UGP 10348 Localization

scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/scripts.js
Jira ID: EXLM-1176
Test URLs: 
- Before: https://main--exlm--adobe-experience-league.hlx.live/en
- After: https://bugfix-exlm-1176--exlm--adobe-experience-league.hlx.live
=> EXLM-1176 Do not rewrite docs courses paths

blocks/header/header.css
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-1058
Test URLs:
- After: https://bugfix-exlm-1058-header--exlm--adobe-experience-league.hlx.live
=> Header profile text wrap fix

blocks/img-md/img-md.css, blocks/img-md/img-md.js, blocks/img-md/img-md.scss, build/sass-util.js
Zoomable image should:
1. work regardless of width option
2. image in modal should be centered and max width/height to viewport
3. Image modal should not allow scroll-through
Test URLs:
- After: https://bugfix-zoomable-image--exlm--adobe-experience-league.hlx.page/en/docs/commerce-admin/catalog/product-attributes/swatches
=> Zoomable Image Fixes 

blocks/authorable-card/article-data-adapter.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1173
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
- After: https://bugfix-exlm-1173-authorable--exlm--adobe-experience-league.hlx.live/en/authorable-cards-block
=> Fix Thumbnails for Authorable cards 

blocks/header/header.js, scripts/urls.js
Jira ID:
Test URLs:
- After: https://khoros-api--exlm--adobe-experience-league.hlx.live
=> Updated lang param for Khoros API

blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss, scripts/search/search.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1191
Test URLs:
After: https://bugfix-exlm-1191--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: remove initial search suggestion from header search exlm-1191

blocks/header/header.js, scripts/search/search.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1191
Test URLs:
After: https://bugfix-exlm-1191-updates--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: remove search suggestions from search input exlm-1191

blocks/target-insertion/target-insertion.js
=> Target Insertion - Fix undefined error

blocks/browse-rail/browse-rail.js, blocks/curated-cards/curated-cards.js, blocks/doc-actions/doc-actions.js, blocks/footer/footer.js, blocks/header/header.js, blocks/marquee/marquee.js, blocks/recommended-courses/recommended-courses.js, blocks/sign-up/sign-up.js, blocks/target-insertion/target-insertion.js, scripts/browse-card/browse-card.js, scripts/data-service/coveo/coveo-token-service.js, scripts/data-service/profile-service.js, scripts/gainsight/gainsight.js, scripts/prev-next-btn.js, scripts/scripts.js, scripts/urls.js
The Pr introduces several refactor and non-breaking changes.
Test URLs:
- After: https://refactor-ims-and-scripts--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-1164 - IMS usage refactor - Scripts Refactor

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1177
Test URLs:
- After: https://bugfix-exlm-1177-table--exlm--adobe-experience-league.hlx.live
=> Global table styles

blocks/adls-cards/adls-cards.js, blocks/authorable-card/authorable-card.js, blocks/browse-filters/browse-filters.js, blocks/curated-cards/curated-cards.js, blocks/events-cards/events-cards.js, blocks/featured-cards/featured-cards.js, blocks/recommended-courses/recommended-courses.js, blocks/tabbed-cards/tabbed-cards.js, scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://bugfix-svg-icons-fix--exlm--adobe-experience-league.hlx.live/
=> Icon Fixes

blocks/marquee/marquee.css, blocks/marquee/marquee.js
Jira ID:
Test URLs:
- After: https://dont-await-signin--exlm--buuhuu.hlx.live/
=> fix: dont wait for sign-in

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://martech-off--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Ability to disable martech

blocks/header/header.css, blocks/header/header.scss, blocks/marquee/marquee.js, blocks/sign-up/sign-up.css, blocks/sign-up/sign-up.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1193
Test URLs:
- After: https://feature-exlm-1193-sign--exlm--adobe-experience-league.hlx.live
=> Header and Marquee signup logic rework

blocks/doc-actions/doc-actions.js, blocks/sign-up/sign-up.css, blocks/table/table.css, scripts/feedback/feedback.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1196 
Test URLs:
- After: https://bugfix-exlm-1196-issues--exlm--adobe-experience-league.hlx.page
=> UI Issues on Dev

blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, blocks/header/header.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1195
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live
After: https://bugfix-exlm-1195--exlm--adobe-experience-league.hlx.live
=> fix: handle auth links on footer EXLM-1195

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1185
Test URLs:
After: https://bugfix-exlm-1185--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: update no results message for community with roles combo exlm-1185

blocks/footer/footer.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1195
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live
After: https://bugfix-footer-exlm-1195--exlm--adobe-experience-league.hlx.live
=> fix: footer issue EXLM-1195

blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1193 
Test URLs:
- After: https://bugfix-exlm-1196-header--exlm--adobe-experience-league.hlx.live
=> Header Product Grid Fix

scripts/editor-support-rte.js, scripts/editor-support.js, scripts/lib-franklin.js
Improve script/style loading for UE by direct loading script/style from hlx.page/hlx.live if enabled via Access-Control-Allow-Origin header
=> chore: improve script loading for UE

blocks/browse-filters/browse-filters.js, scripts/editor-support-rte.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1201
Test URLs:
After: https://bugfix-exlm-1201--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: search input issue with community filters exlm-1201

blocks/browse-filters/browse-filters.js, blocks/footer/footer.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1185
Test URLs:
After: https://bugfix-exlm-1185-msg--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: update no results message exlm-1185

blocks/footer/footer.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1179
Test URLs:
After: https://bugfix-exlm-1179-issue--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: handle intermittent footer issue due to race condition exlm-1179

scripts/editor-support-rte.js, scripts/scripts.js
=> fix: load privacy-standalone relative to codebasepath

blocks/footer/footer.css, blocks/footer/footer.scss
Jira ID:
Test URLs:
- After: https://footer-breadcrumbs--exlm--adobe-experience-league.hlx.live
=> Footer breadcrumbs

blocks/browse-filters/browse-filters.js, blocks/browse-filters/browse-topics.js, blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1202
Test URLs:
After: https://bugfix-exlm-1202--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: add workaround for missing aq during facet selection exlm-1202

.husky/pre-commit, .husky/pre-push, check-branch-name.js, package.json
Pre commit / push hook to verify that the branch name does not exceed the maximum length
relates to https://github.com/adobe/helix-bot/issues/961
=> chore: check branch pre commit / push

component-models.json
=> fix: remove cq namespace

scripts/scripts.js
Jira ID: EXLM-1132
Test URLs:
- After: https://bugfix-exlm-1132-consent--exlm--adobe-experience-league.hlx.live/
=> EXLM-1132: load privacy-standalone from origin via cdn routing.

scripts/editor-support-rte.js
=> fix: update rte support script

blocks/recommended-courses/recommended-courses.js
Updated Recommended Courses component to move the placement of No Results container
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1182
Test URLs:
- After: https://feature-exlm-uatfixes--exlm--adobe-experience-league.hlx.live
=> Recommended Courses  UAT Fix

blocks/authorable-card/authorable-card.js
Jira ID:
Test URLs:
- After: https://authorable-cards--exlm--adobe-experience-league.hlx.page/en/authorable-cards-ahmed
=> Authorable Cards - get type from all possible meta

blocks/authorable-card/authorable-card.js
=> Authorable Cards - fetch path as is

blocks/featured-cards/featured-cards.js
Moved th
e Role and Label default values to placeholders
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1219
Test URLs:
- After: https://feature-exlm-1219--adobe-experience-league.hlx.live
=> EXLM 1219 Featured Card

scripts/browse-card/browse-cards-delegate.js
Jira ID: EXLM-1220
Test URLs:
- After: https://bugfix-exlm-1220--exlm--adobe-experience-league.hlx.live/?martech=off
=> Curated Cards - Locale changes

styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1216
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/commerce-operations/release/planning/schedule
- After: https://bugfix-exlm-1261-table--exlm--adobe-experience-league.hlx.live/en/docs/commerce-operations/release/planning/schedule
=> Global styles table issue

scripts/coveo-headless/engine.js
Jira ID:
Test URLs:
- After: https://bugfix-coveo-prod-link--exlm--adobe-experience-league.hlx.live/?martext=off
=> Coveo Prod Link

scripts/coveo-headless/index.js
Jira ID: 
Test URLs:
After: https://feat-headless-locale--exlm--adobe-experience-league.hlx.live/en/browse
=> feat: setup locale on headless engine

blocks/toc/toc.js, scripts/urls.js
=> Use new TOC action

scripts/search/search.js
Jira ID: [EXLM-1158](https://jira.corp.adobe.com/browse/EXLM-1158)
Test URLs:
- After: https://exlm-1158--exlm--adobe-experience-league.hlx.live
=> EXLM-1158 Search - automatic pre-filters for solution

scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-delegate.js
Updated the time left logic to show only for the language En and Total Duration for all other languages
Updated the lang parameter to extract the locale specific Data
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1182
Test URLs:
- After: https://feature-exlm-1182-rec-courses--exlm--adobe-experience-league.hlx.live
Japanese
English
=> EXLM 1182 Recommended Courses Duration Calculation

scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-delegate.js
Updated the code to support the locale mapping for Zh Es and PT for Paths API as well 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1182
Test URLs:
- After: https://feature-exlm-1182-rec-courses--exlm--adobe-experience-league.hlx.live
=> EXLM1182 Recommended Courses  Support for Zh and PT

blocks/header/header.css, blocks/header/header.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1235
Test URLs:
- After: https://bugfix-exlm-1235-header--exlm--adobe-experience-league.hlx.live
=> Authenticated Header bug fix

scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1222
Test URLs:
- After: https://feature-exlm-1222--exlm--adobe-experience-league.hlx.live
=> EXLM-1222 Open on demand content in same tab

blocks/header/header.css, blocks/header/header.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1235
Test URLs:
- After: https://bugfix-exlm-1235-revert--exlm--adobe-experience-league.hlx.live
=> revert "Authenticated header bug fix" #660

blocks/header/header.css, blocks/header/header.scss
=> Hot Fix: Authenticated header

component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1166
Test URLs:
- After: https://exlm-1166-ue--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/tabbed.html?ref=exlm-1166-ue
=> EXLM-1166 Date filter for tabbed cards

blocks/table/table.js
Jira ID:  https://jira.corp.adobe.com/browse/EXLM-1247 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/workfront-known-issues/issues/new-workfront-experience/newworkfrontexperience
- After: https://hotfix-exlm-1247-table--exlm--adobe-experience-league.hlx.live/en/docs/workfront-known-issues/issues/new-workfront-experience/newworkfrontexperience
=> Hotfix - Html elements in Table fix

blocks/table/table.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1247 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/workfront-known-issues/issues/new-workfront-experience/newworkfrontexperience
- After: https://hotfix-exlm-1247-table--exlm--adobe-experience-league.hlx.live/en/docs/workfront-known-issues/issues/new-workfront-experience/newworkfrontexperience
=> Hotfix - Table fix

blocks/authorable-card/authorable-card.js
=> Hotfix - Translated Content for Badge Title

blocks/marquee/marquee.css, blocks/marquee/marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1234
Test URLs:
- After: https://bugfix-exlm-1234-video--exlm--adobe-experience-league.hlx.live
=> Update modal style for Video in Marquee

scripts/feedback/feedback.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1246
Test URLs:
- After: https://feature-exlm-1246--exlm--adobe-experience-league.hlx.live
=> EXLM-1246 Feedback bar

helix-query.yaml
=> Hotfix - Reduce Sitemap Size - fix index names

component-models.json
Jira ID: EXLM-1166
Test URLs:
- After: https://exlm-1166--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/tabbed.html?ref=exlm-1166
=> EXLM-1166 Filter by Date for tabbed cards

blocks/featured-cards/featured-cards.js, scripts/dropdown/dropdown.js
Updated Featured Card Component to preserve the filters when the user navigates back through URL Query Params 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1161
Test URLs:
- After: https://feature-exlm-1161-feat-card--exlm--adobe-experience-league.hlx.live
https://github.com/adobe-experience-league/exlm/assets/30936827/c88f6472-ff82-4d34-9f9d-dfdc7af039c4
=> EXLM 1161 Featured Card Filters

blocks/code/code.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1250
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-cloud-service/content/overview/seo-and-url-management
- After: https://bugfix-exlm-1250-doc--exlm--adobe-experience-league.hlx.live/en/docs/experience-manager-cloud-service/content/overview/seo-and-url-management?martech=off
=> Doc pages horizontal scroll fix

component-models.json, scripts/browse-card/browse-card.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1253 
Test URLs:
- After: https://bugfix-exlm-1253-card--exlm--adobe-experience-league.hlx.live/en/browse
=> EXLM - 1253 Browse card long character fix

blocks/browse-filters/browse-filters.js, scripts/coveo-headless/index.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1225
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse/analytics
After: https://bugfix-exlm-1225--exlm--adobe-experience-league.hlx.live/en/browse/analytics
=> fix: retain page number selection on load exlm-1225

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1225
Test URLs:
After: https://bugfix-exlm-1225-render--exlm--adobe-experience-league.hlx.live/en/browse
=> fix: prevent unwanted rerender of cards due to headlessSearchBox state update exlm-1225

scripts/analytics/lib-analytics.js
Jira ID: UGP-10609
Test URLs:
- After: https://bugfix-ugp-10609--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> ugp-10609 and ugp-10244 additional change

blocks/header/header.css, blocks/header/header.js, blocks/header/header.scss
Jira ID:
Test URLs:
- After: https://feature-exlm-1096--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> profile picture from pps

scripts/scripts.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1282--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-1282 - new Launch script in dev

blocks/browse-filters/browse-filters.js, scripts/analytics/lib-analytics.js, scripts/coveo-headless/index.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1257-dl--exlm--adobe-experience-league.hlx.live/
=> EXLM-1257 DL Changes for Browse Filters

styles/styles.css, styles/styles.scss
Jira ID: EXLM-1252
Test URLs:
- After: https://bugfix-exlm-1252--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Fix landing page spacing to be consistent with padding instead of margin

icons/rail.svg
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1279
Test URLs:
- After: https://bugfix-exlm-1279--exlm--adobe-experience-league.hlx.live
=> EXLM-1279 Fixed rails tooltip

scripts/browse-card/browse-cards-adls-adaptor.js, scripts/browse-card/browse-cards-live-events-adaptor.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1262
Test URLs:
- After: https://bugfix-exlm-1262--exlm--adobe-experience-league.hlx.live
=> EXLM-1262 ADLS card labels

blocks/browse-filters/browse-filters.js, scripts/browse-card/browse-card-placeholder.css, scripts/browse-card/browse-card-placeholder.js, scripts/coveo-headless/engine.js, scripts/search/search-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1223
Test URLs:
After: https://feat-exlm-1223--exlm--adobe-experience-league.hlx.live/en/browse
=> feat: show shimmer animation until coveo v2 call is done exlm-1223

404.html
Updated 404.html to get the respective AEM locale 404 page as authored in UE
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1259
Test URLs:
- After: https://feature-exlm-1259-404--exlm--adobe-experience-league.hlx.live
=> EXLM-1259-404 All Locales

styles/styles.css, styles/styles.scss
Jira ID: EXLM-1275
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/overview/seo-and-url-management?martech=off
- After: https://exlm-1275--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/overview/seo-and-url-management?martech=off
- After: https://exlm-1275--exlm--adobe-experience-league.hlx.page/en/docs/experience-platform/rtcdp/home?martech=off
=> EXLM-1275 - Fix content too wide on mobile

blocks/footer/footer.css, blocks/footer/footer.scss
Remove unreadable nested `&-` from class names
=> Footer CSS readability

blocks/footer/footer.css, blocks/footer/footer.scss
Jira ID:
Test URLs:
- After: https://exlm-1263--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> EXLM-1263 - Better spacing for copyright text

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, scripts/coveo-headless/index.js
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse
After: https://query-suggest-fix--exlm--adobe-experience-league.hlx.page/en/browse
=> fix: browse query suggestion & sortDropdown toggle visibility

scripts/bookmark/bookmark.js, scripts/browse-card/browse-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1277
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/browse
After: https://bugfix-exlm-1277--exlm--adobe-experience-league.hlx.page/en/browse
=> fix: remove setimeout value to set the appropriate pointer-event value to handle the bookmark issue

blocks/code/code.css, scripts/delayed.js, styles/styles.css, styles/styles.scss
Jira ID: EXLM-1250
Test URLs:
- After: https://exlm-1250--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> EXLM-1250 - Fix wrapping content, wrapping code and add code wrapping button

blocks/marquee/marquee.js
Test URLs:
- After: https://marquee-undefined--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> Fix marquee undefined issues

scripts/scripts.js, styles/image-modal.css
Jira ID: EXLM-1300
Test URLs:
- After: https://exlm-1300--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> EXLM-1300 image modal background and image title

blocks/detailed-teaser/detailed-teaser.css, blocks/teaser/teaser.css
Jira ID:
Test URLs:
- After: https://feature-exlm-1294--exlm--adobe-experience-league.hlx.live/
=> EXLM-1294 - Teaser Border Fix

component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-1210
Test URLs:
- After: https://feature-exlm-1210-ue--exlm--adobe-experience-league.hlx.live
=> EXLM-1210 Article Marquee block

blocks/detailed-teaser/detailed-teaser.css, blocks/marquee/marquee.css, blocks/sign-up/sign-up.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1297
Test URLs:
- After: https://bugfix-exlm-1297-ts--exlm--adobe-experience-league.hlx.page
=> EXLM 1297- Remove spacing around teaser

blocks/header/header.js
Updated the Header to get the Featured Products from Top Products List 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1317
Test URLs:
- After: https://feature-exlm-1317-header--exlm--adobe-experience-league.hlx.live
=> EXLM 1299 Header Featured Products

scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://hotfix-ugp-10704--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Hotfix UGP-10704 & EXLM-1338 fix blank pages and table render issues

blocks/browse-filters/browse-filters.js, component-models.json
Jira ID: EXLM-1206
Test URLs:
- After: https://feature-exlm-1206-topics--exlm--adobe-experience-league.hlx.live/
=> EXLM-1206: option to change Topics heading font size

styles/styles.css, styles/styles.scss
Jira ID: UGP-10548 : Template changes for KB Article pages.
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/experience-cloud-kcs/kbarticles/ka-22383
- After: https://feature-ugp-10548--exlm--adobe-experience-league.hlx.page/en/docs/experience-cloud-kcs/kbarticles/ka-22383?martech=off
=> feature/UGP-10548 Styles targeting KB Article pages

scripts/lib-franklin.js
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/docs?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service?martech=off
After: …
=> Remove perf measurement code

blocks/breadcrumbs/breadcrumbs.css, blocks/cloud-solutions/cloud-solutions.css, blocks/footer/footer.css, blocks/footer/footer.js, blocks/footer/footer.scss, blocks/guides-list/guides-list.css, blocks/header/header.js, blocks/tutorial-list/tutorial-list.css, scripts/feedback/feedback.css, scripts/language.js, scripts/rails/rails.js, styles/styles.css, styles/styles.scss
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/docs?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/browse/analytics?martech=off
After: https://performance--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service?martech=off
After: …
=> Improve a11y and SEO scores 

blocks/browse-filters/browse-filters.js, component-models.json
Jira ID:
Test URLs:
- After: https://feature-exlm-1207-meta--exlm--adobe-experience-league.hlx.live/
=> Section Metadata

component-models.json
Updated the Page Metadata to include Article Theme Details
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1308
Test URLs:
- After: https://feature-exlm-1308-metadata--exlm--adobe-experience-league.hlx.live
=> EXLM 1308 Page Metadata

scripts/feedback/feedback.js
Jira ID:
Test URLs:
- After: https://bugfix-ugp-8792--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> UGP-8792 - quatrics feedback errors on language browsers

blocks/browse-filters/browse-filters.js, component-models.json
headingStyle pattern. 
author preview has slightly different element structure than eds if using richtext component - the bug is caused by this but since we will be using headingType pattern, this is not an issue per unit test.
Jira ID: EXLM-1232
Test URLs:
- After: https://bugfix-exlm-1342-topics--exlm--adobe-experience-league.hlx.live/
=> EXLM-1206 / 1232: headingStyle pattern

blocks/recommended-courses/recommended-courses.js
Removed recommended Courses Block from DOM when the user is not Signed In
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1297
Test URLs:
- After: https://feature-exlm-1297-rec--exlm--adobe-experience-league.hlx.live
Spacing
=> EXLM 1297 Spacing Issue 

scripts/auth/profile.js
Jira ID:
Test URLs:
- After: https://exlm-1295--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-1295 - Fix issue with bookmarks

blocks/block-quote/block-quote.js
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1304
Updated the theme variable class List Name
Test URLs:
After: https://feature-exlm-1304-block-quote--exlm--adobe-experience-league.hlx.live/
=> EXLM 1304 Block Quote Theme Update

helix-query.yaml
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1210 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/articles
- After: https://feature-exlm-1210-ai--exlm--adobe-experience-league.hlx.page/en/articles
=> EXLM 1210 - Add article pages index

helix-query.yaml
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1210
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/articles
- After: https://feature-exlm-1210-ai--exlm--adobe-experience-league.hlx.page/en/articles
=> ELM 1210 - Remove exclude from article-index

component-definition.json, component-filters.json, component-models.json
Updated Component Model Filter and Definitions to add two new sections Article Header Section and Article Content Section 
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1356
Test URLs:
- After: https://feat-exlm-1356--exlm--adobe-experience-league.hlx.live
=> EXLM 1356 Article Page Template UE Sections

component-definition.json, component-filters.json, component-models.json
Updated Component Model Definition and Filters for Callout Block 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1303
Test URLs:
- After: https://feature-exlm-1303-callout--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> EXLM 1303 Callout Block UE Changes

scripts/articles/articles.css, scripts/articles/articles.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1209
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.page/en/articles/experience-manager
After: https://feat-exlm-1209--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager
=> feat: articles page layout impl EXLM-1209

blocks/browse-filters/browse-topics.css
Jira ID: EXLM-1342
Test URLs:
- After: https://bugfix-exlm-1342-topics--exlm--adobe-experience-league.hlx.live/
=> EXLM-1342: Browse Filter - Topics font size issue

blocks/callout/callout.css, blocks/callout/callout.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1303
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager
After: https://feat-exlm-1303--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager
=> feat: callout card block impl exlm-1303

component-models.json
Jira ID: EXLM-1382
Test URLs:
- After: https://bugfix-exlm-1382--exlm--adobe-experience-league.hlx.live
=> EXLM-1382 Removed default selection

blocks/article-marquee/article-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1379
Test URLs:
-  Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
-  After: https://feature-exlm-1210-am--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> EXLM - 1379 Fix bookmark issue in Article Marquee

scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1380
Test URLs:
- After: https://exlm-1380--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> fix: articles header exlm-1380

blocks/callout/callout.css, blocks/mini-toc/mini-toc.js, scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1386
Test URLs:
- After: https://exlm-1386--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> fix: article layout exlm-1386

blocks/article-marquee/article-marquee.css, blocks/article-marquee/article-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1381
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles
- After: https://bugfix-exlm-1381-am--exlm--adobe-experience-league.hlx.live/en/articles
=> EXLM-1381 Article Marquee UI issues

blocks/mini-toc/mini-toc.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1386
Test URLs:
- After: https://bugfix-exlm-1386--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> fix: querySelector issue during mini-toc build exlm-1386

blocks/article-marquee/article-marquee.css, blocks/article-marquee/article-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1381
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles
- After: https://bugfix-exlm-1381-am--exlm--adobe-experience-league.hlx.live/en/articles
=> Article Marquee UE Issue fix

paths.json
Jira ID:
Test URLs:
- After: https://feature-article-index--exlm--adobe-experience-league.hlx.live/
=> Add Article Index

scripts/scripts.js
Jira ID: EXLM-1395
Test URLs:
- After: https://feature-exlm-1395--exlm--adobe-experience-league.hlx.live/
=> EXLM-1395: update new launch Stage script.

component-models.json
Jira ID: EXLM-1376
Test URLs:
After: https://feature-exlm-1376--exlm--adobe-experience-league.hlx.live/
=> EXLM-1376 Page meta-tags for coveo index

blocks/author-bio/author-bio.css, blocks/author-bio/author-bio.js, component-definition.json, component-filters.json, component-models.json
Updated Component Model Filter Definitions along with Block Basic Css and Js for Author Bio Pages Block
Note: The author Bio Page block is developed with Sample Styling for now as it does not have a visitor design
This will be part of the Summary Block 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles
- After: https://feature-exlm-1283-author-bio--exlm--adobe-experience-league.hlx.live/en/articles
Sample Styling
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/articles/carl-cameron.html?ref=feature-exlm-1283-author-bio
=> EXLM 1283 Author Bio Pages Block

component-definition.json, component-filters.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1359
Test URLs:
- After: https://feature-exlm-1358-am--exlm--adobe-experience-league.hlx.live
=> EXLM-1359 Author summary UE component update

blocks/article-tags/article-tags.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1348
Test URLs:
- After: https://feat-exlm-1348--exlm--adobe-experience-league.hlx.live
=> spacing fixes

scripts/analytics/lib-analytics.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
- After: https://ugp-10788--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> UGP-10788 - 'type' must be 'other' (lowercase) for datalayer link click web interaction

blocks/table/table.css, blocks/table/table.scss
Jira ID: UGP-10566
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/docs/support-resources/data-sheets/bug-fixes
- After: https://bugfix-ugp-10566--exlm--adobe-experience-league.hlx.page/en/docs/support-resources/data-sheets/bug-fixes
=> bugfix/UGP-10566 Fix link smaller font

blocks/article-marquee/article-marquee.css, blocks/article-marquee/article-marquee.js, blocks/author-bio/author-bio.js, component-definition.json, component-filters.json, component-models.json, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1358
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
- After: https://feature-exlm-1358-am--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
=> EXLM 1358 - Article Marquee refactor

helix-query.yaml
Jira ID:
Test URLs:
- After: https://helix-query-update--exlm--adobe-experience-league.hlx.live
=> Updated article-index query

blocks/article-marquee/article-marquee.js, blocks/author-summary/author-summary.css, blocks/author-summary/author-summary.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1359
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
- After: https://feature-exlm-1359-as--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
=> EXLM-1359 Author Summary Block

scripts/scripts.js
Jira ID: EXLM-1376
Test URLs:
- After: https://exlm-1376--exlm--adobe-experience-league.hlx.live
=> EXLM-1376 Tags updated for Articles page

blocks/toc/toc.js
Jira ID:
Test URLs:
- After: https://exlm-1431--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> EXLM-1431 - show selected item in TOC

blocks/browse-rail/browse-rail.css
Jira ID: EXLM-1419
Test URLs:
- After: https://bugfix-exlm-1419--exlm--adobe-experience-league.hlx.live
=> EXLM-1419 Browse Left Nav alignment

blocks/browse-rail/browse-rail.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1428
Test URLs:
- After: https://bugfix-exlm-1428-ba--exlm--adobe-experience-league.hlx.live
=> EXLM 1428 - Add padding to browse rail

fstab.yaml
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1349
Test URLs:
- After: https://feat-exlm-1349--exlm--adobe-experience-league.hlx.live
=> Feat exlm 1349

scripts/articles/articles.css, scripts/articles/articles.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1391
Test URLs:
- After: https://exlm-1391-fix--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> fix: css adjustment for article layout exlm-1391

blocks/article-marquee/article-marquee.js, blocks/author-bio/author-bio.js, blocks/author-summary/author-summary.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1358
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
- After: https://feature-exlm-1210-re--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
=> Refactor author bio fetch

scripts/scripts.js
=> Revert Using new Launch Script 

scripts/scripts.js
Test URLs:
- After: https://feature-exlm-1446--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Clean up page metadata code

blocks/featured-authors/featured-authors.js, component-models.json
Test URLs:
- After: https://feature-exlm-1446--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Added content picker for Author Bio page

blocks/article-tags/article-tags.js, scripts/scripts.js
Test URLs:
- After: https://feature-exlm-1446--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Page metadata - tags decoded

blocks/featured-authors/featured-authors.js, component-definition.json, component-models.json
- Added some default values for heading and image border/alignment
- condition so you can only edit author CTA if author bio has been set first.
Test URLs:
- After: https://exlm-1351-2--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> EXLM-1351: Improvments for Featured Authors Block

blocks/article-marquee/article-marquee.js, blocks/author-summary/author-summary.js, component-models.json, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1469
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
- After: https://feat-exlm-1469-au--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/test-page
=> EXLM-1469 - Refactor Article Marquee and Author Summary to use Page metadata

blocks/article-tags/article-tags.js, component-models.json
Test URLs:
- After: https://exlm-1446--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Updated changes compatible with page properties custom metadata

blocks/article-tags/article-tags.js, component-models.json
Reverts adobe-experience-league/exlm#844
Test URLs:
After: https://revert-844-exlm-1446--exlm--adobe-experience-league.hlx.live/
=> Revert "EXLM-1446 Updated changes compatible with page properties custom metadata"

component-models.json
Test URLs:
- After: https://exlm-1446--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Updated author-bio-page as a content-picker in page metadata

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, blocks/featured-cards/featured-cards.js, scripts/coveo-headless/index.js
Jira ID: EXLM-1305
Test URLs:
- After: https://feature-exlm-1305--exlm--adobe-experience-league.hlx.live/
=> exlm-1305: View more link that can apply filters to show more results

helix-sitemap.yaml
Reverts adobe-experience-league/exlm#850
=> Revert "Change Sitemap Origin for Dev"

scripts/browse-card/browse-cards-coveo-data-adaptor.js, scripts/browse-card/browse-cards-delegate.js, scripts/coveo-headless/index.js, scripts/data-service/coveo/coveo-data-service.js
Jira ID:
Test URLs:
- After: https://course-desc-and-thumb--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management
=> Added fallbacks for thumbnail and description for browse cards + staging search token

blocks/detailed-teaser/detailed-teaser.css, blocks/marquee/marquee.css, blocks/media/media.css, blocks/sign-up/sign-up.css, blocks/teaser/teaser.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1420 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles
- After: https://feat-exlm-1420-ar--exlm--adobe-experience-league.hlx.live/en/articles
=> EXLM 1420 - Article Theme block styles

scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1391
Test URLs:
- After: https://cssfix-articles-page--exlm--adobe-experience-league.hlx.live/en/articles/experience-manager/sample-article
=> fix: css updates for gap in articles layout

blocks/featured-cards/featured-cards.js
Reinstate original execution order of updateDropdownValue() if blocks to address browser back issue.  
Fix white space not encoded properly which causes the drop down ui issues and coveo query no results issue.
Jira ID: EXLM-1479 / EXLM-1305
Test URLs:
- After: https://bugfix-exlm-1479--exlm--adobe-experience-league.hlx.live/
=> exlm-1479: feature cards exlm1305 bugfixes

blocks/article-tags/article-tags.js
Test URLs:
- After: https://coveo-solution--exlm--adobe-experience-league.hlx.live
=> EXLM-1446 Updated coveo -solution page meta

component-models.json
Jira ID:
Test URLs:
- After: https://feature-exlm-1375--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Moved Article to top - UE Dropdown

scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1375--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Added Placeholder for Author Prefix

blocks/featured-authors/featured-authors.css
Jira ID:
Test URLs: https://jira.corp.adobe.com/browse/EXLM-1453
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/title-samples 
- After: https://exlm-1453--exlm--adobe-experience-league.hlx.page/en/title-samples
=> exlm-1453: Fixing layouting issues for featured authors block

blocks/inline-survey/inline-survey.css, blocks/inline-survey/inline-survey.js, component-definition.json, component-filters.json, component-models.json
Initial Block for inline Survey, Currently supports the Survey Title and an ID to be used to add the Survey.
=> initial inline feedback

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, scripts/browse-card/browse-cards-constants.js, scripts/coveo-headless/engine.js, scripts/coveo-headless/index.js, scripts/data-service/coveo/coveo-data-service.js, scripts/data-service/coveo/coveo-token-service.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1352
Test URLs:
- After: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> Added Author type Facet to Browse Filters EXLM-1352

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1352
Test URLs:
- After: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> feat: article author type facet condition update

scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-coveo-data-adaptor.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1375--exlm--adobe-experience-league.hlx.live/en/curated-cards-single
=> Console Log Error - Fixes

blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1352
Test URLs:
- After: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> feat: experience type facet condition update

blocks/curated-cards/curated-cards.js, component-models.json
Jira ID: EXLM-1498
Test URLs:
- After: https://bugfix-exlm-1498--exlm--adobe-experience-league.hlx.live
=> EXLM-1498 Updated Experience level options for curated cards

blocks/browse-filters/browse-filters.js
Jira ID: EXLM-1479 / 1305
Test URLs:
- After: https://bugfix-exlm-1479-closeicon--exlm--adobe-experience-league.hlx.live/
-
=> EXLM-1479: close icon not showing for any 2nd filter from feature-cards params

blocks/browse-filters/browse-filters.js
If PR#873 still has issues, perhaps this is an acceptable solution? Suggest different param name and/or value.
Jira ID: EXLM-1479
Test URLs:
- After: https://bugfix-exlm-1479-icon--exlm--adobe-experience-league.hlx.live/
=> Bugfix/exlm-1479 icon another solution 

blocks/browse-filters/browse-filter-utils.js, scripts/crypto.js, scripts/lib-franklin.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1509
Test URLs:
- After: https://feat-exlm-1509--exlm--adobe-experience-league.hlx.page
=> Filter Author Type fix

blocks/data-and-email-consent/data-and-email-consent.css, blocks/data-and-email-consent/data-and-email-consent.js, component-definition.json, component-filters.json
Jira ID: EXLM-1503
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/profile/signup-flow-modal/step3
After: https://fix-1503--exlm--adobe-experience-league.hlx.live/en/profile/signup-flow-modal/step3
=> EXLM-1503 Data and email consent card

scripts/toast/toast.js
Jira ID: EXLM-1491
Test URLs:
- After: https://feature-exlm-1491--exlm--adobe-experience-league.hlx.live
=> EXLM-1491 Toast notification updates

blocks/header/header.js, scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://feature-exlm-1504--exlm--adobe-experience-league.hlx.live/?signup-wizard=on
=> EXLM-1504 / Signup flow popup

blocks/adobe-account-card/adobe-account-card.css, blocks/adobe-account-card/adobe-account-card.js
Jira ID: EXLM-1502
Test URLs:
- After: https://feature-exlm-1502--exlm--adobe-experience-league.hlx.live
=> EXLM-1502 Adobe Account card

blocks/role-cards/role-cards.css, blocks/role-cards/role-cards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1506
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.page/en/profile
- After: https://feat-exlm-1506-fix--exlm--adobe-experience-league.hlx.page/en/profile
=> fixes for updating the values

scripts/data-service/coveo/coveo-token-service.js
Jira ID: bugfix/coveo-service-typo
Test URLs:
- After: https://bugfix-coveo-service-typo--exlm--adobe-experience-league.hlx.live/
=> prod/hotfix code sync: coveo-service-typo

component-definition.json, component-filters.json, component-models.json, scripts/editor-support.js, scripts/events/event-stream.js
Jira ID: EXLM-1511
Test URLs:
- After: https://feature-exlm-1511--exlm--adobe-experience-league.hlx.live
=> EXLM-1511 Special containers for Profile and Signup pages

scripts/profile/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1558
Test URLs:
- After: https://exlm-1558--exlm--adobe-experience-league.hlx.live/
=> fix: profile card style EXLM-1558

scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1571--exlm--adobe-experience-league.hlx.live/
=> Signup Flow - Fixes

head.html
Jira ID:
Test URLs:
- After: https://ugp-10959--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> bing console ownership

blocks/table/table.css, blocks/table/table.scss, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://ugp-10565--exlm--adobe-experience-league.hlx.page/en/docs/support-resources/data-sheets/bug-fixes?martech=off
- After: https://ugp-10565--exlm--adobe-experience-league.hlx.page/en/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-foundation-components/supporting-new-language-localization?martech=off
=> Highlighted text - inline and as a section style

scripts/toast/toast.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1591
Test URLs:
- After: https://bugfix-exlm-1591--exlm--adobe-experience-league.hlx.live
=> EXLM 1591 - Render Toast inside dialog

scripts/auth/profile.js
Jira ID:
Test URLs:
- After: https://feature-profile-config--exlm--adobe-experience-league.hlx.live/?martext=off
=> ExL Profile Config - Check

scripts/profile/profile.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1600
Test URLs:
- After: https://feat-exlm-1600--exlm--adobe-experience-league.hlx.page
=> flex css fix for tablet and mobile

blocks/curated-cards/curated-cards.js, component-models.json, scripts/browse-card/browse-cards-delegate.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1594--exlm--adobe-experience-league.hlx.live/?martech=off
=> Curated Card - Author Type Changes

blocks/email-card/email-card.css, blocks/email-card/email-card.js, component-definition.json, component-filters.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1578
Test URLs:
- After: https://feat-exlm-1578--exlm--adobe-experience-league.hlx.page
=> email card ue and fe changes

component-definition.json, component-filters.json, component-models.json
Jira ID:
Test URLs:
- After: https://exlm-1575--exlm--adobe-experience-league.hlx.live
=> Product Interests Blocks

component-definition.json, component-filters.json, component-models.json
Jira ID:
Test URLs:
- After: https://exlm-1575--exlm--adobe-experience-league.hlx.live
=> EXLM-1575 Updated Product Interests blocks

blocks/profile-rail/profile-rail.css, blocks/profile-tab/profile-tab.css, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1584
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/profile
- After: https://feature-exlm-1584--exlm--adobe-experience-league.hlx.live/en/profile
=> EXLM 1584 - Profile theme Mobile and Tablet styles

blocks/icon-block/icon-block.css, blocks/icon-block/icon-block.js, component-definition.json, component-filters.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1576
Test URLs:
- After: https://feat-exlm-1576--exlm--adobe-experience-league.hlx.page
=> icon block UE & FE changes

blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js, component-definition.json, component-filters.json, component-models.json, scripts/dom-helpers.js
Based on the Featured Authors block.
This block references a Thought Leadership article and pulls the title, summary, and author(s) from the article.
It also has a couple of override properties for the summary and CTA text.
Also add dom-helpers.js to /scripts. This makes constructing HTML much simpler.
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1546
Test URLs:
Before: https://main--exlm--adobe-experience-league.hlx.live/en/featured-content
After: https://feature-exlm-1546--exlm--rrusher.hlx.page/en/featured-content
=> Add featured-content block

component-definition.json, component-filters.json, component-models.json
Jira ID:
Test URLs:
- After: https://revert-1575--exlm--adobe-experience-league.hlx.live
=> EXLM-1575 Removed Product Entitlements Block

blocks/profile-rail/profile-rail.css, blocks/profile-rail/profile-rail.js, helix-query.yaml, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1566
Test URLs:
- After: https://feature-exlm-1566--exlm--adobe-experience-league.hlx.live
=> EXLM-1566 - Profile Left rail and Profile page query index

component-models.json
Jira ID: EXLM-1646
Test URLs:
- After: https://exlm-1650--exlm--adobe-experience-league.hlx.live
=> EXLM-1646 Block quote

component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-1651
Test URLs:
- After: https://exlm-1651--exlm--adobe-experience-league.hlx.live
=> EXLM-1651 Note block

blocks/article-marquee/article-marquee.js
Jira ID: EXLM-article-path
Test URLs:
- After: https://bugfix-article-path--exlm--adobe-experience-league.hlx.live/
=> Change article parent folder per Stage page setup and testing feedback.

scripts/editor-support.js
Jira ID:
Test URLs:
- After: https://bugfix-article-path--exlm--adobe-experience-league.hlx.live
=> Fix for author bio pages

blocks/note/note.js
Jira ID: EXLM-1651
Test URLs:
After: https://exlm-1651--exlm--adobe-experience-league.hlx.live/
=> EXLM-1651 Note block icons

blocks/user-profile-card/user-profile-card.css, blocks/user-profile-card/user-profile-card.js, scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js
Jira ID:
Test URLs:
- After: https://feature-exlm-1564--exlm--adobe-experience-league.hlx.live/?martech=off
=> Signup Flow - Finish Screen Changes

scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1671
Test URLs:
- After: https://bugfix-exlm-1671--exlm--adobe-experience-league.hlx.live
=> EXLM 1671 - Temporary fix for profile page redirect in UE

scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1662 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights/how-to-drive-content-velocity-aem
- After: https://bugfix-exlm-1662--exlm--adobe-experience-league.hlx.live/en/actionable-insights/how-to-drive-content-velocity-aem?martech=off
=> EXLM 1662 - Article pages UAT issues

scripts/editor-support.js
Sets id for or titles in the article content section when viewed in UE.
Jira ID:
Test URLs:
- Before: https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/actionable-insights/how-to-drive-content-velocity-aem.html
- After: https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/actionable-insights/how-to-drive-content-velocity-aem.html?ref=exlm-1672
=> EXLM-1672: adding Id for RTE headings

blocks/note/note.css, blocks/note/note.scss
Jira ID: EXLM-1689
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/articles/commerce/test-page
- After: https://bugfix-exlm-1689--exlm--adobe-experience-league.hlx.live/en/articles/commerce/test-page
=> EXLM-1689 Note block css fixes

blocks/doc-actions/doc-actions.js
Jira ID: EXLM-1692
Test URLs:
- After: https://bugfix-exlm-1692--exlm--adobe-experience-league.hlx.live/
=> EXLM-1692: switch AA data layer values

scripts/auth/profile.js, scripts/profile/profile.js, scripts/scripts.js
Added new Khoros API Endpoint for fetching community Profile Details
Added the logic for the same to get the response from community Profile Details
Updated the Profile Card Block to add the community Profile Details details
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1505
Test URLs:
- After: https://feature-exlm-1505-profile-card--exlm--adobe-experience-league.hlx.live
=> EXLM 1505  Profile  Card

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js, blocks/curated-cards/curated-cards.js, scripts/coveo-headless/index.js, scripts/lib-franklin.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1542
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
- After: https://exlm-1542--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
=> feat: product filter for TL EXLM-1542

blocks/browse-filters/browse-filters.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1543
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
- After: https://fix-exlm-1543--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
=> fix: css update exlm-1543

blocks/product-interests/product-interests.css, blocks/product-interests/product-interests.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1597
Test URLs:
- After: https://bugfix-exlm-1711--exlm--adobe-experience-league.hlx.live
=> EXLM 1711 - Product Interests UI issues

blocks/article-marquee/article-marquee.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1694
Test URLs:
- After: https://feat-exlm-1694--exlm--adobe-experience-league.hlx.page
=> readtime removed when time is not authored

blocks/fragment/fragment.js
Jira ID:
Test URLs:
- After: https://ugp-10894--exlm--adobe-experience-league.hlx.page/en/docs/marketo/using/getting-started/things-to-know/icon-glossary?martech=off
=> Fragment Block

blocks/product-experience-level/product-experience-level.css, blocks/product-interests/product-interests.js, scripts/signup-flow/signup-flow.css, scripts/signup-flow/signup-flow.js, scripts/toast/toast.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1729
Test URLs:
- After: https://bugfix-exlm-1729--exlm--adobe-experience-league.hlx.live
=> EXLM 1729 - Profile Interest Signup flow issues

blocks/featured-content/featured-content.js, component-definition.json, component-filters.json, component-models.json
Jira ID: EXLM-1739
Test URLs:
- After: https://exlm-1739--exlm--adobe-experience-league.hlx.live
=> EXLM-1739 Bookmarks block

scripts/browse-card/browse-card.css
Updated the CSS for the Article Card Heading from Celery to Grey 
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1703
Test URLs:
- After: https://feature-exlm-1705-insights--exlm--adobe-experience-league.hlx.live
Browse Filters
Curated Cards
Tabbed Cards
=> EXLM 1703 Actionable Insights

blocks/tags/tags.css, blocks/tags/tags.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1726
Test URLs:
- After: https://feat-exlm-1726-fixes--exlm--adobe-experience-league.hlx.page
=> EXLM-1726 CSS Fixes

blocks/browse-filters/browse-filter-utils.js, component-models.json, scripts/browse-card/browse-cards-constants.js
Updated the term Article to Actionable Insights in component-models and related blocks
Jira ID:https://jira.corp.adobe.com/browse/EXLM-1700
Test URLs:
- After: https://feature-exlm-1700-insights--exlm--adobe-experience-league.hlx.live
Curated Cards
Tabbed Cards
Browse Filters
Featured Cards
=> EXLM 1700 Actionable Insights

blocks/article-marquee/article-marquee.js, blocks/author-summary/author-summary.js
Jira ID: EXLM-1693
Test URLs:
- After: https://exlm-1693--exlm--adobe-experience-league.hlx.live
=> EXLM-1693 Handled null case for author bio link

blocks/article-marquee/article-marquee.css, blocks/author-summary/author-summary.css
Jira ID: EXLM-1773
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-article
- After: https://exlm-1773--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-article
=> EXLM-1773 Author summary css fixes

blocks/article-marquee/article-marquee.js, blocks/author-summary/author-summary.js
Jira ID: EXLM-1693
Test URLs:
- After: https://exlm-1693--exlm--adobe-experience-league.hlx.live
=> EXLM-1693 Handled duplicate author bio links

scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1674
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab
- After: https://exlm-1674--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab
=> EXLM 1674 - Center images in article pages

component-models.json
Jira ID: EXLM-1544
Test URLs:
- After: https://tabs-update--exlm--adobe-experience-league.hlx.live
=> EXLM-1544 Tabs models.json update

blocks/article-marquee/article-marquee.js, blocks/bookmarks/bookmarks.css, blocks/bookmarks/bookmarks.js, blocks/doc-actions/doc-actions.js, blocks/playlist/actions/playlist-bookmark-action.js, scripts/bookmark/bookmark.js, scripts/browse-card/browse-card.js, scripts/coveo-headless/index.js, scripts/data-service/article-data-service.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
- After: https://feat-bookmarks-card--exlm--adobe-experience-league.hlx.live/en/actionable-insights?martext=off
=> feat: bookmarks card impl

blocks/bookmarks/bookmarks.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1565
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live?martext=off
- After: https://exlm-1565--exlm--adobe-experience-league.hlx.live?martext=off
=> chore: dev teting fixes exlm-1565

blocks/playlist-browse/dom-helpers.js, blocks/playlist-browse/playlist-browse.js
Jira ID:
Test URLs:
- After: https://playlist--exlm--adobe-experience-league.hlx.page/en/playlists?martech=off
=> Playlist Index Page -  Docs

blocks/topic-results/topic-results.js, component-definition.json, component-filters.json
=> Adding stub for topic results block

component-filters.json
=> Adding topic results to section

blocks/note/note.css, blocks/note/note.scss
Jira ID: EXLM-1798 
Test URLs:
- After: https://bugfix-exlm-1798--exlm--adobe-experience-league.hlx.live
=> EXLM-1798 Notes issue fix

blocks/awards/awards.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1807
Test URLs:
- After: https://feat-exlm-1579-cssfixe--exlm--adobe-experience-league.hlx.page
=> EXLM-1807 Css fixes for Awards Block

blocks/article-marquee/article-marquee.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1388--exlm--adobe-experience-league.hlx.live/
=> Article Marquee - Bookmark Fix

blocks/playlist/playlist-action-menu.js, blocks/playlist/playlist-utils.js, blocks/playlist/playlist.js, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID:
Test URLs:
- After: https://playlist--exlm--adobe-experience-league.hlx.page/en/playlists/aem-cloud-manager-skill-builder?martech=off
- After: https://playlist--exlm--adobe-experience-league.hlx.page/en/playlists?martech=off
=> Playlists - Placeholders and Transcript loading state

blocks/browse-filters/browse-filter-utils.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1789
Test URLs:
- After: https://feat-exlm-1789--exlm--adobe-experience-league.hlx.page
=> EXLM-1789 Description changes for adobe & external in browse filters

scripts/editor-support.js
ToC is not handling headings and subheadings correctly in UE
Jira ID: EXLM-1805
Test URLs:
- After: https://bugfix-exlm-1805--exlm--adobe-experience-league.hlx.live/
=> EXLM-1805: ToC is not handling headings and subheadings correctly in UE

scripts/data-service/coveo/coveo-token-service.js
Jira ID:
Test URLs:
- After: https://coveo-token--exlm--adobe-experience-league.hlx.live
=> Uncommented coveo token code for dev and stage

scripts/scripts.js
Jira ID: EXLM-1825
Test URLs:
- After: https://bugfix-exlm-1825--exlm--adobe-experience-league.hlx.live/
=> EXLM-1825: Perpective page not rendering if plain sections are used

component-definition.json, component-filters.json, component-models.json
Jira ID:
Test URLs:
- After: https://enable-tabs-block--exlm--adobe-experience-league.hlx.live
=> Enabled Tabs block

scripts/articles/articles.css, scripts/scripts.js, styles/styles.css, styles/styles.scss
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1810 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab
- After: https://exlm-1810--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab?martech=off
=> EXLM 1810 - Fix mini-toc layout issue

blocks/browse-filters/browse-filters.css, blocks/browse-filters/browse-filters.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1802
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights
- After: https://exlm-1802--exlm--adobe-experience-league.hlx.live/en/actionable-insights
=> EXLM 1802 - Add All Solutions to dropdown in browse Filters

blocks/tabbed-cards/tabbed-cards.js
Jira ID:
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
- After: https://tabbed-card-fix--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> Tabbed cards css fix for no results

blocks/awards/awards.js, blocks/bookmarks/bookmarks.css, blocks/bookmarks/bookmarks.js, scripts/pagination/pagination.css, scripts/pagination/pagination.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1797
Test URLs:
- After: https://feat-pagination-comp--exlm--adobe-experience-league.hlx.live?martech=off
=> feat: pagination component on profile page EXLM-1797

scripts/editor-support.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1809
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab
- After: https://exlm-1809--exlm--adobe-experience-league.hlx.live/en/actionable-insights/test-tab
=> EXLM 1809 - Preserve article layout in UE

scripts/user-actions/user-actions.js
Jira ID:
Test URLs:
- After: https://user-actions--exlm--adobe-experience-league.hlx.live
https://author-p122525-e1200861.adobeaemcloud.com/ui#/@amc/aem/universal-editor/canvas/author-p122525-e1200861.adobeaemcloud.com/content/exlm/global/en/browse/experience-manager.html?ref=user-actions
=> User actions CSS for UE

scripts/browse-card/browse-card.js, scripts/user-actions/user-actions.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1830--exlm--adobe-experience-league.hlx.live/
=> Copy Link Fix

scripts/browse-card/browse-card.css, scripts/browse-card/browse-card.js, scripts/browse-card/browse-cards-constants.js
Jira ID: EXLM-1775
Test URLs:
- After: https://perspectives--exlm--adobe-experience-league.hlx.live
=> Updated Articles to Perspectives

styles/theme/browse-product.css
Jira ID:
Test URLs:
- After: https://style-themes--exlm--adobe-experience-league.hlx.live
=> Added browse-product.css

blocks/browse-filters/browse-filter-utils.js, blocks/browse-filters/browse-filters.js, blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1546
Test URLs:
- After: https://exlm-1546--exlm--adobe-experience-league.hlx.live/
=> feat: author block updates exlm-1546

blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1804
Test URLs:
- After: https://feat-exlm-1804-fixes--exlm--adobe-experience-league.hlx.page
=> EXLM-1804 Dropdown selection fix

blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1804
Test URLs:
- After: https://feat-exlm-1804-fix2--exlm--adobe-experience-league.hlx.page
=> EXLM-1804 fix for array and string case of industry interest

blocks/browse-filters/browse-filters.js
Jira ID:
Test URLs:
- After: https://browse-filters--exlm--adobe-experience-league.hlx.live
=> Browse Filters fix

blocks/target-insertion/target-insertion.js, scripts/tutorial-widgets/tutorial-widgets.js
Jira ID: UGP-11193
Test URLs:
- After: https://ugp-11193--exlm--adobe-experience-league.hlx.page/en/docs/integrations-learn/experience-cloud/solution-categories/content-management?martech=off
=> UGP-11193 - insert recommendation-more-help as last block

blocks/awards/awards.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1865
Test URLs:
- After: https://feat-exlm-1865--exlm--adobe-experience-league.hlx.page
=> EXLM-1865 SVG icon update after pagination and CSS fixes for cards size

blocks/featured-authors/featured-authors.js, blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js, scripts/scripts.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1835, https://jira.corp.adobe.com/browse/EXLM-1836
Test URLs:
- After: https://exlm-1835--exlm--adobe-experience-league.hlx.live/
=> fix: feature content block exlm-1835 exlm-1836

blocks/featured-content/featured-content.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1836
Test URLs:
- After: https://exlm-1836--exlm--adobe-experience-league.hlx.live/
=> fix: featured block mobile css updates exlm-1836

blocks/featured-content/featured-content.css, blocks/featured-content/featured-content.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1836
Test URLs:
- After: https://exlm-1836-1--exlm--adobe-experience-league.hlx.live/
=> fix: update css for low res & author css based on company exlm-1836

component-definition.json, component-models.json
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1546
Test URLs:
- After: https://feat-exlm-1546-ueFix--exlm--adobe-experience-league.hlx.page
=> EXLM-1546 UE fixes for default value for featured content

scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://bugfix-exlm-1801--exlm--adobe-experience-league.hlx.live/?martech=off
=> Bookmark Issue Fix

blocks/tags/tags.css, scripts/articles/articles.css
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1878 
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives/test-tab
- After: https://exlm-1878--exlm--adobe-experience-league.hlx.live/en/perspectives/test-tab
=> EXLM 1878 - Style updates to perspective pages

blocks/role-and-industry/role-and-industry.css, blocks/role-and-industry/role-and-industry.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1845 , https://jira.corp.adobe.com/browse/EXLM-1844
Test URLs:
- After: https://feat-exlm-1844--exlm--adobe-experience-league.hlx.live/
=> Placeholder key and Fallback update for Role cards

blocks/tags/tags.css, blocks/tags/tags.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1864
Test URLs:
- After: https://feat-exlm-1864--exlm--adobe-experience-league.hlx.page
=> EXLM-1864 Product tag added

scripts/browse-card/browse-card.js
Jira ID: EXLM-1882
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
- After: https://bugfix-exlm-1882--exlm--adobe-experience-league.hlx.live/en/browse?martech=off
=> EXLM-1882 Perspectives card Author Type Badge

blocks/authorable-card/authorable-card.js, component-models.json, scripts/browse-card/browse-card.js
Jira ID:
Test URLs:
- After: https://authorable-card--exlm--adobe-experience-league.hlx.live
=> Tags for authorable card

blocks/authorable-card/authorable-card.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1593
Test URLs:
- Before: https://main--exlm--adobe-experience-league.hlx.live/en/perspectives
- After: https://ac-ue--exlm--adobe-experience-league.hlx.live/en/perspectives
=> Authorable cards convert relative urls to absolute urls for UE

scripts/user-actions/bookmark.js
Jira ID: https://jira.corp.adobe.com/browse/EXLM-1872
Test URLs:
- After: https://exlm-1872--exlm--adobe-experience-league.hlx.live/
=> fix: bookmarks check update exlm-1872
